#! /bin/bash

#g++ -g -std=c++11 -L ~/lib -I ../ -l TopTreeAnaContent76 -l TopTreeAna76 -l MLP -l TreePlayer -l TMVA -l XMLIO -I `root-config --incdir` `root-config --libs` Ntupler.cc -o TreeMaker
g++ -g -std=c++11 -L ~/lib -I ../ -l TopTreeAnaContent76 -l TopTreeAna76 -l MLP -l TreePlayer -l KinFit -l TMVA -l XMLIO -I `root-config --incdir` `root-config --libs` FCNC_TreeProcessor.cc -o MACRO_TreeProcessor

