// Class: ReadBDT
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.06/01       [394753]
Creator        : kskovpen
Date           : Fri Feb  3 15:22:12 2017
Host           : Linux vocms0301.cern.ch 2.6.32-642.11.1.el6.x86_64 #1 SMP Wed Nov 16 09:40:09 CET 2016 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /storage_mnt/storage/user/kskovpen/analysis/tHFCNC/CMSSW_8_0_25/src/TopKinFit/test/Validation/TopTopLepHbb/MVA
Training events: 149345
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "100" [Number of trees in the forest]
MaxDepth: "3" [Max depth of the decision tree allowed]
nCuts: "20" [Number of grid points in variable range used in finding optimal cut in node splitting]
SeparationType: "giniindex" [Separation criterion for node splitting]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
MinNodeSize: "5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
BoostType: "AdaBoost" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
UseBaggedBoost: "False" [Use only a random subsample of all events for growing the trees in each boost iteration.]
Shrinkage: "1.000000e+00" [Learning rate for GradBoost algorithm]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "2" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split with RandomisedTree option]
BaggedSampleFraction: "6.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "inverseboostnegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "6.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 4
HiggsRecMCSVv2M               HiggsRecMCSVv2M               HiggsRecMCSVv2M               HiggsRecMCSVv2M                                                 'F'    [18.1019706726,1670.60339355]
TopLepRecMCSVv2M              TopLepRecMCSVv2M              TopLepRecMCSVv2M              TopLepRecMCSVv2M                                                'F'    [49.4397544861,1912.0411377]
HiggsTopLepRecDrCSVv2M        HiggsTopLepRecDrCSVv2M        HiggsTopLepRecDrCSVv2M        HiggsTopLepRecDrCSVv2M                                          'F'    [0.0063662128523,9.0174369812]
TopLepRecPtCSVv2M             TopLepRecPtCSVv2M             TopLepRecPtCSVv2M             TopLepRecPtCSVv2M                                               'F'    [0.492339491844,915.629699707]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDTNode
   
#ifndef BDTNode__def
#define BDTNode__def
   
class BDTNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDTNode ( BDTNode* left,BDTNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTNode();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTNode* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTNode*   fLeft;     // pointer to the left daughter node
   BDTNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDTNode::~BDTNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDTNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDTNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT : public IClassifierReader {

 public:

   // constructor
   ReadBDT( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDT" ),
        fNvars( 4 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "HiggsRecMCSVv2M", "TopLepRecMCSVv2M", "HiggsTopLepRecDrCSVv2M", "TopLepRecPtCSVv2M" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[4];
   double fVmax[4];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[4];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTNode*)current->GetRight();
         else current=(BDTNode*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
};

void ReadBDT::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(0.442376006588969);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.677286,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.353038,-99) , 
0, 78.0506, 0, 0, 0.635929,-99) , 
NN(
0, 
0, 
-1, 2.43499, 0, -1, 0.325395,-99) , 
1, 226.83, 1, 0, 0.571462,-99) , 
NN(
0, 
0, 
-1, 231.052, 1, -1, 0.102093,-99) , 
0, 175.483, 1, 0, 0.5,-99)    );
  // itree = 1
  fBoostWeights.push_back(0.298206);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 154.871, 0, 1, 0.610143,-99) , 
NN(
0, 
0, 
-1, 130.511, 1, -1, 0.384664,-99) , 
2, 2.58096, 0, 0, 0.532257,-99) , 
NN(
0, 
0, 
-1, 231.052, 1, -1, 0.150357,-99) , 
0, 175.483, 1, 0, 0.479403,-99)    );
  // itree = 2
  fBoostWeights.push_back(0.275067);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.588628,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.410402,-99) , 
0, 90.9001, 0, 0, 0.541402,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.203692,-99) , 
0, 145.499, 1, 0, 0.5097,-99) , 
NN(
0, 
0, 
-1, 231.052, 1, -1, 0.192539,-99) , 
0, 175.483, 1, 0, 0.468586,-99)    );
  // itree = 3
  fBoostWeights.push_back(0.218182);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.638898,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.437131,-99) , 
2, 2.21366, 0, 0, 0.601985,-99) , 
NN(
0, 
0, 
-1, 138.005, 1, -1, 0.432574,-99) , 
3, 162.731, 0, 0, 0.486613,-99) , 
NN(
0, 
0, 
-1, 131.226, 0, -1, 0.238934,-99) , 
0, 175.483, 1, 0, 0.456084,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.190366);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 116.314, 0, 1, 0.552867,-99) , 
NN(
0, 
0, 
-1, 131.226, 0, -1, 0.308812,-99) , 
0, 144.309, 1, 0, 0.507592,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.225674,-99) , 
1, 315.526, 1, 0, 0.485241,-99)    );
  // itree = 5
  fBoostWeights.push_back(0.151249);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.544759,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461131,-99) , 
3, 116.314, 0, 0, 0.505473,-99) , 
NN(
0, 
0, 
-1, 131.226, 0, -1, 0.350848,-99) , 
0, 144.309, 1, 0, 0.477411,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.260661,-99) , 
1, 315.526, 1, 0, 0.460826,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.11972);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.599103,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485167,-99) , 
2, 3.44656, 0, 0, 0.503212,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526592,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.285285,-99) , 
3, 131.226, 0, 0, 0.386022,-99) , 
0, 144.309, 1, 0, 0.482228,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.290844,-99) , 
1, 315.526, 1, 0, 0.467951,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.134281);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.539317,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.437435,-99) , 
0, 66.1802, 0, 0, 0.530965,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.547595,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.318713,-99) , 
3, 131.226, 0, 0, 0.416447,-99) , 
0, 144.309, 1, 0, 0.512134,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506974,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.3736,-99) , 
1, 253.579, 1, 0, 0.439983,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.319133,-99) , 
1, 307.079, 1, 0, 0.395855,-99) , 
1, 226.83, 1, 0, 0.486419,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.0912303);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512241,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.432614,-99) , 
2, 1.72276, 0, 0, 0.5027,-99) , 
NN(
0, 
0, 
-1, 2.82077, 0, -1, 0.356558,-99) , 
0, 138.005, 1, 0, 0.484515,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.3655,-99) , 
0, 175.483, 1, 0, 0.47128,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.100296);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.91742, 0, 1, 0.541937,-99) , 
NN(
0, 
0, 
-1, 130.335, 1, -1, 0.4584,-99) , 
3, 218.382, 0, 0, 0.471998,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.342211,-99) , 
1, 315.526, 1, 0, 0.462694,-99)    );
  // itree = 10
  fBoostWeights.push_back(0.0879954);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521527,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.438876,-99) , 
1, 136.317, 0, 0, 0.507573,-99) , 
NN(
0, 
0, 
-1, 133.812, 1, -1, 0.440543,-99) , 
1, 201.481, 1, 0, 0.488848,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.365132,-99) , 
1, 315.526, 1, 0, 0.480076,-99)    );
  // itree = 11
  fBoostWeights.push_back(0.093902);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.575272,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.533768,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.448554,-99) , 
3, 117.829, 0, 0, 0.498541,-99) , 
2, 3.86826, 0, 0, 0.514042,-99) , 
NN(
0, 
0, 
-1, 151.646, 1, -1, 0.453941,-99) , 
2, 3.01006, 0, 0, 0.477504,-99)    );
  // itree = 12
  fBoostWeights.push_back(0.068762);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515975,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.420305,-99) , 
0, 132.288, 1, 0, 0.507174,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504098,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.392005,-99) , 
3, 131.226, 0, 0, 0.440257,-99) , 
0, 144.309, 1, 0, 0.49569,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.394208,-99) , 
1, 315.526, 1, 0, 0.488586,-99)    );
  // itree = 13
  fBoostWeights.push_back(0.0820884);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527961,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472007,-99) , 
0, 103.745, 0, 0, 0.499935,-99) , 
NN(
0, 
0, 
-1, 149.783, 1, -1, 0.427416,-99) , 
0, 130.511, 1, 0, 0.486409,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.420282,-99) , 
0, 175.483, 1, 0, 0.479319,-99)    );
  // itree = 14
  fBoostWeights.push_back(0.0456984);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.548897,-99) , 
NN(
0, 
0, 
-1, 315.526, 1, -1, 0.479408,-99) , 
2, 3.86825, 0, 0, 0.484909,-99)    );
  // itree = 15
  fBoostWeights.push_back(0.035633);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507599,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.449185,-99) , 
1, 264.831, 1, 0, 0.504097,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.440455,-99) , 
2, 1.30391, 0, 0, 0.499442,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.428181,-99) , 
1, 315.526, 1, 0, 0.494517,-99)    );
  // itree = 16
  fBoostWeights.push_back(0.0446052);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520726,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491948,-99) , 
2, 2.58096, 1, 0, 0.50188,-99) , 
NN(
0, 
0, 
-1, 150.496, 1, -1, 0.436118,-99) , 
0, 138.005, 1, 0, 0.494023,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.446532,-99) , 
0, 175.483, 1, 0, 0.488968,-99)    );
  // itree = 17
  fBoostWeights.push_back(0.0421361);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536224,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490824,-99) , 
3, 78.4503, 0, 0, 0.522604,-99) , 
NN(
0, 
0, 
-1, 152.369, 1, -1, 0.487263,-99) , 
2, 3.13267, 0, 0, 0.49862,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.435869,-99) , 
2, 1.29366, 0, 0, 0.494057,-99)    );
  // itree = 18
  fBoostWeights.push_back(0.0364736);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51138,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456828,-99) , 
1, 125.46, 0, 0, 0.50791,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456438,-99) , 
1, 315.526, 1, 0, 0.504417,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.446257,-99) , 
2, 1.29366, 0, 0, 0.500195,-99)    );
  // itree = 19
  fBoostWeights.push_back(0.0355776);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535791,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52812,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500964,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.407899,-99) , 
0, 151.646, 1, 0, 0.48676,-99) , 
3, 262.293, 0, 0, 0.491003,-99) , 
2, 3.86825, 0, 0, 0.494548,-99)    );
  // itree = 20
  fBoostWeights.push_back(0.0400325);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526932,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519246,-99) , 
NN(
0, 
0, 
-1, 151.646, 1, -1, 0.480571,-99) , 
3, 262.293, 0, 0, 0.484537,-99) , 
2, 3.86825, 0, 0, 0.487891,-99)    );
  // itree = 21
  fBoostWeights.push_back(0.0416879);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519854,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484907,-99) , 
1, 148.99, 0, 0, 0.507714,-99) , 
NN(
0, 
0, 
-1, 145.032, 1, -1, 0.479052,-99) , 
1, 188.811, 1, 0, 0.49716,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457123,-99) , 
1, 315.526, 1, 0, 0.49442,-99)    );
  // itree = 22
  fBoostWeights.push_back(0.0242866);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525502,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499373,-99) , 
2, 3.32219, 0, 0, 0.504805,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504725,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.423856,-99) , 
3, 120.98, 1, 0, 0.464788,-99) , 
2, 1.65445, 0, 0, 0.500062,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466007,-99) , 
3, 44.0703, 0, 0, 0.496833,-99)    );
  // itree = 23
  fBoostWeights.push_back(0.0233705);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 210.083, 0, 1, 0.507086,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46583,-99) , 
3, 44.0703, 0, 0, 0.503217,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461921,-99) , 
2, 1.29366, 0, 0, 0.50023,-99)    );
  // itree = 24
  fBoostWeights.push_back(0.0209629);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510538,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495646,-99) , 
2, 2.59228, 1, 0, 0.501076,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457411,-99) , 
1, 264.831, 1, 0, 0.498449,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466262,-99) , 
1, 315.526, 1, 0, 0.496249,-99)    );
  // itree = 25
  fBoostWeights.push_back(0.0314385);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514338,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494068,-99) , 
0, 97.5531, 0, 0, 0.508528,-99) , 
NN(
0, 
0, 
-1, 211.98, 1, -1, 0.486824,-99) , 
3, 87.6483, 0, 0, 0.501954,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509134,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.415912,-99) , 
0, 125.887, 1, 0, 0.47303,-99) , 
2, 1.72276, 0, 0, 0.498143,-99)    );
  // itree = 26
  fBoostWeights.push_back(0.0181612);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 3.37423, 0, 1, 0.504326,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479106,-99) , 
3, 44.0703, 0, 0, 0.501998,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501275,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.423569,-99) , 
0, 125.887, 1, 0, 0.471224,-99) , 
2, 1.72276, 0, 0, 0.497945,-99)    );
  // itree = 27
  fBoostWeights.push_back(0.0324015);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 203.836, 0, 1, 0.508689,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506077,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.420898,-99) , 
0, 152.369, 1, 0, 0.494156,-99) , 
3, 174.804, 0, 0, 0.498295,-99) , 
NN(
0, 
0, 
-1, 125.887, 1, -1, 0.470179,-99) , 
2, 1.72276, 0, 0, 0.494594,-99)    );
  // itree = 28
  fBoostWeights.push_back(0.0199434);
  fForest.push_back( 
NN(
0, 
0, 
-1, 315.526, 1, -1, 0.49003,-99)    );
  // itree = 29
  fBoostWeights.push_back(0.0149301);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501568,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477319,-99) , 
1, 131.493, 0, 0, 0.499199,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460958,-99) , 
1, 264.831, 1, 0, 0.496902,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469218,-99) , 
1, 315.526, 1, 0, 0.495014,-99)    );
  // itree = 30
  fBoostWeights.push_back(0.0252135);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516171,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505938,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487725,-99) , 
3, 175.181, 0, 0, 0.493079,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47106,-99) , 
2, 1.47745, 0, 0, 0.490839,-99) , 
2, 3.86825, 0, 0, 0.492847,-99)    );
  // itree = 31
  fBoostWeights.push_back(0.0193772);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507471,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493335,-99) , 
2, 2.59228, 1, 0, 0.498488,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466996,-99) , 
1, 264.831, 1, 0, 0.496598,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474365,-99) , 
1, 315.526, 1, 0, 0.495084,-99)    );
  // itree = 32
  fBoostWeights.push_back(0.0241492);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 3.97337, 0, 1, 0.508112,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502979,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463706,-99) , 
0, 140.173, 1, 0, 0.495874,-99) , 
2, 3.13266, 0, 0, 0.500553,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517072,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490362,-99) , 
3, 65.2112, 1, 0, 0.501053,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460417,-99) , 
3, 123.035, 1, 0, 0.483606,-99) , 
2, 2.15186, 0, 0, 0.496834,-99)    );
  // itree = 33
  fBoostWeights.push_back(0.0445127);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518254,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463883,-99) , 
0, 126.208, 1, 0, 0.508071,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.445268,-99) , 
0, 151.646, 1, 0, 0.498346,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515549,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488227,-99) , 
1, 226.83, 0, 0, 0.493781,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457452,-99) , 
2, 1.92843, 0, 0, 0.488552,-99) , 
3, 131.226, 1, 0, 0.493893,-99)    );
  // itree = 34
  fBoostWeights.push_back(0.0230247);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522254,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493946,-99) , 
0, 144.309, 0, 0, 0.498613,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464772,-99) , 
1, 264.831, 1, 0, 0.496584,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472052,-99) , 
1, 315.526, 1, 0, 0.494919,-99)    );
  // itree = 35
  fBoostWeights.push_back(0.0171997);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 139.45, 0, 1, 0.506456,-99) , 
NN(
0, 
0, 
-1, 145.032, 1, -1, 0.490411,-99) , 
1, 188.811, 1, 0, 0.500556,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477794,-99) , 
1, 315.526, 1, 0, 0.499012,-99)    );
  // itree = 36
  fBoostWeights.push_back(0.0170276);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507482,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494304,-99) , 
1, 179.761, 1, 0, 0.50111,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473925,-99) , 
1, 125.46, 0, 0, 0.499419,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482087,-99) , 
1, 315.526, 1, 0, 0.498243,-99)    );
  // itree = 37
  fBoostWeights.push_back(0.00976649);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512373,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499297,-99) , 
2, 3.398, 0, 0, 0.50152,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482495,-99) , 
3, 44.0703, 0, 0, 0.499741,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484642,-99) , 
2, 1.29366, 0, 0, 0.498656,-99)    );
  // itree = 38
  fBoostWeights.push_back(0.0349777);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524692,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474793,-99) , 
0, 126.208, 1, 0, 0.515405,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464534,-99) , 
0, 151.646, 1, 0, 0.505782,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508567,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489114,-99) , 
3, 78.4503, 0, 0, 0.503666,-99) , 
NN(
0, 
0, 
-1, 2.71234, 0, -1, 0.478877,-99) , 
2, 2.88748, 0, 0, 0.497351,-99) , 
2, 2.58096, 1, 0, 0.500399,-99)    );
  // itree = 39
  fBoostWeights.push_back(0.0274635);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518155,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489746,-99) , 
1, 307.079, 1, 0, 0.508153,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536168,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490812,-99) , 
0, 145.032, 0, 0, 0.497552,-99) , 
1, 226.83, 0, 0, 0.499783,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485329,-99) , 
2, 1.29366, 0, 0, 0.498745,-99)    );
  // itree = 40
  fBoostWeights.push_back(0.0270538);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.554321,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509121,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456155,-99) , 
0, 151.646, 1, 0, 0.499,-99) , 
2, 2.45832, 0, 0, 0.506715,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506893,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494954,-99) , 
2, 2.88748, 0, 0, 0.503908,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507085,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476908,-99) , 
2, 3.14535, 0, 0, 0.489978,-99) , 
0, 97.5531, 0, 0, 0.499922,-99) , 
2, 2.58096, 1, 0, 0.502378,-99)    );
  // itree = 41
  fBoostWeights.push_back(0.0156941);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 226.83, 0, 1, 0.502933,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485288,-99) , 
3, 44.0703, 0, 0, 0.501331,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522532,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483791,-99) , 
0, 111.244, 1, 0, 0.50175,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473692,-99) , 
1, 204.566, 1, 0, 0.492343,-99) , 
2, 2.15186, 0, 0, 0.499361,-99)    );
  // itree = 42
  fBoostWeights.push_back(0.0266278);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.544368,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526711,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488197,-99) , 
0, 84.874, 1, 0, 0.494941,-99) , 
2, 2.45832, 0, 0, 0.501826,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527465,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490637,-99) , 
1, 203.836, 0, 0, 0.501305,-99) , 
NN(
0, 
0, 
-1, 144.555, 1, -1, 0.491569,-99) , 
3, 174.804, 0, 0, 0.494557,-99) , 
2, 2.58096, 1, 0, 0.497183,-99)    );
  // itree = 43
  fBoostWeights.push_back(0.0116812);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 144.309, 0, 1, 0.504295,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474164,-99) , 
1, 264.831, 1, 0, 0.502492,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490635,-99) , 
1, 315.526, 1, 0, 0.50169,-99)    );
  // itree = 44
  fBoostWeights.push_back(0.0260375);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51517,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461584,-99) , 
0, 151.646, 1, 0, 0.506818,-99) , 
NN(
0, 
0, 
-1, 3.2098, 1, -1, 0.493197,-99) , 
3, 131.226, 1, 0, 0.5007,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501061,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47942,-99) , 
1, 125.462, 0, 0, 0.490889,-99) , 
1, 138.135, 0, 0, 0.49949,-99)    );
  // itree = 45
  fBoostWeights.push_back(0.0150452);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50816,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481887,-99) , 
0, 151.646, 1, 0, 0.503741,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500374,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489055,-99) , 
0, 97.594, 0, 0, 0.497231,-99) , 
2, 3.01006, 1, 0, 0.501157,-99) , 
NN(
0, 
0, 
-1, 125.462, 0, -1, 0.490496,-99) , 
1, 138.135, 0, 0, 0.499842,-99)    );
  // itree = 46
  fBoostWeights.push_back(0.0251949);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510644,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482468,-99) , 
2, 3.30135, 1, 0, 0.504835,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481519,-99) , 
2, 1.92843, 0, 0, 0.501494,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505392,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465218,-99) , 
0, 132.568, 1, 0, 0.500866,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468152,-99) , 
0, 151.646, 1, 0, 0.495824,-99) , 
3, 131.226, 0, 0, 0.498404,-99)    );
  // itree = 47
  fBoostWeights.push_back(0.0353768);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509393,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530364,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492439,-99) , 
0, 123.283, 1, 0, 0.519253,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519281,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482898,-99) , 
0, 78.0506, 1, 0, 0.487785,-99) , 
1, 226.83, 0, 0, 0.494049,-99) , 
0, 175.483, 0, 0, 0.49565,-99)    );
  // itree = 48
  fBoostWeights.push_back(0.0214398);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.96574, 1, 1, 0.505894,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510688,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481321,-99) , 
1, 175.496, 1, 0, 0.494418,-99) , 
2, 2.56912, 0, 0, 0.502331,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5055,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465689,-99) , 
0, 75.3348, 0, 0, 0.500126,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471357,-99) , 
0, 151.646, 1, 0, 0.495694,-99) , 
3, 131.226, 0, 0, 0.498713,-99)    );
  // itree = 49
  fBoostWeights.push_back(0.0244243);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531267,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503022,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479063,-99) , 
1, 204.566, 1, 0, 0.49522,-99) , 
2, 2.45832, 0, 0, 0.500238,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503529,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49447,-99) , 
2, 3.17443, 1, 0, 0.500232,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511189,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476271,-99) , 
2, 3.50048, 0, 0, 0.486561,-99) , 
3, 131.226, 0, 0, 0.493226,-99) , 
2, 2.58096, 1, 0, 0.495759,-99)    );
  // itree = 50
  fBoostWeights.push_back(0.0228896);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501952,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527859,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494573,-99) , 
0, 100.916, 0, 0, 0.515122,-99) , 
NN(
0, 
0, 
-1, 232.12, 1, -1, 0.489122,-99) , 
1, 226.83, 0, 0, 0.494293,-99) , 
0, 175.483, 0, 0, 0.495092,-99)    );
  // itree = 51
  fBoostWeights.push_back(0.0163965);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52276,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49708,-99) , 
0, 144.309, 0, 0, 0.501301,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467853,-99) , 
1, 264.831, 1, 0, 0.499298,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485429,-99) , 
1, 315.526, 1, 0, 0.498361,-99)    );
  // itree = 52
  fBoostWeights.push_back(0.0207175);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.556785,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499651,-99) , 
3, 131.226, 0, 0, 0.524755,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503802,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4692,-99) , 
3, 232.12, 1, 0, 0.498904,-99) , 
0, 144.309, 0, 0, 0.502964,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510419,-99) , 
NN(
0, 
0, 
-1, 2.31923, 0, -1, 0.489756,-99) , 
2, 3.24453, 0, 0, 0.495037,-99) , 
1, 226.83, 1, 0, 0.501279,-99)    );
  // itree = 53
  fBoostWeights.push_back(0.0239034);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510852,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505904,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466115,-99) , 
0, 65.7948, 0, 0, 0.502776,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.42311,-99) , 
0, 218.418, 1, 0, 0.498184,-99) , 
3, 261.96, 0, 0, 0.49943,-99)    );
  // itree = 54
  fBoostWeights.push_back(0.0121751);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504878,-99) , 
NN(
0, 
0, 
-1, 218.418, 1, -1, 0.493781,-99) , 
3, 261.96, 0, 0, 0.494873,-99)    );
  // itree = 55
  fBoostWeights.push_back(0.0184812);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52801,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51348,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491842,-99) , 
0, 84.874, 1, 0, 0.495631,-99) , 
2, 2.45832, 0, 0, 0.500136,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504732,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492352,-99) , 
2, 3.15982, 0, 0, 0.497472,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478242,-99) , 
3, 44.0703, 0, 0, 0.495723,-99) , 
2, 2.58096, 1, 0, 0.497317,-99)    );
  // itree = 56
  fBoostWeights.push_back(0.0101345);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 243.719, 0, 1, 0.503662,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486738,-99) , 
0, 151.646, 1, 0, 0.500892,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.498987,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500239,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482185,-99) , 
1, 201.057, 1, 0, 0.49456,-99) , 
2, 3.86826, 0, 0, 0.495451,-99) , 
2, 3.01006, 1, 0, 0.49875,-99)    );
  // itree = 57
  fBoostWeights.push_back(0.0143282);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521762,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507249,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492216,-99) , 
3, 82.1554, 1, 0, 0.497061,-99) , 
2, 2.45832, 0, 0, 0.500497,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505047,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497824,-99) , 
2, 2.9767, 1, 0, 0.500456,-99) , 
NN(
0, 
0, 
-1, 50.2947, 0, -1, 0.491753,-99) , 
3, 131.226, 0, 0, 0.495996,-99) , 
2, 2.58096, 1, 0, 0.497622,-99)    );
  // itree = 58
  fBoostWeights.push_back(0.0184138);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536742,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495708,-99) , 
0, 144.309, 0, 0, 0.502135,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507038,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48768,-99) , 
3, 162.731, 0, 0, 0.493967,-99) , 
1, 222.607, 1, 0, 0.500026,-99) , 
NN(
0, 
0, 
-1, 125.462, 0, -1, 0.494248,-99) , 
1, 138.135, 0, 0, 0.499313,-99)    );
  // itree = 59
  fBoostWeights.push_back(0.0110038);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 144.309, 0, 1, 0.50445,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477972,-99) , 
1, 264.831, 1, 0, 0.502867,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494486,-99) , 
1, 315.526, 1, 0, 0.502302,-99)    );
  // itree = 60
  fBoostWeights.push_back(0.0050264);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506568,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509622,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49948,-99) , 
0, 175.483, 0, 0, 0.50054,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490032,-99) , 
3, 44.5139, 0, 0, 0.499683,-99) , 
2, 3.86825, 0, 0, 0.500229,-99)    );
  // itree = 61
  fBoostWeights.push_back(0.0227244);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510912,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467042,-99) , 
0, 151.646, 1, 0, 0.504173,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503734,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491446,-99) , 
3, 280.644, 0, 0, 0.494932,-99) , 
3, 174.804, 1, 0, 0.501629,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501348,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492189,-99) , 
1, 125.462, 0, 0, 0.497046,-99) , 
1, 138.135, 0, 0, 0.501064,-99)    );
  // itree = 62
  fBoostWeights.push_back(0.0203316);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511375,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506803,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491445,-99) , 
2, 2.85147, 0, 0, 0.502013,-99) , 
2, 2.22195, 1, 0, 0.503809,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505418,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468249,-99) , 
0, 68.9756, 0, 0, 0.501633,-99) , 
NN(
0, 
0, 
-1, 91.7983, 1, -1, 0.473072,-99) , 
0, 151.646, 1, 0, 0.497309,-99) , 
3, 174.804, 0, 0, 0.499114,-99)    );
  // itree = 63
  fBoostWeights.push_back(0.0289349);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505931,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524986,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499269,-99) , 
0, 123.283, 1, 0, 0.517446,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517806,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485607,-99) , 
0, 78.0506, 1, 0, 0.489926,-99) , 
1, 226.83, 0, 0, 0.495394,-99) , 
0, 175.483, 0, 0, 0.496488,-99)    );
  // itree = 64
  fBoostWeights.push_back(0.0183748);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516285,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497444,-99) , 
1, 159.918, 1, 0, 0.505779,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499726,-99) , 
1, 203.836, 1, 0, 0.503922,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504921,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466108,-99) , 
0, 68.9756, 0, 0, 0.500967,-99) , 
NN(
0, 
0, 
-1, 91.7983, 1, -1, 0.475526,-99) , 
0, 151.646, 1, 0, 0.497116,-99) , 
3, 174.804, 0, 0, 0.499005,-99)    );
  // itree = 65
  fBoostWeights.push_back(0.0167549);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514584,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496811,-99) , 
2, 3.1214, 1, 0, 0.507121,-99) , 
NN(
0, 
0, 
-1, 0, 1, 1, 0.501999,-99) , 
2, 2.53668, 0, 0, 0.505699,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502577,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482602,-99) , 
1, 222.608, 1, 0, 0.497446,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474712,-99) , 
1, 138.135, 0, 0, 0.494707,-99) , 
3, 174.804, 0, 0, 0.497757,-99)    );
  // itree = 66
  fBoostWeights.push_back(0.0124333);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 203.836, 0, 1, 0.506451,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497811,-99) , 
2, 2.53668, 0, 0, 0.504051,-99) , 
NN(
0, 
0, 
-1, 151.646, 1, -1, 0.493419,-99) , 
3, 174.804, 0, 0, 0.49637,-99)    );
  // itree = 67
  fBoostWeights.push_back(0.0116935);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508708,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507545,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498627,-99) , 
1, 203.836, 0, 0, 0.501235,-99) , 
2, 2.22195, 1, 0, 0.50267,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501962,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473092,-99) , 
0, 68.9756, 0, 0, 0.499022,-99) , 
NN(
0, 
0, 
-1, 91.7983, 1, -1, 0.482522,-99) , 
0, 151.646, 1, 0, 0.496527,-99) , 
3, 174.804, 0, 0, 0.498232,-99)    );
  // itree = 68
  fBoostWeights.push_back(0.0138072);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513177,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49663,-99) , 
3, 235.336, 1, 0, 0.505049,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498664,-99) , 
1, 203.836, 1, 0, 0.503089,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501869,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487576,-99) , 
3, 116.697, 1, 0, 0.496988,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480424,-99) , 
1, 138.135, 0, 0, 0.494993,-99) , 
3, 174.804, 0, 0, 0.49724,-99)    );
  // itree = 69
  fBoostWeights.push_back(0.0186468);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50855,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505365,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470358,-99) , 
0, 144.516, 1, 0, 0.499537,-99) , 
3, 243.284, 0, 0, 0.501988,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508299,-99) , 
NN(
0, 
0, 
-1, 85.6755, 0, -1, 0.490349,-99) , 
2, 1.7431, 1, 0, 0.493072,-99) , 
3, 131.226, 0, 0, 0.497127,-99)    );
  // itree = 70
  fBoostWeights.push_back(0.0249208);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50796,-99) , 
NN(
NN(
0, 
0, 
-1, 100.916, 0, 1, 0.516333,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511845,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487807,-99) , 
0, 78.0506, 1, 0, 0.491028,-99) , 
1, 226.83, 0, 0, 0.496056,-99) , 
0, 175.483, 0, 0, 0.497291,-99)    );
  // itree = 71
  fBoostWeights.push_back(0.020876);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 131.226, 0, 1, 0.533201,-99) , 
NN(
0, 
0, 
-1, 232.12, 1, -1, 0.494617,-99) , 
0, 144.309, 0, 0, 0.500659,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510157,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487734,-99) , 
3, 156.531, 0, 0, 0.495836,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483788,-99) , 
2, 2.43499, 0, 0, 0.491945,-99) , 
1, 226.83, 1, 0, 0.49881,-99)    );
  // itree = 72
  fBoostWeights.push_back(0.018185);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 131.226, 0, 1, 0.528002,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502884,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481335,-99) , 
3, 232.12, 1, 0, 0.499835,-99) , 
0, 144.309, 0, 0, 0.504244,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510176,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489031,-99) , 
3, 75.8948, 0, 0, 0.499776,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489467,-99) , 
3, 122.21, 1, 0, 0.494609,-99) , 
1, 226.83, 1, 0, 0.5022,-99)    );
  // itree = 73
  fBoostWeights.push_back(0.0231398);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 201.057, 0, 1, 0.506709,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505998,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460079,-99) , 
0, 62.6164, 0, 0, 0.502532,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509587,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.42725,-99) , 
0, 212.059, 1, 0, 0.476191,-99) , 
0, 151.646, 1, 0, 0.498596,-99) , 
3, 218.382, 0, 0, 0.499948,-99)    );
  // itree = 74
  fBoostWeights.push_back(0.0128386);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505199,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503211,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486336,-99) , 
2, 2.85849, 0, 0, 0.495263,-99) , 
3, 245.364, 0, 0, 0.499575,-99) , 
NN(
0, 
0, 
-1, 151.646, 1, -1, 0.493751,-99) , 
3, 174.804, 0, 0, 0.495366,-99)    );
  // itree = 75
  fBoostWeights.push_back(0.0110051);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508574,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492362,-99) , 
2, 3.0719, 1, 0, 0.502401,-99) , 
NN(
0, 
0, 
-1, 152.369, 1, -1, 0.495981,-99) , 
3, 174.804, 0, 0, 0.497787,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490583,-99) , 
2, 1.29366, 0, 0, 0.49727,-99)    );
  // itree = 76
  fBoostWeights.push_back(0.0136097);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503599,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485385,-99) , 
3, 50.2922, 0, 0, 0.501294,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489235,-99) , 
3, 261.96, 1, 0, 0.500039,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514564,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491668,-99) , 
3, 119.785, 0, 0, 0.501946,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488892,-99) , 
2, 1.53884, 0, 0, 0.495899,-99) , 
2, 2.15186, 0, 0, 0.499131,-99)    );
  // itree = 77
  fBoostWeights.push_back(0.0116891);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518797,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502711,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491443,-99) , 
3, 122.653, 1, 0, 0.497799,-99) , 
2, 2.45832, 0, 0, 0.500721,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501076,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490936,-99) , 
0, 172.464, 1, 0, 0.499799,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501022,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478458,-99) , 
2, 3.14535, 0, 0, 0.488235,-99) , 
0, 97.5531, 0, 0, 0.496486,-99) , 
2, 2.58096, 1, 0, 0.498016,-99)    );
  // itree = 78
  fBoostWeights.push_back(0.00962945);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515878,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50011,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491852,-99) , 
1, 204.566, 1, 0, 0.497425,-99) , 
2, 2.45832, 0, 0, 0.499991,-99) , 
NN(
0, 
0, 
-1, 97.5531, 0, -1, 0.495038,-99) , 
2, 2.58096, 1, 0, 0.496828,-99)    );
  // itree = 79
  fBoostWeights.push_back(0.00755409);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503154,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512397,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498359,-99) , 
1, 201.057, 0, 0, 0.502821,-99) , 
NN(
0, 
0, 
-1, 151.646, 1, -1, 0.496428,-99) , 
3, 218.737, 0, 0, 0.497537,-99) , 
2, 3.86825, 0, 0, 0.497982,-99)    );
  // itree = 80
  fBoostWeights.push_back(0.0116041);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 125.462, 1, 1, 0.503384,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504037,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48488,-99) , 
0, 151.646, 1, 0, 0.501105,-99) , 
NN(
0, 
0, 
-1, 245.367, 0, -1, 0.492782,-99) , 
3, 174.804, 1, 0, 0.498816,-99) , 
1, 138.135, 1, 0, 0.49938,-99)    );
  // itree = 81
  fBoostWeights.push_back(0.0151118);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505645,-99) , 
NN(
NN(
0, 
0, 
-1, 100.916, 0, 1, 0.513558,-99) , 
NN(
0, 
0, 
-1, 209.925, 1, -1, 0.493658,-99) , 
1, 226.83, 0, 0, 0.497611,-99) , 
0, 175.483, 0, 0, 0.498442,-99)    );
  // itree = 82
  fBoostWeights.push_back(0.0163077);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.82191, 0, 1, 0.526914,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500706,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477504,-99) , 
2, 3.46295, 1, 0, 0.497228,-99) , 
0, 144.309, 0, 0, 0.501869,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507383,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486921,-99) , 
2, 2.85651, 1, 0, 0.497614,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489383,-99) , 
3, 122.21, 1, 0, 0.493489,-99) , 
1, 226.83, 1, 0, 0.500093,-99)    );
  // itree = 83
  fBoostWeights.push_back(0.0166803);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512699,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497233,-99) , 
1, 201.057, 0, 0, 0.502208,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502885,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469638,-99) , 
0, 62.6164, 0, 0, 0.500378,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508793,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.436804,-99) , 
0, 212.059, 1, 0, 0.479654,-99) , 
0, 151.646, 1, 0, 0.497286,-99) , 
3, 218.382, 0, 0, 0.498106,-99)    );
  // itree = 84
  fBoostWeights.push_back(0.0130819);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508876,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497594,-99) , 
2, 2.98741, 1, 0, 0.503696,-99) , 
NN(
NN(
0, 
0, 
-1, 62.6164, 0, -1, 0.496837,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504624,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.440912,-99) , 
0, 212.059, 1, 0, 0.478849,-99) , 
0, 151.646, 1, 0, 0.494154,-99) , 
3, 218.382, 0, 0, 0.495744,-99)    );
  // itree = 85
  fBoostWeights.push_back(0.0123486);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508866,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499095,-99) , 
3, 284.788, 0, 0, 0.503429,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501985,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477057,-99) , 
0, 62.6164, 0, 0, 0.500107,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501354,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.444139,-99) , 
0, 212.059, 1, 0, 0.478217,-99) , 
0, 151.646, 1, 0, 0.496843,-99) , 
3, 218.382, 0, 0, 0.49794,-99)    );
  // itree = 86
  fBoostWeights.push_back(0.0112398);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 201.057, 0, 1, 0.503777,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50037,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484999,-99) , 
0, 126.208, 1, 0, 0.497485,-99) , 
NN(
0, 
0, 
-1, 212.059, 1, -1, 0.47762,-99) , 
0, 151.646, 1, 0, 0.494523,-99) , 
3, 218.382, 0, 0, 0.496066,-99)    );
  // itree = 87
  fBoostWeights.push_back(0.0219057);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503061,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513755,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496046,-99) , 
0, 100.916, 0, 0, 0.506973,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510382,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487382,-99) , 
0, 78.0506, 1, 0, 0.490461,-99) , 
1, 226.83, 0, 0, 0.49374,-99) , 
0, 175.483, 0, 0, 0.494701,-99)    );
  // itree = 88
  fBoostWeights.push_back(0.0173251);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.82191, 0, 1, 0.522145,-99) , 
NN(
0, 
0, 
-1, 3.46295, 1, -1, 0.494288,-99) , 
0, 144.309, 0, 0, 0.498639,-99) , 
NN(
0, 
0, 
-1, 3.24453, 0, -1, 0.489915,-99) , 
1, 226.83, 1, 0, 0.49679,-99)    );
  // itree = 89
  fBoostWeights.push_back(0.0117999);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 144.309, 0, 1, 0.503968,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476909,-99) , 
1, 209.925, 1, 0, 0.501618,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502251,-99) , 
NN(
0, 
0, 
-1, 163.15, 1, -1, 0.4915,-99) , 
2, 3.24453, 0, 0, 0.494245,-99) , 
1, 226.83, 1, 0, 0.500055,-99)    );
  // itree = 90
  fBoostWeights.push_back(0.0141661);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 201.057, 0, 1, 0.504688,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50302,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477989,-99) , 
0, 62.6164, 0, 0, 0.501133,-99) , 
NN(
0, 
0, 
-1, 212.059, 1, -1, 0.474686,-99) , 
0, 151.646, 1, 0, 0.497192,-99) , 
3, 218.382, 0, 0, 0.49844,-99)    );
  // itree = 91
  fBoostWeights.push_back(0.0141656);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506473,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498619,-99) , 
1, 201.057, 0, 0, 0.501146,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505419,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494621,-99) , 
3, 135.432, 0, 0, 0.498125,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500338,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.445612,-99) , 
0, 212.059, 1, 0, 0.47822,-99) , 
0, 151.646, 1, 0, 0.49516,-99) , 
3, 218.382, 0, 0, 0.496157,-99)    );
  // itree = 92
  fBoostWeights.push_back(0.0128661);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504485,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499962,-99) , 
2, 2.98741, 1, 0, 0.502408,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503256,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493446,-99) , 
0, 100.772, 0, 0, 0.499368,-99) , 
NN(
0, 
0, 
-1, 212.059, 1, -1, 0.477534,-99) , 
0, 151.646, 1, 0, 0.496115,-99) , 
3, 218.382, 0, 0, 0.497163,-99)    );
  // itree = 93
  fBoostWeights.push_back(0.0111891);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504733,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496894,-99) , 
2, 2.69055, 0, 0, 0.502146,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501373,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487135,-99) , 
0, 126.208, 1, 0, 0.498701,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500013,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.452299,-99) , 
0, 212.059, 1, 0, 0.480745,-99) , 
0, 151.646, 1, 0, 0.496027,-99) , 
3, 218.382, 0, 0, 0.497046,-99)    );
  // itree = 94
  fBoostWeights.push_back(0.00971645);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502973,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49978,-99) , 
3, 284.788, 0, 0, 0.501195,-99) , 
NN(
0, 
0, 
-1, 151.646, 1, -1, 0.494459,-99) , 
3, 218.382, 0, 0, 0.495581,-99)    );
  // itree = 95
  fBoostWeights.push_back(0.0128659);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502844,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513894,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498134,-99) , 
0, 123.283, 1, 0, 0.509269,-99) , 
NN(
0, 
0, 
-1, 209.925, 1, -1, 0.494028,-99) , 
1, 226.83, 0, 0, 0.497055,-99) , 
0, 175.483, 0, 0, 0.497651,-99)    );
  // itree = 96
  fBoostWeights.push_back(0.0186528);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.82191, 0, 1, 0.520112,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508913,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493682,-99) , 
0, 90.2193, 1, 0, 0.497478,-99) , 
0, 144.309, 0, 0, 0.50101,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507408,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490487,-99) , 
2, 2.85651, 1, 0, 0.499336,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487473,-99) , 
3, 122.21, 1, 0, 0.493391,-99) , 
1, 226.83, 1, 0, 0.499396,-99)    );
  // itree = 97
  fBoostWeights.push_back(0.0128442);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 144.309, 0, 1, 0.504183,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481988,-99) , 
1, 209.925, 1, 0, 0.502257,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5032,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504387,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470645,-99) , 
1, 307.079, 1, 0, 0.492579,-99) , 
0, 97.5531, 1, 0, 0.49562,-99) , 
1, 226.83, 1, 0, 0.50085,-99)    );
  // itree = 98
  fBoostWeights.push_back(0.0150917);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532282,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497141,-99) , 
2, 2.82191, 0, 0, 0.512912,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503771,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491356,-99) , 
3, 116.477, 1, 0, 0.497143,-99) , 
0, 144.309, 0, 0, 0.499603,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500584,-99) , 
NN(
0, 
0, 
-1, 163.15, 1, -1, 0.491759,-99) , 
2, 3.24453, 0, 0, 0.494012,-99) , 
1, 226.83, 1, 0, 0.498418,-99)    );
  // itree = 99
  fBoostWeights.push_back(0.0130605);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 2.98741, 1, 1, 0.505964,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502722,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481669,-99) , 
0, 62.6164, 0, 0, 0.501135,-99) , 
NN(
0, 
0, 
-1, 212.059, 1, -1, 0.477664,-99) , 
0, 151.646, 1, 0, 0.497642,-99) , 
3, 218.382, 0, 0, 0.499027,-99)    );
   return;
};
 
// Clean up
inline void ReadBDT::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDT::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
