// Class: ReadBDT
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.06/01       [394753]
Creator        : kskovpen
Date           : Wed Jan 11 10:51:32 2017
Host           : Linux vocms0315.cern.ch 2.6.32-573.26.1.el6.x86_64 #1 SMP Wed May 4 09:23:05 CEST 2016 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /storage_mnt/storage/user/kskovpen/analysis/tHFCNC/CMSSW_8_0_12/src/TopKinFit/test/Validation/TopTopLepHad/MVA
Training events: 68293
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "100" [Number of trees in the forest]
MaxDepth: "3" [Max depth of the decision tree allowed]
nCuts: "20" [Number of grid points in variable range used in finding optimal cut in node splitting]
SeparationType: "giniindex" [Separation criterion for node splitting]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
MinNodeSize: "5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
BoostType: "AdaBoost" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
UseBaggedBoost: "False" [Use only a random subsample of all events for growing the trees in each boost iteration.]
Shrinkage: "1.000000e+00" [Learning rate for GradBoost algorithm]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "2" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split with RandomisedTree option]
BaggedSampleFraction: "6.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "inverseboostnegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "6.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 4
TopHadRecMCSVv2L              TopHadRecMCSVv2L              TopHadRecMCSVv2L              TopHadRecMCSVv2L                                                'F'    [38.0983428955,2485.53808594]
TopLepRecMTCSVv2L             TopLepRecMTCSVv2L             TopLepRecMTCSVv2L             TopLepRecMTCSVv2L                                               'F'    [4.85756635666,1280.54577637]
TopLepTopHadRecDphiTCSVv2L    TopLepTopHadRecDphiTCSVv2L    TopLepTopHadRecDphiTCSVv2L    TopLepTopHadRecDphiTCSVv2L                                      'F'    [-3.14156866074,3.14158320427]
TopLepRecPtTCSVv2L            TopLepRecPtTCSVv2L            TopLepRecPtTCSVv2L            TopLepRecPtTCSVv2L                                              'F'    [0.497465074062,864.608032227]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDTNode
   
#ifndef BDTNode__def
#define BDTNode__def
   
class BDTNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDTNode ( BDTNode* left,BDTNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTNode();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTNode* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTNode*   fLeft;     // pointer to the left daughter node
   BDTNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDTNode::~BDTNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDTNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDTNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT : public IClassifierReader {

 public:

   // constructor
   ReadBDT( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDT" ),
        fNvars( 4 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "TopHadRecMCSVv2L", "TopLepRecMTCSVv2L", "TopLepTopHadRecDphiTCSVv2L", "TopLepRecPtTCSVv2L" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[4];
   double fVmax[4];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[4];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTNode*)current->GetRight();
         else current=(BDTNode*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
};

void ReadBDT::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(0.414347529005595);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 133.234, 0, 1, 0.686338,-99) , 
NN(
0, 
0, 
-1, 144.445, 0, -1, 0.353035,-99) , 
0, 204.586, 1, 0, 0.605814,-99) , 
NN(
0, 
0, 
-1, 200.869, 1, -1, 0.260308,-99) , 
0, 271.188, 1, 0, 0.5,-99)    );
  // itree = 1
  fBoostWeights.push_back(0.276634);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 158.385, 0, 1, 0.605164,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540904,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.346105,-99) , 
3, 205.38, 0, 0, 0.404164,-99) , 
0, 271.188, 1, 0, 0.549143,-99) , 
NN(
0, 
0, 
-1, 239.173, 1, -1, 0.253044,-99) , 
1, 187.099, 1, 0, 0.494196,-99)    );
  // itree = 2
  fBoostWeights.push_back(0.199341);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.650663,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478246,-99) , 
0, 268.083, 1, 0, 0.592279,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545098,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.43286,-99) , 
2, 2.54319, 0, 0, 0.460039,-99) , 
3, 164.404, 0, 0, 0.507538,-99) , 
NN(
0, 
0, 
-1, 239.173, 1, -1, 0.308784,-99) , 
1, 187.099, 1, 0, 0.471835,-99)    );
  // itree = 3
  fBoostWeights.push_back(0.163532);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 157.643, 0, 1, 0.632625,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.59058,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.453729,-99) , 
2, 2.85663, 0, 0, 0.481323,-99) , 
2, -2.84237, 1, 0, 0.507148,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.249227,-99) , 
1, 247.846, 1, 0, 0.489291,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.095619);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.624201,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499194,-99) , 
0, 255.893, 1, 0, 0.58757,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506359,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.367915,-99) , 
1, 201.556, 1, 0, 0.495902,-99) , 
2, -2.54317, 1, 0, 0.520602,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.28106,-99) , 
1, 247.846, 1, 0, 0.504483,-99)    );
  // itree = 5
  fBoostWeights.push_back(0.11499);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 120.086, 0, 1, 0.578341,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511428,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.440219,-99) , 
2, 2.0588, 0, 0, 0.475587,-99) , 
2, -2.54317, 1, 0, 0.503135,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.30078,-99) , 
1, 247.846, 1, 0, 0.489742,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.107583);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 120.086, 0, 1, 0.552188,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517596,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454445,-99) , 
3, 164.404, 0, 0, 0.474944,-99) , 
2, -1.94478, 1, 0, 0.503631,-99) , 
NN(
0, 
0, 
-1, 254.7, 1, -1, 0.391954,-99) , 
1, 187.099, 1, 0, 0.484482,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.178296);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.594904,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.364268,-99) , 
0, 134.29, 0, 0, 0.55342,-99) , 
NN(
0, 
0, 
-1, 144.445, 0, -1, 0.416465,-99) , 
0, 193.487, 1, 0, 0.508956,-99) , 
NN(
0, 
0, 
-1, 200.869, 1, -1, 0.430583,-99) , 
0, 271.188, 1, 0, 0.485648,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.0645243);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -2.54317, 1, 1, 0.527961,-99) , 
NN(
0, 
0, 
-1, 143.089, 0, -1, 0.477721,-99) , 
3, 123.427, 0, 0, 0.50425,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.365688,-99) , 
1, 247.846, 1, 0, 0.495433,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.074173);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526622,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467139,-99) , 
1, 166.844, 1, 0, 0.514057,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503946,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.391303,-99) , 
0, 132.441, 0, 0, 0.458404,-99) , 
0, 154.643, 0, 0, 0.503351,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.38078,-99) , 
1, 247.846, 1, 0, 0.495603,-99)    );
  // itree = 10
  fBoostWeights.push_back(0.0624133);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530067,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459375,-99) , 
1, 86.7966, 0, 0, 0.519293,-99) , 
NN(
0, 
0, 
-1, 154.643, 0, -1, 0.477061,-99) , 
2, -1.64558, 1, 0, 0.49401,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.398417,-99) , 
1, 247.846, 1, 0, 0.488004,-99)    );
  // itree = 11
  fBoostWeights.push_back(0.103233);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.555431,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.43129,-99) , 
0, 141.687, 0, 0, 0.524957,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536903,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460521,-99) , 
3, 247.417, 0, 0, 0.472993,-99) , 
0, 193.481, 1, 0, 0.499473,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.417649,-99) , 
0, 504.277, 1, 0, 0.493645,-99)    );
  // itree = 12
  fBoostWeights.push_back(0.0511752);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516544,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46127,-99) , 
0, 487.631, 1, 0, 0.511381,-99) , 
NN(
0, 
0, 
-1, 122.612, 0, -1, 0.464238,-99) , 
0, 154.643, 0, 0, 0.502335,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.419469,-99) , 
1, 247.846, 1, 0, 0.497163,-99)    );
  // itree = 13
  fBoostWeights.push_back(0.0408192);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508646,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.455444,-99) , 
1, 204.862, 1, 0, 0.504179,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506284,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.438172,-99) , 
3, 178.13, 0, 0, 0.467737,-99) , 
1, 97.4213, 0, 0, 0.49638,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.43198,-99) , 
1, 247.846, 1, 0, 0.492372,-99)    );
  // itree = 14
  fBoostWeights.push_back(0.0259891);
  fForest.push_back( 
NN(
0, 
0, 
-1, 247.846, 1, -1, 0.487008,-99)    );
  // itree = 15
  fBoostWeights.push_back(0.0264863);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505237,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484825,-99) , 
1, 165.196, 1, 0, 0.500271,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4595,-99) , 
1, 74.2804, 0, 0, 0.496484,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.448442,-99) , 
1, 247.846, 1, 0, 0.493503,-99)    );
  // itree = 16
  fBoostWeights.push_back(0.0660134);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 194.49, 0, 1, 0.538032,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522979,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454918,-99) , 
2, 2.60019, 0, 0, 0.485229,-99) , 
2, -2.54317, 1, 0, 0.50212,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508851,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458382,-99) , 
1, 124.918, 0, 0, 0.488132,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.425161,-99) , 
1, 196.863, 1, 0, 0.479669,-99) , 
3, 123.942, 0, 0, 0.491595,-99)    );
  // itree = 17
  fBoostWeights.push_back(0.0460298);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512488,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.447837,-99) , 
0, 131.117, 0, 0, 0.504152,-99) , 
NN(
0, 
0, 
-1, 2.84228, 1, -1, 0.473065,-99) , 
0, 215.679, 1, 0, 0.491922,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454451,-99) , 
0, 504.277, 1, 0, 0.489261,-99)    );
  // itree = 18
  fBoostWeights.push_back(0.0368282);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -2.9706, 1, 1, 0.518007,-99) , 
NN(
0, 
0, 
-1, 1.20403, 0, -1, 0.485821,-99) , 
2, -1.94477, 1, 0, 0.499059,-99) , 
NN(
0, 
0, 
-1, 2.84219, 1, -1, 0.47859,-99) , 
3, 123.942, 0, 0, 0.489461,-99)    );
  // itree = 19
  fBoostWeights.push_back(0.017294);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527541,-99) , 
NN(
0, 
0, 
-1, 247.846, 1, -1, 0.492553,-99) , 
3, 329.682, 0, 0, 0.494641,-99)    );
  // itree = 20
  fBoostWeights.push_back(0.019471);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517003,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498329,-99) , 
0, 278.224, 0, 0, 0.503499,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464168,-99) , 
1, 239.168, 1, 0, 0.500529,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465795,-99) , 
1, 65.6046, 0, 0, 0.498448,-99)    );
  // itree = 21
  fBoostWeights.push_back(0.0429959);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.533656,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489043,-99) , 
0, 180.8, 1, 0, 0.506165,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46216,-99) , 
0, 126.889, 0, 0, 0.503334,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47004,-99) , 
0, 504.277, 1, 0, 0.500974,-99)    );
  // itree = 22
  fBoostWeights.push_back(0.0333793);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515434,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486447,-99) , 
1, 74.2804, 0, 0, 0.512729,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.455918,-99) , 
1, 247.846, 1, 0, 0.509192,-99) , 
NN(
0, 
0, 
-1, -1.04711, 1, -1, 0.484884,-99) , 
0, 154.643, 0, 0, 0.504554,-99)    );
  // itree = 23
  fBoostWeights.push_back(0.0219287);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 187.099, 0, 1, 0.509048,-99) , 
NN(
0, 
0, 
-1, 168.566, 1, -1, 0.487632,-99) , 
3, 82.8325, 0, 0, 0.5034,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475407,-99) , 
0, 504.277, 1, 0, 0.501417,-99)    );
  // itree = 24
  fBoostWeights.push_back(0.0238965);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524359,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512753,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4673,-99) , 
0, 394.398, 1, 0, 0.505883,-99) , 
NN(
0, 
0, 
-1, 2.84239, 1, -1, 0.492104,-99) , 
3, 141.576, 0, 0, 0.497814,-99) , 
3, 329.682, 0, 0, 0.499398,-99)    );
  // itree = 25
  fBoostWeights.push_back(0.0147462);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516766,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499291,-99) , 
0, 278.224, 0, 0, 0.504134,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478688,-99) , 
1, 239.168, 1, 0, 0.502219,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476911,-99) , 
1, 65.6046, 0, 0, 0.500707,-99)    );
  // itree = 26
  fBoostWeights.push_back(0.0189213);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509401,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495535,-99) , 
2, -2.54317, 0, 0, 0.505778,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482369,-99) , 
1, 239.168, 1, 0, 0.504017,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480591,-99) , 
1, 65.6046, 0, 0, 0.502617,-99)    );
  // itree = 27
  fBoostWeights.push_back(0.0307924);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542109,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525182,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49196,-99) , 
0, 262.229, 0, 0, 0.501992,-99) , 
1, 188.326, 0, 0, 0.50881,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506209,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474281,-99) , 
0, 154.643, 0, 0, 0.500278,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457779,-99) , 
1, 209.168, 1, 0, 0.495658,-99) , 
2, -1.34638, 1, 0, 0.501271,-99)    );
  // itree = 28
  fBoostWeights.push_back(0.0317377);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534456,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510977,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482944,-99) , 
1, 92.9691, 0, 0, 0.505043,-99) , 
1, 188.326, 0, 0, 0.510038,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507296,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480225,-99) , 
0, 271.188, 1, 0, 0.499495,-99) , 
NN(
0, 
0, 
-1, 105.256, 1, -1, 0.468731,-99) , 
2, 1.21853, 0, 0, 0.49218,-99) , 
2, -1.34638, 1, 0, 0.499801,-99)    );
  // itree = 29
  fBoostWeights.push_back(0.0258612);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526551,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516584,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495301,-99) , 
2, -2.97064, 1, 0, 0.500468,-99) , 
1, 188.326, 0, 0, 0.504896,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508742,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487181,-99) , 
2, 2.50056, 1, 0, 0.497892,-99) , 
NN(
0, 
0, 
-1, 2.07322, 0, -1, 0.477152,-99) , 
1, 158.09, 1, 0, 0.4915,-99) , 
2, -1.34638, 1, 0, 0.497217,-99)    );
  // itree = 30
  fBoostWeights.push_back(0.026156);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525926,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493616,-99) , 
0, 184.955, 1, 0, 0.51001,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487195,-99) , 
0, 370.405, 1, 0, 0.506561,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513801,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496136,-99) , 
3, 247.386, 0, 0, 0.498822,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50571,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.430694,-99) , 
3, 104.203, 1, 0, 0.471478,-99) , 
2, 0.791182, 0, 0, 0.493519,-99) , 
2, -1.34638, 1, 0, 0.499085,-99)    );
  // itree = 31
  fBoostWeights.push_back(0.0280922);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538244,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49493,-99) , 
2, -2.79987, 1, 0, 0.51845,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522665,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48351,-99) , 
2, -2.54332, 0, 0, 0.500969,-99) , 
3, 165.878, 0, 0, 0.507471,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511606,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49931,-99) , 
2, 2.35813, 1, 0, 0.503373,-99) , 
NN(
0, 
0, 
-1, 104.203, 1, -1, 0.47088,-99) , 
2, 0.791182, 0, 0, 0.497075,-99) , 
2, -1.34638, 1, 0, 0.501512,-99)    );
  // itree = 32
  fBoostWeights.push_back(0.0238949);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540827,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498564,-99) , 
0, 152.257, 0, 0, 0.517489,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531956,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494683,-99) , 
3, 288.563, 0, 0, 0.498312,-99) , 
0, 171.284, 1, 0, 0.504885,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485323,-99) , 
0, 504.277, 1, 0, 0.503502,-99)    );
  // itree = 33
  fBoostWeights.push_back(0.0234773);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.5432, 0, 1, 0.518121,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515278,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49539,-99) , 
0, 266.417, 0, 0, 0.503123,-99) , 
0, 171.284, 1, 0, 0.508263,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491293,-99) , 
0, 504.277, 1, 0, 0.507063,-99)    );
  // itree = 34
  fBoostWeights.push_back(0.0415996);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526514,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474593,-99) , 
0, 215.669, 1, 0, 0.516919,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535598,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454933,-99) , 
2, 2.71421, 1, 0, 0.495496,-99) , 
0, 271.188, 1, 0, 0.510835,-99) , 
NN(
NN(
0, 
0, 
-1, -3.04391, 1, 1, 0.509893,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513425,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462295,-99) , 
0, 237.39, 0, 0, 0.48447,-99) , 
2, -1.08998, 1, 0, 0.50339,-99) , 
2, 1.64559, 0, 0, 0.506408,-99)    );
  // itree = 35
  fBoostWeights.push_back(0.0272512);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529885,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491714,-99) , 
2, 2.78543, 0, 0, 0.510375,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525237,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465266,-99) , 
2, 2.71421, 1, 0, 0.495429,-99) , 
0, 271.188, 1, 0, 0.506132,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515639,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496848,-99) , 
2, -3.04391, 1, 0, 0.499495,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502097,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461946,-99) , 
1, 148.752, 1, 0, 0.485833,-99) , 
2, -1.08998, 1, 0, 0.496002,-99) , 
2, 1.64559, 0, 0, 0.500107,-99)    );
  // itree = 36
  fBoostWeights.push_back(0.0193139);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508726,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493234,-99) , 
0, 376.634, 1, 0, 0.50579,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483111,-99) , 
3, 41.6456, 0, 0, 0.50411,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509899,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486347,-99) , 
1, 157.192, 0, 0, 0.493685,-99) , 
0, 154.643, 0, 0, 0.502116,-99)    );
  // itree = 37
  fBoostWeights.push_back(0.0254095);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508579,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492871,-99) , 
1, 107.013, 0, 0, 0.504709,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503265,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464072,-99) , 
3, 306.194, 0, 0, 0.484308,-99) , 
3, 247.386, 1, 0, 0.50201,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521985,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466076,-99) , 
3, 166.222, 0, 0, 0.492864,-99) , 
2, -2.84237, 0, 0, 0.500508,-99)    );
  // itree = 38
  fBoostWeights.push_back(0.0290564);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52317,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480973,-99) , 
2, 2.71425, 0, 0, 0.50675,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515184,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.452514,-99) , 
2, 2.8565, 1, 0, 0.495838,-99) , 
3, 124.641, 0, 0, 0.501967,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50453,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494749,-99) , 
2, -2.84859, 0, 0, 0.500959,-99) , 
NN(
0, 
0, 
-1, 237.39, 0, -1, 0.480088,-99) , 
2, -1.08998, 1, 0, 0.49562,-99) , 
2, 1.64559, 0, 0, 0.498192,-99)    );
  // itree = 39
  fBoostWeights.push_back(0.0369797);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.24394, 1, 1, 0.52562,-99) , 
NN(
0, 
0, 
-1, 193.957, 1, -1, 0.460466,-99) , 
1, 152.395, 1, 0, 0.501532,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.533902,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495056,-99) , 
1, 187.099, 0, 0, 0.500936,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454025,-99) , 
0, 237.883, 1, 0, 0.495888,-99) , 
0, 271.188, 0, 0, 0.497569,-99)    );
  // itree = 40
  fBoostWeights.push_back(0.0248028);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.84239, 0, 1, 0.511676,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503675,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458845,-99) , 
0, 206.973, 0, 0, 0.493866,-99) , 
0, 187.939, 1, 0, 0.503009,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50854,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474949,-99) , 
3, 165.09, 1, 0, 0.492926,-99) , 
0, 387.733, 1, 0, 0.501589,-99)    );
  // itree = 41
  fBoostWeights.push_back(0.0102261);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501741,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486564,-99) , 
3, 41.4741, 0, 0, 0.500619,-99) , 
NN(
0, 
0, 
-1, 122.612, 0, -1, 0.487964,-99) , 
0, 154.643, 0, 0, 0.498188,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484141,-99) , 
1, 247.846, 1, 0, 0.497334,-99)    );
  // itree = 42
  fBoostWeights.push_back(0.0268788);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506206,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479565,-99) , 
2, 2.54319, 1, 0, 0.499891,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517708,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4777,-99) , 
2, 2.54317, 0, 0, 0.491312,-99) , 
3, 164.404, 1, 0, 0.496919,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486696,-99) , 
1, 247.846, 1, 0, 0.496298,-99)    );
  // itree = 43
  fBoostWeights.push_back(0.0232302);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523736,-99) , 
NN(
0, 
0, 
-1, 87.9665, 0, -1, 0.481348,-99) , 
3, 166.222, 0, 0, 0.499968,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501495,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48425,-99) , 
1, 158.09, 1, 0, 0.496003,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476804,-99) , 
3, 247.386, 1, 0, 0.493519,-99) , 
2, -2.54317, 1, 0, 0.495234,-99)    );
  // itree = 44
  fBoostWeights.push_back(0.023582);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517939,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503268,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.455334,-99) , 
3, 87.9665, 0, 0, 0.48715,-99) , 
3, 166.222, 0, 0, 0.500674,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50254,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484964,-99) , 
0, 271.188, 1, 0, 0.4975,-99) , 
NN(
0, 
0, 
-1, 158.35, 1, -1, 0.485057,-99) , 
2, 1.24667, 0, 0, 0.492433,-99) , 
2, -2.54317, 1, 0, 0.494624,-99)    );
  // itree = 45
  fBoostWeights.push_back(0.034637);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.541519,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519934,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454348,-99) , 
2, -2.37222, 1, 0, 0.48394,-99) , 
2, 2.2439, 0, 0, 0.501845,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514731,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469155,-99) , 
2, 2.54313, 1, 0, 0.503387,-99) , 
NN(
0, 
0, 
-1, 237.883, 1, -1, 0.488574,-99) , 
0, 271.188, 0, 0, 0.492816,-99) , 
1, 187.099, 0, 0, 0.494314,-99)    );
  // itree = 46
  fBoostWeights.push_back(0.0234791);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.84239, 0, 1, 0.505655,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458735,-99) , 
0, 237.883, 1, 0, 0.500607,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514597,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497007,-99) , 
2, -0.149621, 1, 0, 0.50576,-99) , 
NN(
0, 
0, 
-1, -0.748024, 0, -1, 0.468814,-99) , 
1, 152.395, 1, 0, 0.492107,-99) , 
0, 271.188, 1, 0, 0.498078,-99)    );
  // itree = 47
  fBoostWeights.push_back(0.0183676);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506621,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529734,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492586,-99) , 
1, 187.099, 0, 0, 0.498818,-99) , 
NN(
0, 
0, 
-1, 195.458, 1, -1, 0.491936,-99) , 
3, 141.576, 0, 0, 0.494786,-99) , 
3, 329.682, 0, 0, 0.495492,-99)    );
  // itree = 48
  fBoostWeights.push_back(0.0187978);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517354,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493333,-99) , 
2, 2.7142, 0, 0, 0.507419,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504117,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471907,-99) , 
0, 240.108, 1, 0, 0.494465,-99) , 
3, 124.003, 0, 0, 0.501666,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518961,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496427,-99) , 
3, 47.5193, 1, 0, 0.499322,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482036,-99) , 
3, 247.386, 1, 0, 0.496893,-99) , 
2, 1.3464, 0, 0, 0.498936,-99)    );
  // itree = 49
  fBoostWeights.push_back(0.0179753);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528797,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499587,-99) , 
3, 198.555, 0, 0, 0.506618,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484832,-99) , 
0, 370.405, 1, 0, 0.503323,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505334,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482435,-99) , 
0, 154.643, 0, 0, 0.501075,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475818,-99) , 
1, 209.168, 1, 0, 0.498359,-99) , 
2, -1.34638, 1, 0, 0.500479,-99)    );
  // itree = 50
  fBoostWeights.push_back(0.0178798);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518502,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499085,-99) , 
0, 184.955, 1, 0, 0.50895,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489323,-99) , 
0, 370.405, 1, 0, 0.505981,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503754,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48708,-99) , 
3, 164.404, 1, 0, 0.498253,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480303,-99) , 
1, 209.168, 1, 0, 0.496323,-99) , 
2, -1.34638, 1, 0, 0.500448,-99)    );
  // itree = 51
  fBoostWeights.push_back(0.0200588);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -2.97064, 1, 1, 0.508879,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493791,-99) , 
0, 370.405, 1, 0, 0.506597,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505605,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4885,-99) , 
3, 123.942, 0, 0, 0.497774,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508204,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458875,-99) , 
3, 104.203, 1, 0, 0.485742,-99) , 
2, 0.791182, 0, 0, 0.495446,-99) , 
2, -1.34638, 1, 0, 0.500208,-99)    );
  // itree = 52
  fBoostWeights.push_back(0.0137517);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 188.326, 0, 1, 0.505898,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493821,-99) , 
3, 83.6745, 0, 0, 0.5031,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507755,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495488,-99) , 
3, 247.386, 0, 0, 0.49735,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50319,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46386,-99) , 
3, 104.203, 1, 0, 0.485287,-99) , 
2, 0.791182, 0, 0, 0.495016,-99) , 
2, -1.34638, 1, 0, 0.498469,-99)    );
  // itree = 53
  fBoostWeights.push_back(0.0187009);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516594,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497534,-99) , 
0, 162.049, 1, 0, 0.502504,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513725,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482936,-99) , 
0, 271.188, 0, 0, 0.491381,-99) , 
1, 107.013, 0, 0, 0.499733,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506944,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480784,-99) , 
2, 1.04711, 0, 0, 0.49308,-99) , 
3, 247.386, 1, 0, 0.498753,-99)    );
  // itree = 54
  fBoostWeights.push_back(0.0205117);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509547,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494672,-99) , 
3, 165.09, 1, 0, 0.504672,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517129,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477756,-99) , 
3, 165.878, 0, 0, 0.49545,-99) , 
2, 2.54317, 1, 0, 0.502226,-99) , 
NN(
0, 
0, 
-1, 126.892, 0, -1, 0.494117,-99) , 
0, 154.643, 0, 0, 0.500674,-99)    );
  // itree = 55
  fBoostWeights.push_back(0.0228653);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -2.79987, 1, 1, 0.513266,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507934,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490599,-99) , 
2, -2.54332, 0, 0, 0.498336,-99) , 
3, 165.878, 0, 0, 0.503881,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505493,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484506,-99) , 
2, 2.92791, 1, 0, 0.501643,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514804,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451417,-99) , 
2, 2.71426, 0, 0, 0.486297,-99) , 
3, 206.238, 1, 0, 0.498358,-99) , 
2, -1.34638, 1, 0, 0.500718,-99)    );
  // itree = 56
  fBoostWeights.push_back(0.0149946);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511817,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507933,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494924,-99) , 
0, 262.229, 0, 0, 0.499099,-99) , 
2, -2.97064, 1, 0, 0.502144,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512236,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496206,-99) , 
2, 3.02966, 0, 0, 0.498616,-99) , 
NN(
0, 
0, 
-1, 104.203, 1, -1, 0.481936,-99) , 
2, 0.791182, 0, 0, 0.495389,-99) , 
2, -1.34638, 1, 0, 0.498275,-99)    );
  // itree = 57
  fBoostWeights.push_back(0.0127314);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51604,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499563,-99) , 
0, 162.049, 1, 0, 0.503861,-99) , 
NN(
0, 
0, 
-1, 94.8878, 0, -1, 0.492913,-99) , 
1, 107.013, 0, 0, 0.501135,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5076,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482233,-99) , 
2, -1.94479, 1, 0, 0.493123,-99) , 
3, 247.386, 1, 0, 0.499954,-99)    );
  // itree = 58
  fBoostWeights.push_back(0.016399);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 161.716, 1, 1, 0.509396,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503771,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473173,-99) , 
1, 195.458, 1, 0, 0.499608,-99) , 
3, 141.564, 0, 0, 0.503071,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504407,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483952,-99) , 
2, 1.04711, 0, 0, 0.493572,-99) , 
3, 247.386, 1, 0, 0.501671,-99)    );
  // itree = 59
  fBoostWeights.push_back(0.0188983);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53916,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516308,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472422,-99) , 
2, -2.37222, 1, 0, 0.492241,-99) , 
2, 2.2439, 0, 0, 0.506828,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505904,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49578,-99) , 
0, 271.188, 0, 0, 0.498684,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483089,-99) , 
1, 169.738, 1, 0, 0.497239,-99) , 
1, 187.099, 0, 0, 0.498826,-99)    );
  // itree = 60
  fBoostWeights.push_back(0.0228056);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 209.327, 0, 1, 0.505867,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4747,-99) , 
0, 237.883, 1, 0, 0.50252,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514655,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48053,-99) , 
2, -2.60017, 0, 0, 0.504127,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469838,-99) , 
2, 2.54313, 1, 0, 0.495819,-99) , 
0, 271.188, 1, 0, 0.500526,-99)    );
  // itree = 61
  fBoostWeights.push_back(0.0155973);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532363,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507972,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469354,-99) , 
3, 124.198, 0, 0, 0.489378,-99) , 
2, 2.2439, 0, 0, 0.502723,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500989,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493541,-99) , 
2, 1.94478, 1, 0, 0.498183,-99) , 
NN(
0, 
0, 
-1, -0.448729, 1, -1, 0.48804,-99) , 
0, 154.643, 0, 0, 0.496224,-99) , 
1, 187.099, 0, 0, 0.497299,-99)    );
  // itree = 62
  fBoostWeights.push_back(0.0219521);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522963,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495134,-99) , 
0, 271.188, 0, 0, 0.503574,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511296,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485954,-99) , 
2, 3.03305, 0, 0, 0.496698,-99) , 
2, 2.85666, 1, 0, 0.500867,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509934,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481834,-99) , 
0, 255.893, 1, 0, 0.501293,-99) , 
NN(
0, 
0, 
-1, 197.814, 1, -1, 0.49034,-99) , 
2, -2.68566, 1, 0, 0.494475,-99) , 
2, 1.64559, 0, 0, 0.497063,-99)    );
  // itree = 63
  fBoostWeights.push_back(0.0175575);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.97063, 0, 1, 0.505886,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518876,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476173,-99) , 
2, 2.5432, 1, 0, 0.493719,-99) , 
0, 271.188, 1, 0, 0.502408,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508417,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497055,-99) , 
2, -2.24627, 0, 0, 0.499559,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509568,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479079,-99) , 
3, 70.3364, 1, 0, 0.489674,-99) , 
2, -1.43205, 1, 0, 0.496948,-99) , 
2, 1.3464, 0, 0, 0.499284,-99)    );
  // itree = 64
  fBoostWeights.push_back(0.0179365);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510824,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507206,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497298,-99) , 
3, 198.879, 0, 0, 0.499901,-99) , 
1, 188.326, 0, 0, 0.50175,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525615,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496617,-99) , 
3, 141.569, 0, 0, 0.500854,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509202,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.445447,-99) , 
2, 2.28697, 0, 0, 0.490481,-99) , 
3, 165.09, 1, 0, 0.497426,-99) , 
2, -1.34638, 1, 0, 0.499274,-99)    );
  // itree = 65
  fBoostWeights.push_back(0.0194528);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507808,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489898,-99) , 
2, 2.85663, 1, 0, 0.504922,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488995,-99) , 
2, -2.84237, 0, 0, 0.502667,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510084,-99) , 
NN(
0, 
0, 
-1, 2.05878, 0, -1, 0.484433,-99) , 
2, -2.54316, 1, 0, 0.493404,-99) , 
3, 206.238, 1, 0, 0.500571,-99)    );
  // itree = 66
  fBoostWeights.push_back(0.0123208);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504264,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493154,-99) , 
1, 107.013, 0, 0, 0.501398,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484899,-99) , 
3, 35.764, 0, 0, 0.500355,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502528,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484193,-99) , 
2, 1.04711, 0, 0, 0.492819,-99) , 
3, 247.386, 1, 0, 0.499246,-99)    );
  // itree = 67
  fBoostWeights.push_back(0.0103634);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492529,-99) , 
2, -0.149359, 1, 0, 0.507556,-99) , 
NN(
0, 
0, 
-1, 161.699, 1, -1, 0.497712,-99) , 
3, 188.586, 0, 0, 0.499153,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504967,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483986,-99) , 
2, -1.94479, 1, 0, 0.493,-99) , 
3, 247.386, 1, 0, 0.498247,-99)    );
  // itree = 68
  fBoostWeights.push_back(0.0215799);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524913,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504556,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470125,-99) , 
1, 194.299, 1, 0, 0.499777,-99) , 
3, 149.411, 0, 0, 0.502288,-99) , 
NN(
NN(
0, 
0, 
-1, 2.88522, 0, 1, 0.507385,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503987,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460216,-99) , 
2, -2.11588, 1, 0, 0.48916,-99) , 
2, 2.24397, 0, 0, 0.496246,-99) , 
3, 165.09, 1, 0, 0.50018,-99)    );
  // itree = 69
  fBoostWeights.push_back(0.0112492);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516236,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491995,-99) , 
2, -0.149359, 1, 0, 0.504358,-99) , 
NN(
0, 
0, 
-1, 161.699, 1, -1, 0.49638,-99) , 
3, 188.586, 0, 0, 0.497547,-99) , 
NN(
0, 
0, 
-1, 0.14954, 0, -1, 0.49004,-99) , 
3, 247.386, 1, 0, 0.496442,-99)    );
  // itree = 70
  fBoostWeights.push_back(0.0165863);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522336,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501974,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47831,-99) , 
1, 194.299, 1, 0, 0.498691,-99) , 
3, 149.411, 0, 0, 0.501053,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513035,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502048,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468046,-99) , 
1, 136.927, 1, 0, 0.491372,-99) , 
1, 188.912, 0, 0, 0.494868,-99) , 
3, 165.09, 1, 0, 0.498896,-99)    );
  // itree = 71
  fBoostWeights.push_back(0.0205079);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529486,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508736,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480006,-99) , 
2, -2.37222, 1, 0, 0.492985,-99) , 
2, 2.2439, 0, 0, 0.504315,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505314,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491168,-99) , 
1, 135.025, 0, 0, 0.497348,-99) , 
NN(
0, 
0, 
-1, 135.631, 1, -1, 0.489454,-99) , 
3, 164.404, 1, 0, 0.494577,-99) , 
1, 187.099, 0, 0, 0.496185,-99)    );
  // itree = 72
  fBoostWeights.push_back(0.014636);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524374,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50361,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485127,-99) , 
2, -2.37222, 1, 0, 0.493478,-99) , 
2, 2.2439, 0, 0, 0.503066,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506751,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497942,-99) , 
0, 271.188, 0, 0, 0.500508,-99) , 
NN(
0, 
0, 
-1, 172.631, 1, -1, 0.488375,-99) , 
1, 143.704, 1, 0, 0.496796,-99) , 
1, 187.099, 0, 0, 0.497831,-99)    );
  // itree = 73
  fBoostWeights.push_back(0.0270536);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516095,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520303,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490265,-99) , 
0, 204.586, 0, 0, 0.498152,-99) , 
2, 2.84239, 0, 0, 0.501315,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511635,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488122,-99) , 
2, -2.05877, 0, 0, 0.500989,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477188,-99) , 
2, 2.54313, 1, 0, 0.495226,-99) , 
0, 271.188, 1, 0, 0.499503,-99)    );
  // itree = 74
  fBoostWeights.push_back(0.0181658);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -2.84229, 1, 1, 0.505925,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476542,-99) , 
0, 237.883, 1, 0, 0.502769,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51681,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495112,-99) , 
2, -1.64559, 1, 0, 0.503771,-99) , 
NN(
0, 
0, 
-1, -0.748024, 0, -1, 0.483723,-99) , 
1, 152.395, 1, 0, 0.496378,-99) , 
0, 271.188, 1, 0, 0.500867,-99)    );
  // itree = 75
  fBoostWeights.push_back(0.0121405);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52002,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503772,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486055,-99) , 
3, 124.198, 0, 0, 0.495238,-99) , 
2, 2.2439, 0, 0, 0.502921,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504282,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496565,-99) , 
2, -1.64558, 1, 0, 0.499668,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484512,-99) , 
1, 169.738, 1, 0, 0.498265,-99) , 
1, 187.099, 0, 0, 0.499033,-99)    );
  // itree = 76
  fBoostWeights.push_back(0.0147682);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 209.168, 0, 1, 0.503701,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514414,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488871,-99) , 
0, 158.831, 1, 0, 0.495041,-99) , 
3, 88.671, 0, 0, 0.500494,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505517,-99) , 
NN(
0, 
0, 
-1, 0.149492, 0, -1, 0.485805,-99) , 
1, 128.878, 1, 0, 0.496319,-99) , 
3, 206.238, 1, 0, 0.49955,-99)    );
  // itree = 77
  fBoostWeights.push_back(0.013706);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517011,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499905,-99) , 
3, 106.3, 0, 0, 0.503016,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48277,-99) , 
2, 2.84219, 1, 0, 0.500573,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507995,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491223,-99) , 
1, 145.991, 1, 0, 0.502004,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506586,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490794,-99) , 
0, 394.398, 0, 0, 0.493478,-99) , 
2, 2.54319, 0, 0, 0.49618,-99) , 
3, 123.942, 1, 0, 0.498242,-99)    );
  // itree = 78
  fBoostWeights.push_back(0.0163641);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517625,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492541,-99) , 
0, 178.073, 1, 0, 0.50725,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504172,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485708,-99) , 
3, 88.6596, 0, 0, 0.492924,-99) , 
0, 248.08, 1, 0, 0.502904,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505342,-99) , 
NN(
0, 
0, 
-1, 162.049, 0, -1, 0.495819,-99) , 
1, 187.099, 0, 0, 0.497415,-99) , 
3, 123.942, 1, 0, 0.499991,-99)    );
  // itree = 79
  fBoostWeights.push_back(0.014611);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516727,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49011,-99) , 
2, 2.37194, 1, 0, 0.508987,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492668,-99) , 
2, -2.24404, 0, 0, 0.505024,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509051,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494296,-99) , 
2, -2.77113, 1, 0, 0.505288,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501191,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482819,-99) , 
0, 154.643, 0, 0, 0.497812,-99) , 
2, -2.54317, 1, 0, 0.500047,-99) , 
3, 82.7937, 1, 0, 0.50133,-99)    );
  // itree = 80
  fBoostWeights.push_back(0.015307);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523578,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499275,-99) , 
3, 53.6871, 1, 0, 0.507347,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494949,-99) , 
3, 35.7672, 0, 0, 0.504755,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507815,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49451,-99) , 
0, 255.893, 1, 0, 0.503499,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504213,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489558,-99) , 
2, 2.60019, 0, 0, 0.495503,-99) , 
2, -2.54317, 1, 0, 0.497893,-99) , 
3, 82.7937, 1, 0, 0.499662,-99)    );
  // itree = 81
  fBoostWeights.push_back(0.0111806);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517256,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510589,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491351,-99) , 
3, 54.2322, 1, 0, 0.503385,-99) , 
3, 71.037, 0, 0, 0.506572,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506366,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499375,-99) , 
2, -2.97059, 1, 0, 0.502155,-99) , 
NN(
0, 
0, 
-1, 154.643, 0, -1, 0.496224,-99) , 
2, -2.54317, 1, 0, 0.497998,-99) , 
3, 82.7937, 1, 0, 0.500208,-99)    );
  // itree = 82
  fBoostWeights.push_back(0.0160197);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515319,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499814,-99) , 
0, 271.188, 0, 0, 0.504699,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505163,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486112,-99) , 
3, 165.878, 0, 0, 0.495018,-99) , 
2, 2.85663, 1, 0, 0.502853,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509645,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460375,-99) , 
0, 249.651, 1, 0, 0.49452,-99) , 
2, -2.84237, 0, 0, 0.501484,-99)    );
  // itree = 83
  fBoostWeights.push_back(0.0174927);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507864,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496521,-99) , 
2, 2.85663, 1, 0, 0.505912,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502518,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481085,-99) , 
3, 306.194, 0, 0, 0.492174,-99) , 
3, 247.386, 1, 0, 0.504102,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505641,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464358,-99) , 
0, 249.651, 1, 0, 0.492972,-99) , 
2, -2.84237, 0, 0, 0.502274,-99)    );
  // itree = 84
  fBoostWeights.push_back(0.00961617);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 82.786, 1, 1, 0.503044,-99) , 
NN(
0, 
0, 
-1, 306.194, 0, -1, 0.49202,-99) , 
3, 247.386, 1, 0, 0.501591,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501268,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468711,-99) , 
0, 249.651, 1, 0, 0.49128,-99) , 
2, -2.84237, 0, 0, 0.499899,-99)    );
  // itree = 85
  fBoostWeights.push_back(0.0101505);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -1.70257, 1, 1, 0.503484,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501039,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469475,-99) , 
1, 236.276, 1, 0, 0.497138,-99) , 
1, 126.352, 1, 0, 0.499821,-99) , 
NN(
0, 
0, 
-1, 249.651, 1, -1, 0.49035,-99) , 
2, -2.84237, 0, 0, 0.498266,-99)    );
  // itree = 86
  fBoostWeights.push_back(0.0117032);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512667,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498222,-99) , 
3, 67.1181, 0, 0, 0.502501,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50117,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491259,-99) , 
1, 126.352, 1, 0, 0.495754,-99) , 
3, 82.7937, 1, 0, 0.497645,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501401,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473636,-99) , 
0, 249.651, 1, 0, 0.492887,-99) , 
2, -2.84237, 0, 0, 0.496864,-99)    );
  // itree = 87
  fBoostWeights.push_back(0.0138179);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507984,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496955,-99) , 
1, 130.64, 0, 0, 0.503693,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508442,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494155,-99) , 
2, -2.55742, 1, 0, 0.496026,-99) , 
3, 82.7937, 1, 0, 0.498175,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502632,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481751,-99) , 
3, 166.222, 0, 0, 0.491755,-99) , 
2, -2.84237, 0, 0, 0.497121,-99)    );
  // itree = 88
  fBoostWeights.push_back(0.0106522);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50221,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49375,-99) , 
2, 2.85663, 1, 0, 0.500847,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50769,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482945,-99) , 
2, 2.28675, 0, 0, 0.49572,-99) , 
3, 206.238, 1, 0, 0.499795,-99) , 
NN(
0, 
0, 
-1, 249.651, 1, -1, 0.491898,-99) , 
2, -2.84237, 0, 0, 0.498499,-99)    );
  // itree = 89
  fBoostWeights.push_back(0.014032);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510666,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483542,-99) , 
0, 276.179, 1, 0, 0.503787,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502496,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481073,-99) , 
2, 2.40895, 1, 0, 0.496092,-99) , 
2, 2.68576, 0, 0, 0.499872,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501301,-99) , 
NN(
0, 
0, 
-1, 237.307, 1, -1, 0.494467,-99) , 
2, -2.95639, 1, 0, 0.495863,-99) , 
2, 0.748002, 0, 0, 0.497722,-99)    );
  // itree = 90
  fBoostWeights.push_back(0.0109306);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515558,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496271,-99) , 
0, 255.115, 0, 0, 0.502972,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502058,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494692,-99) , 
2, 2.68027, 0, 0, 0.497501,-99) , 
2, -1.70257, 1, 0, 0.499035,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500418,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477483,-99) , 
0, 249.651, 1, 0, 0.493386,-99) , 
2, -2.84237, 0, 0, 0.498108,-99)    );
  // itree = 91
  fBoostWeights.push_back(0.0104634);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50567,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492036,-99) , 
3, 197.846, 1, 0, 0.503109,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5015,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49545,-99) , 
1, 107.013, 1, 0, 0.497121,-99) , 
2, 0.577033, 1, 0, 0.499735,-99) , 
NN(
0, 
0, 
-1, 249.651, 1, -1, 0.492329,-99) , 
2, -2.84237, 0, 0, 0.49852,-99)    );
  // itree = 92
  fBoostWeights.push_back(0.00789538);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51446,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498764,-99) , 
2, -0.748024, 0, 0, 0.507423,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500574,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482132,-99) , 
0, 294.816, 1, 0, 0.498088,-99) , 
0, 394.398, 0, 0, 0.499362,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491744,-99) , 
1, 65.6046, 0, 0, 0.498905,-99)    );
  // itree = 93
  fBoostWeights.push_back(0.0109016);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506576,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496396,-99) , 
0, 271.188, 0, 0, 0.499601,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501289,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488911,-99) , 
2, 3.03303, 0, 0, 0.494151,-99) , 
2, 2.85663, 1, 0, 0.498562,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501917,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486871,-99) , 
3, 166.222, 0, 0, 0.494081,-99) , 
2, -2.84237, 0, 0, 0.497826,-99)    );
  // itree = 94
  fBoostWeights.push_back(0.00738028);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502053,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493925,-99) , 
3, 205.38, 1, 0, 0.50061,-99) , 
NN(
0, 
0, 
-1, 124.776, 0, -1, 0.494569,-99) , 
2, 2.85663, 1, 0, 0.499458,-99) , 
NN(
0, 
0, 
-1, 249.651, 1, -1, 0.494194,-99) , 
2, -2.84237, 0, 0, 0.498594,-99)    );
  // itree = 95
  fBoostWeights.push_back(0.0103015);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518856,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502029,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485484,-99) , 
3, 124.198, 0, 0, 0.494066,-99) , 
2, 2.2439, 0, 0, 0.501755,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502316,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496266,-99) , 
1, 130.478, 0, 0, 0.498624,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488866,-99) , 
1, 169.738, 1, 0, 0.497721,-99) , 
1, 187.099, 0, 0, 0.498386,-99)    );
  // itree = 96
  fBoostWeights.push_back(0.009059);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504491,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522499,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493501,-99) , 
3, 256.54, 1, 0, 0.507032,-99) , 
NN(
0, 
0, 
-1, -2.84237, 0, -1, 0.49707,-99) , 
3, 219.954, 0, 0, 0.498517,-99) , 
3, 329.682, 0, 0, 0.498873,-99)    );
  // itree = 97
  fBoostWeights.push_back(0.00953006);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 71.0141, 1, 1, 0.504366,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501882,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476054,-99) , 
1, 236.276, 1, 0, 0.498692,-99) , 
1, 126.352, 1, 0, 0.501092,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502923,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486746,-99) , 
0, 249.651, 1, 0, 0.497966,-99) , 
2, -2.84237, 0, 0, 0.500579,-99)    );
  // itree = 98
  fBoostWeights.push_back(0.010008);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517522,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50226,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489703,-99) , 
2, -2.37222, 1, 0, 0.495378,-99) , 
2, 2.2439, 0, 0, 0.502245,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507257,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498435,-99) , 
1, 130.48, 0, 0, 0.500217,-99) , 
NN(
0, 
0, 
-1, 172.631, 1, -1, 0.493046,-99) , 
1, 143.704, 1, 0, 0.498024,-99) , 
1, 187.099, 0, 0, 0.49872,-99)    );
  // itree = 99
  fBoostWeights.push_back(0.0201693);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51492,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527295,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491195,-99) , 
3, 63.2911, 1, 0, 0.497396,-99) , 
3, 220.213, 0, 0, 0.501555,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505493,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483385,-99) , 
0, 233.964, 1, 0, 0.502466,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501261,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47532,-99) , 
2, 1.04713, 1, 0, 0.49042,-99) , 
0, 278.224, 1, 0, 0.499059,-99) , 
1, 126.352, 1, 0, 0.500123,-99)    );
   return;
};
 
// Clean up
inline void ReadBDT::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDT::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
