hadd ../Merged/Ntuples_All/Ntuples_12_5_2017/FCNC_1L3B__Run2_TopTree_Study_TTJets_powheg_isrup_El.root ../NtuplerOutput/Ntuples_El/Ntuples_11_5_2017/FCNC_1L3B__Run2_TopTree_Study_TTJets_powheg_isrup*_*.root
hadd ../Merged/Ntuples_All/Ntuples_12_5_2017/FCNC_1L3B__Run2_TopTree_Study_TTJets_powheg_isrdown_El.root ../NtuplerOutput/Ntuples_El/Ntuples_11_5_2017/FCNC_1L3B__Run2_TopTree_Study_TTJets_powheg_isrdown*_*.root
hadd ../Merged/Ntuples_All/Ntuples_12_5_2017/FCNC_1L3B__Run2_TopTree_Study_TTJets_powheg_fsrup_El.root ../NtuplerOutput/Ntuples_El/Ntuples_10_5_2017/FCNC_1L3B__Run2_TopTree_Study_TTJets_powheg_fsrup*_*.root ../NtuplerOutput/Ntuples_El/Ntuples_11_5_2017/FCNC_1L3B__Run2_TopTree_Study_TTJets_powheg_fsrup*_*.root
hadd ../Merged/Ntuples_All/Ntuples_12_5_2017/FCNC_1L3B__Run2_TopTree_Study_TTJets_powheg_fsrdown_El.root ../NtuplerOutput/Ntuples_El/Ntuples_10_5_2017/FCNC_1L3B__Run2_TopTree_Study_TTJets_powheg_fsrdown*_*.root ../NtuplerOutput/Ntuples_El/Ntuples_11_5_2017/FCNC_1L3B__Run2_TopTree_Study_TTJets_powheg_fsrdown*_*.root
hadd ../Merged/Ntuples_All/Ntuples_12_5_2017/FCNC_1L3B__Run2_TopTree_Study_TTJets_powheg_UEdown_El.root ../NtuplerOutput/Ntuples_El/Ntuples_10_5_2017/FCNC_1L3B__Run2_TopTree_Study_TTJets_powheg_UEdown*_*.root ../NtuplerOutput/Ntuples_El/Ntuples_11_5_2017/FCNC_1L3B__Run2_TopTree_Study_TTJets_powheg_UEdown*_*.root
hadd ../Merged/Ntuples_All/Ntuples_12_5_2017/FCNC_1L3B__Run2_TopTree_Study_TTJets_powheg_UEup_El.root ../NtuplerOutput/Ntuples_El/Ntuples_10_5_2017/FCNC_1L3B__Run2_TopTree_Study_TTJets_powheg_UEup*_*.root ../NtuplerOutput/Ntuples_El/Ntuples_11_5_2017/FCNC_1L3B__Run2_TopTree_Study_TTJets_powheg_UEup*_*.root
hadd ../Merged/Ntuples_All/Ntuples_12_5_2017/FCNC_1L3B__Run2_TopTree_Study_TTJets_powheg_hdampup_El.root ../NtuplerOutput/Ntuples_El/Ntuples_11_5_2017/FCNC_1L3B__Run2_TopTree_Study_TTJets_powheg_hdampup*_*.root
hadd ../Merged/Ntuples_All/Ntuples_12_5_2017/FCNC_1L3B__Run2_TopTree_Study_TTJets_powheg_hdampdown_El.root ../NtuplerOutput/Ntuples_El/Ntuples_11_5_2017/FCNC_1L3B__Run2_TopTree_Study_TTJets_powheg_hdampdown*_*.root

hadd ../Merged/Ntuples_All/Ntuples_12_5_2017/FCNC_1L3B__Run2_TopTree_Study_TTJets_powheg_isrup_Mu.root ../NtuplerOutput/Ntuples_Mu/Ntuples_11_5_2017/FCNC_1L3B__Run2_TopTree_Study_TTJets_powheg_isrup*_*.root
hadd ../Merged/Ntuples_All/Ntuples_12_5_2017/FCNC_1L3B__Run2_TopTree_Study_TTJets_powheg_isrdown_Mu.root ../NtuplerOutput/Ntuples_Mu/Ntuples_11_5_2017/FCNC_1L3B__Run2_TopTree_Study_TTJets_powheg_isrdown*_*.root
hadd ../Merged/Ntuples_All/Ntuples_12_5_2017/FCNC_1L3B__Run2_TopTree_Study_TTJets_powheg_fsrup_Mu.root ../NtuplerOutput/Ntuples_Mu/Ntuples_11_5_2017/FCNC_1L3B__Run2_TopTree_Study_TTJets_powheg_fsrup*_*.root
hadd ../Merged/Ntuples_All/Ntuples_12_5_2017/FCNC_1L3B__Run2_TopTree_Study_TTJets_powheg_fsrdown_Mu.root ../NtuplerOutput/Ntuples_Mu/Ntuples_11_5_2017/FCNC_1L3B__Run2_TopTree_Study_TTJets_powheg_fsrdown*_*.root
hadd ../Merged/Ntuples_All/Ntuples_12_5_2017/FCNC_1L3B__Run2_TopTree_Study_TTJets_powheg_UEdown_Mu.root ../NtuplerOutput/Ntuples_Mu/Ntuples_11_5_2017/FCNC_1L3B__Run2_TopTree_Study_TTJets_powheg_UEdown*_*.root
hadd ../Merged/Ntuples_All/Ntuples_12_5_2017/FCNC_1L3B__Run2_TopTree_Study_TTJets_powheg_UEup_Mu.root ../NtuplerOutput/Ntuples_Mu/Ntuples_11_5_2017/FCNC_1L3B__Run2_TopTree_Study_TTJets_powheg_UEup*_*.root
hadd ../Merged/Ntuples_All/Ntuples_12_5_2017/FCNC_1L3B__Run2_TopTree_Study_TTJets_powheg_hdampup_Mu.root ../NtuplerOutput/Ntuples_Mu/Ntuples_11_5_2017/FCNC_1L3B__Run2_TopTree_Study_TTJets_powheg_hdampup*_*.root
hadd ../Merged/Ntuples_All/Ntuples_12_5_2017/FCNC_1L3B__Run2_TopTree_Study_TTJets_powheg_hdampdown_Mu.root ../NtuplerOutput/Ntuples_Mu/Ntuples_11_5_2017/FCNC_1L3B__Run2_TopTree_Study_TTJets_powheg_hdampdown*_*.root

hadd ../Merged/Ntuples_All/Ntuples_12_5_2017/FCNC_1L3B__Run2_TopTree_Study_TTJets_powheg_isrup.root ../Merged/Ntuples_All/Ntuples_12_5_2017/FCNC_1L3B__Run2_TopTree_Study_TTJets_powheg_isrup_Mu.root ../Merged/Ntuples_All/Ntuples_12_5_2017/FCNC_1L3B__Run2_TopTree_Study_TTJets_powheg_isrup_El.root
hadd ../Merged/Ntuples_All/Ntuples_12_5_2017/FCNC_1L3B__Run2_TopTree_Study_TTJets_powheg_isrdown.root ../Merged/Ntuples_All/Ntuples_12_5_2017/FCNC_1L3B__Run2_TopTree_Study_TTJets_powheg_isrdown_Mu.root ../Merged/Ntuples_All/Ntuples_12_5_2017/FCNC_1L3B__Run2_TopTree_Study_TTJets_powheg_isrdown_El.root
hadd ../Merged/Ntuples_All/Ntuples_12_5_2017/FCNC_1L3B__Run2_TopTree_Study_TTJets_powheg_fsrup.root ../Merged/Ntuples_All/Ntuples_12_5_2017/FCNC_1L3B__Run2_TopTree_Study_TTJets_powheg_fsrup_Mu.root  ../Merged/Ntuples_All/Ntuples_12_5_2017/FCNC_1L3B__Run2_TopTree_Study_TTJets_powheg_fsrup_El.root
hadd ../Merged/Ntuples_All/Ntuples_12_5_2017/FCNC_1L3B__Run2_TopTree_Study_TTJets_powheg_fsrdown.root ../Merged/Ntuples_All/Ntuples_12_5_2017/FCNC_1L3B__Run2_TopTree_Study_TTJets_powheg_fsrdown_Mu.root  ../Merged/Ntuples_All/Ntuples_12_5_2017/FCNC_1L3B__Run2_TopTree_Study_TTJets_powheg_fsrdown_El.root
hadd ../Merged/Ntuples_All/Ntuples_12_5_2017/FCNC_1L3B__Run2_TopTree_Study_TTJets_powheg_UEdown.root ../Merged/Ntuples_All/Ntuples_12_5_2017/FCNC_1L3B__Run2_TopTree_Study_TTJets_powheg_UEdown_Mu.root  ../Merged/Ntuples_All/Ntuples_12_5_2017/FCNC_1L3B__Run2_TopTree_Study_TTJets_powheg_UEdown_El.root
hadd ../Merged/Ntuples_All/Ntuples_12_5_2017/FCNC_1L3B__Run2_TopTree_Study_TTJets_powheg_UEup.root ../Merged/Ntuples_All/Ntuples_12_5_2017/FCNC_1L3B__Run2_TopTree_Study_TTJets_powheg_UEup_Mu.root  ../Merged/Ntuples_All/Ntuples_12_5_2017/FCNC_1L3B__Run2_TopTree_Study_TTJets_powheg_UEup_El.root
hadd ../Merged/Ntuples_All/Ntuples_12_5_2017/FCNC_1L3B__Run2_TopTree_Study_TTJets_powheg_hdampup.root ../Merged/Ntuples_All/Ntuples_12_5_2017/FCNC_1L3B__Run2_TopTree_Study_TTJets_powheg_hdampup_Mu.root ../Merged/Ntuples_All/Ntuples_12_5_2017/FCNC_1L3B__Run2_TopTree_Study_TTJets_powheg_hdampup_El.root
hadd ../Merged/Ntuples_All/Ntuples_12_5_2017/FCNC_1L3B__Run2_TopTree_Study_TTJets_powheg_hdampdown.root ../Merged/Ntuples_All/Ntuples_12_5_2017/FCNC_1L3B__Run2_TopTree_Study_TTJets_powheg_hdampdown_Mu.root ../Merged/Ntuples_All/Ntuples_12_5_2017/FCNC_1L3B__Run2_TopTree_Study_TTJets_powheg_hdampdown_El.root


rm ../Merged/Ntuples_All/Ntuples_12_5_2017/FCNC_1L3B__Run2_TopTree_Study_TTJets_powheg_isrup_*.root
rm ../Merged/Ntuples_All/Ntuples_12_5_2017/FCNC_1L3B__Run2_TopTree_Study_TTJets_powheg_isrdown_*.root
rm ../Merged/Ntuples_All/Ntuples_12_5_2017/FCNC_1L3B__Run2_TopTree_Study_TTJets_powheg_fsrdown_*.root
rm ../Merged/Ntuples_All/Ntuples_12_5_2017/FCNC_1L3B__Run2_TopTree_Study_TTJets_powheg_fsrup_*.root
rm ../Merged/Ntuples_All/Ntuples_12_5_2017/FCNC_1L3B__Run2_TopTree_Study_TTJets_powheg_UEdown_*.root
rm ../Merged/Ntuples_All/Ntuples_12_5_2017/FCNC_1L3B__Run2_TopTree_Study_TTJets_powheg_UEup_*.root
rm ../Merged/Ntuples_All/Ntuples_12_5_2017/FCNC_1L3B__Run2_TopTree_Study_TTJets_powheg_hdampup_*.root
rm ../Merged/Ntuples_All/Ntuples_12_5_2017/FCNC_1L3B__Run2_TopTree_Study_TTJets_powheg_hdampdown_*.root

