// Class: ReadBDT
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.06/01       [394753]
Creator        : kskovpen
Date           : Thu Feb  2 15:52:30 2017
Host           : Linux vocms0301.cern.ch 2.6.32-642.11.1.el6.x86_64 #1 SMP Wed Nov 16 09:40:09 CET 2016 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /storage_mnt/storage/user/kskovpen/analysis/tHFCNC/CMSSW_8_0_25/src/TopKinFit/test/Validation/TopHLepbb/MVA
Training events: 1102398
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "100" [Number of trees in the forest]
MaxDepth: "3" [Max depth of the decision tree allowed]
nCuts: "20" [Number of grid points in variable range used in finding optimal cut in node splitting]
SeparationType: "giniindex" [Separation criterion for node splitting]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
MinNodeSize: "5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
BoostType: "AdaBoost" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
UseBaggedBoost: "False" [Use only a random subsample of all events for growing the trees in each boost iteration.]
Shrinkage: "1.000000e+00" [Learning rate for GradBoost algorithm]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "2" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split with RandomisedTree option]
BaggedSampleFraction: "6.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "inverseboostnegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "6.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 4
HiggsRecMAll                  HiggsRecMAll                  HiggsRecMAll                  HiggsRecMAll                                                    'F'    [16.0956401825,2519.54980469]
TopLepRecMAll                 TopLepRecMAll                 TopLepRecMAll                 TopLepRecMAll                                                   'F'    [79.899810791,2752.85620117]
HiggsTopLepRecDrAll           HiggsTopLepRecDrAll           HiggsTopLepRecDrAll           HiggsTopLepRecDrAll                                             'F'    [0.000933093833737,10.8273181915]
TopLepRecPtAll                TopLepRecPtAll                TopLepRecPtAll                TopLepRecPtAll                                                  'F'    [0.0918210744858,1047.2232666]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDTNode
   
#ifndef BDTNode__def
#define BDTNode__def
   
class BDTNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDTNode ( BDTNode* left,BDTNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTNode();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTNode* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTNode*   fLeft;     // pointer to the left daughter node
   BDTNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDTNode::~BDTNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDTNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDTNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT : public IClassifierReader {

 public:

   // constructor
   ReadBDT( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDT" ),
        fNvars( 4 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "HiggsRecMAll", "TopLepRecMAll", "HiggsTopLepRecDrAll", "TopLepRecPtAll" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[4];
   double fVmax[4];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[4];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTNode*)current->GetRight();
         else current=(BDTNode*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
};

void ReadBDT::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(0.377429693406387);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 85.1846, 0, 1, 0.693959,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532665,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.343658,-99) , 
3, 149.984, 0, 0, 0.404652,-99) , 
0, 136.255, 1, 0, 0.599063,-99) , 
NN(
0, 
0, 
-1, 134.068, 1, -1, 0.295608,-99) , 
1, 207.183, 1, 0, 0.5,-99)    );
  // itree = 1
  fBoostWeights.push_back(0.255703);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.687017,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47642,-99) , 
2, 2.57864, 0, 0, 0.629829,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502293,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.390994,-99) , 
3, 113.796, 0, 0, 0.444782,-99) , 
0, 84.2168, 0, 0, 0.572818,-99) , 
NN(
0, 
0, 
-1, 208.127, 1, -1, 0.359568,-99) , 
0, 135.308, 1, 0, 0.495218,-99)    );
  // itree = 2
  fBoostWeights.push_back(0.202137);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.580002,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.434491,-99) , 
2, 2.0631, 0, 0, 0.557438,-99) , 
NN(
0, 
0, 
-1, 134.068, 1, -1, 0.382483,-99) , 
1, 237.489, 1, 0, 0.531441,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.215677,-99) , 
1, 334.467, 1, 0, 0.506183,-99)    );
  // itree = 3
  fBoostWeights.push_back(0.183648);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.607076,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459626,-99) , 
0, 89.8935, 0, 0, 0.552554,-99) , 
NN(
0, 
0, 
-1, 189.566, 1, -1, 0.43094,-99) , 
0, 135.308, 1, 0, 0.509504,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.251825,-99) , 
1, 334.467, 1, 0, 0.489674,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.127334);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 136.756, 1, 1, 0.638651,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525625,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.44601,-99) , 
1, 189, 1, 0, 0.496936,-99) , 
3, 199.545, 0, 0, 0.518267,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.287972,-99) , 
1, 334.467, 1, 0, 0.501064,-99)    );
  // itree = 5
  fBoostWeights.push_back(0.116122);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 136.756, 1, 1, 0.608778,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.533917,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461117,-99) , 
2, 3.09419, 0, 0, 0.488002,-99) , 
3, 199.545, 0, 0, 0.505978,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.314768,-99) , 
1, 334.467, 1, 0, 0.491967,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.109014);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.537816,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.447135,-99) , 
0, 152.336, 1, 0, 0.519548,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.407568,-99) , 
0, 254.52, 1, 0, 0.508159,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.340336,-99) , 
1, 334.467, 1, 0, 0.496045,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.066485);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 136.756, 1, 1, 0.573869,-99) , 
NN(
0, 
0, 
-1, 273.855, 1, -1, 0.482956,-99) , 
3, 199.545, 0, 0, 0.496306,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.365219,-99) , 
1, 334.467, 1, 0, 0.486953,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.0728238);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.562768,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495446,-99) , 
2, 2.90833, 0, 0, 0.531269,-99) , 
NN(
0, 
0, 
-1, 120.822, 1, -1, 0.477274,-99) , 
3, 99.8186, 0, 0, 0.508055,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.380766,-99) , 
1, 334.467, 1, 0, 0.499034,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.0870637);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532696,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.42874,-99) , 
1, 265.774, 1, 0, 0.523494,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.431918,-99) , 
1, 128.389, 0, 0, 0.515246,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.398079,-99) , 
1, 334.467, 1, 0, 0.506993,-99)    );
  // itree = 10
  fBoostWeights.push_back(0.0821704);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529513,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454141,-99) , 
0, 168.015, 1, 0, 0.515576,-99) , 
NN(
0, 
0, 
-1, 109.554, 1, -1, 0.444627,-99) , 
0, 72.8626, 0, 0, 0.504299,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.418256,-99) , 
0, 254.52, 1, 0, 0.495186,-99)    );
  // itree = 11
  fBoostWeights.push_back(0.042413);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.578938,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500111,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461312,-99) , 
3, 71.3249, 0, 0, 0.489523,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.399678,-99) , 
1, 334.467, 1, 0, 0.483524,-99) , 
3, 249.409, 0, 0, 0.490517,-99)    );
  // itree = 12
  fBoostWeights.push_back(0.0476501);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.568566,-99) , 
NN(
0, 
0, 
-1, 334.467, 1, -1, 0.479724,-99) , 
3, 249.409, 0, 0, 0.486219,-99)    );
  // itree = 13
  fBoostWeights.push_back(0.0660928);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.556493,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467223,-99) , 
2, 2.57825, 0, 0, 0.533969,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531718,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480863,-99) , 
2, 3.60973, 0, 0, 0.489685,-99) , 
3, 148.864, 0, 0, 0.502848,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.441513,-99) , 
0, 254.52, 1, 0, 0.496384,-99)    );
  // itree = 14
  fBoostWeights.push_back(0.0516058);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519047,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465885,-99) , 
1, 135.316, 0, 0, 0.511675,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.448219,-99) , 
1, 273.855, 1, 0, 0.507467,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.439098,-99) , 
1, 334.467, 1, 0, 0.502736,-99)    );
  // itree = 15
  fBoostWeights.push_back(0.0410328);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517527,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488997,-99) , 
0, 125.846, 1, 0, 0.506091,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462038,-99) , 
0, 61.5092, 0, 0, 0.501478,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.452479,-99) , 
0, 254.52, 1, 0, 0.496319,-99)    );
  // itree = 16
  fBoostWeights.push_back(0.0210296);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.549847,-99) , 
NN(
0, 
0, 
-1, 334.467, 1, -1, 0.492567,-99) , 
3, 249.409, 0, 0, 0.496728,-99)    );
  // itree = 17
  fBoostWeights.push_back(0.0244928);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.544637,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504313,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460803,-99) , 
1, 273.855, 1, 0, 0.501471,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.445928,-99) , 
1, 334.467, 1, 0, 0.497824,-99) , 
3, 249.409, 0, 0, 0.501222,-99)    );
  // itree = 18
  fBoostWeights.push_back(0.0484264);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528686,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484832,-99) , 
3, 99.3907, 0, 0, 0.509655,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503725,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461455,-99) , 
1, 183.419, 0, 0, 0.481465,-99) , 
0, 95.5694, 0, 0, 0.50059,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462031,-99) , 
0, 254.52, 1, 0, 0.496537,-99)    );
  // itree = 19
  fBoostWeights.push_back(0.0330396);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53912,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496047,-99) , 
0, 136.255, 0, 0, 0.511013,-99) , 
NN(
0, 
0, 
-1, 134.068, 1, -1, 0.487033,-99) , 
1, 176.877, 1, 0, 0.499853,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.45867,-99) , 
1, 334.467, 1, 0, 0.49702,-99)    );
  // itree = 20
  fBoostWeights.push_back(0.0286963);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538698,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511993,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491693,-99) , 
1, 176.877, 1, 0, 0.502584,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456799,-99) , 
1, 334.467, 1, 0, 0.499586,-99) , 
3, 249.409, 0, 0, 0.502423,-99)    );
  // itree = 21
  fBoostWeights.push_back(0.0376966);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523144,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48919,-99) , 
0, 148.552, 1, 0, 0.512175,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506231,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475885,-99) , 
1, 183.419, 0, 0, 0.490266,-99) , 
0, 95.5694, 0, 0, 0.505127,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474233,-99) , 
0, 254.52, 1, 0, 0.501886,-99)    );
  // itree = 22
  fBoostWeights.push_back(0.0225456);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532039,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505285,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480833,-99) , 
1, 140.511, 0, 0, 0.501176,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461264,-99) , 
1, 334.467, 1, 0, 0.498569,-99) , 
3, 249.409, 0, 0, 0.500992,-99)    );
  // itree = 23
  fBoostWeights.push_back(0.0196164);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526422,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526244,-99) , 
NN(
0, 
0, 
-1, 334.467, 1, -1, 0.492932,-99) , 
2, 4.12527, 0, 0, 0.495439,-99) , 
3, 249.409, 0, 0, 0.497681,-99)    );
  // itree = 24
  fBoostWeights.push_back(0.0191979);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 202.953, 0, 1, 0.520694,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503832,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471656,-99) , 
2, 1.51338, 0, 0, 0.50115,-99) , 
2, 3.52528, 0, 0, 0.504231,-99) , 
NN(
0, 
0, 
-1, 3.09419, 1, -1, 0.481353,-99) , 
3, 49.9552, 0, 0, 0.501191,-99)    );
  // itree = 25
  fBoostWeights.push_back(0.0182293);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527945,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497974,-99) , 
2, 2.0631, 1, 0, 0.502755,-99) , 
NN(
0, 
0, 
-1, 277.896, 1, -1, 0.478798,-99) , 
1, 249.611, 1, 0, 0.500043,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473874,-99) , 
1, 334.467, 1, 0, 0.498251,-99)    );
  // itree = 26
  fBoostWeights.push_back(0.0245456);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 118.276, 1, 1, 0.509391,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512824,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481341,-99) , 
3, 84.2674, 1, 0, 0.491888,-99) , 
0, 95.5694, 0, 0, 0.503759,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483242,-99) , 
0, 254.52, 1, 0, 0.501607,-99)    );
  // itree = 27
  fBoostWeights.push_back(0.0205715);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516421,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496244,-99) , 
0, 136.255, 0, 0, 0.50323,-99) , 
NN(
0, 
0, 
-1, 277.896, 1, -1, 0.481351,-99) , 
1, 249.611, 1, 0, 0.500752,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47674,-99) , 
1, 334.467, 1, 0, 0.499109,-99)    );
  // itree = 28
  fBoostWeights.push_back(0.0186398);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 202.953, 0, 1, 0.520099,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503028,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473358,-99) , 
2, 1.51338, 0, 0, 0.500557,-99) , 
2, 3.52528, 0, 0, 0.503639,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509571,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468876,-99) , 
0, 108.506, 1, 0, 0.486107,-99) , 
3, 49.9552, 0, 0, 0.50131,-99)    );
  // itree = 29
  fBoostWeights.push_back(0.0117026);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519313,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500661,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477679,-99) , 
1, 249.611, 1, 0, 0.498105,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470422,-99) , 
1, 334.467, 1, 0, 0.496284,-99) , 
2, 4.12527, 0, 0, 0.497931,-99)    );
  // itree = 30
  fBoostWeights.push_back(0.0230249);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516391,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516948,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504626,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486214,-99) , 
2, 2.55409, 1, 0, 0.4925,-99) , 
3, 249.758, 0, 0, 0.494351,-99) , 
2, 4.12527, 0, 0, 0.495927,-99)    );
  // itree = 31
  fBoostWeights.push_back(0.0195636);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513504,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495916,-99) , 
3, 148.864, 0, 0, 0.501049,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470143,-99) , 
0, 197.75, 1, 0, 0.498428,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481723,-99) , 
0, 254.52, 1, 0, 0.496676,-99)    );
  // itree = 32
  fBoostWeights.push_back(0.0190718);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510447,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494608,-99) , 
1, 177.456, 1, 0, 0.502446,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480141,-99) , 
1, 128.389, 0, 0, 0.500432,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482828,-99) , 
1, 334.467, 1, 0, 0.499228,-99)    );
  // itree = 33
  fBoostWeights.push_back(0.0177951);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515606,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517421,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49715,-99) , 
2, 3.34035, 0, 0, 0.500632,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515351,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.453279,-99) , 
2, 2.75047, 1, 0, 0.485359,-99) , 
3, 50.3914, 0, 0, 0.498794,-99) , 
2, 4.12527, 0, 0, 0.499997,-99)    );
  // itree = 34
  fBoostWeights.push_back(0.0167754);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 207.183, 0, 1, 0.506184,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485875,-99) , 
2, 1.76486, 0, 0, 0.504121,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507089,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474824,-99) , 
0, 108.506, 1, 0, 0.488491,-99) , 
3, 49.9552, 0, 0, 0.502047,-99)    );
  // itree = 35
  fBoostWeights.push_back(0.0594144);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 126.472, 0, 1, 0.53401,-99) , 
NN(
0, 
0, 
-1, 130.007, 0, -1, 0.459445,-99) , 
0, 134.068, 1, 0, 0.505556,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.549823,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.446175,-99) , 
3, 149.984, 1, 0, 0.515416,-99) , 
NN(
0, 
0, 
-1, 182.939, 1, -1, 0.486359,-99) , 
0, 136.255, 0, 0, 0.496427,-99) , 
1, 207.183, 0, 0, 0.499234,-99)    );
  // itree = 36
  fBoostWeights.push_back(0.0184446);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.0631, 1, 1, 0.50802,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503189,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47296,-99) , 
0, 134.068, 1, 0, 0.491928,-99) , 
1, 225.366, 1, 0, 0.50509,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484457,-99) , 
1, 334.467, 1, 0, 0.503682,-99)    );
  // itree = 37
  fBoostWeights.push_back(0.0107257);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515343,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509344,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498633,-99) , 
3, 167.546, 0, 0, 0.500765,-99) , 
3, 239.911, 0, 0, 0.502158,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501231,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470726,-99) , 
2, 3.09419, 1, 0, 0.488028,-99) , 
3, 49.9552, 0, 0, 0.500284,-99)    );
  // itree = 38
  fBoostWeights.push_back(0.0130819);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 239.912, 0, 1, 0.5047,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491524,-99) , 
2, 1.76486, 0, 0, 0.503362,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504407,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475353,-99) , 
0, 108.506, 1, 0, 0.487666,-99) , 
3, 49.9552, 0, 0, 0.50128,-99)    );
  // itree = 39
  fBoostWeights.push_back(0.0114052);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524246,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499241,-99) , 
1, 202.953, 0, 0, 0.508485,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503472,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495756,-99) , 
2, 2.85464, 0, 0, 0.499309,-99) , 
2, 3.52528, 0, 0, 0.500756,-99) , 
NN(
0, 
0, 
-1, 3.09419, 1, -1, 0.488162,-99) , 
3, 49.9552, 0, 0, 0.499085,-99)    );
  // itree = 40
  fBoostWeights.push_back(0.034533);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536921,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488143,-99) , 
3, 87.0187, 1, 0, 0.510146,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528311,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479462,-99) , 
0, 136.586, 1, 0, 0.508925,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519922,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489209,-99) , 
3, 135.435, 0, 0, 0.49229,-99) , 
3, 149.682, 0, 0, 0.497722,-99) , 
2, 2.0631, 1, 0, 0.49973,-99)    );
  // itree = 41
  fBoostWeights.push_back(0.014955);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516103,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505205,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47935,-99) , 
1, 273.855, 1, 0, 0.503537,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484473,-99) , 
1, 334.467, 1, 0, 0.502288,-99) , 
2, 4.12527, 0, 0, 0.503277,-99)    );
  // itree = 42
  fBoostWeights.push_back(0.0137052);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52556,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486641,-99) , 
1, 185.617, 1, 0, 0.508289,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520284,-99) , 
NN(
0, 
0, 
-1, 35.7084, 0, -1, 0.497071,-99) , 
3, 249.409, 0, 0, 0.498894,-99) , 
2, 2.0631, 1, 0, 0.500411,-99)    );
  // itree = 43
  fBoostWeights.push_back(0.0119318);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515625,-99) , 
NN(
NN(
0, 
0, 
-1, 3.34035, 0, 1, 0.503336,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509096,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470355,-99) , 
2, 2.75047, 1, 0, 0.49039,-99) , 
3, 50.3914, 0, 0, 0.50178,-99) , 
2, 4.12527, 0, 0, 0.502771,-99)    );
  // itree = 44
  fBoostWeights.push_back(0.00960965);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512645,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508547,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498654,-99) , 
2, 3.34035, 0, 0, 0.500353,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506114,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473328,-99) , 
2, 2.75047, 1, 0, 0.490286,-99) , 
3, 50.3914, 0, 0, 0.499143,-99) , 
2, 4.12527, 0, 0, 0.50011,-99)    );
  // itree = 45
  fBoostWeights.push_back(0.0182981);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507411,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487615,-99) , 
0, 67.9957, 0, 0, 0.50451,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478525,-99) , 
0, 197.75, 1, 0, 0.50231,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491881,-99) , 
0, 254.52, 1, 0, 0.501217,-99)    );
  // itree = 46
  fBoostWeights.push_back(0.0217676);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516486,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488956,-99) , 
0, 134.068, 1, 0, 0.505854,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505545,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485087,-99) , 
3, 144.934, 1, 0, 0.498132,-99) , 
1, 207.183, 0, 0, 0.500534,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505233,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482136,-99) , 
0, 108.506, 1, 0, 0.491926,-99) , 
3, 49.9552, 0, 0, 0.499393,-99)    );
  // itree = 47
  fBoostWeights.push_back(0.037001);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532373,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478669,-99) , 
1, 188.386, 1, 0, 0.510902,-99) , 
NN(
0, 
0, 
-1, 192.71, 0, -1, 0.487546,-99) , 
3, 149.984, 1, 0, 0.502773,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519146,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49224,-99) , 
0, 103.41, 0, 0, 0.501899,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454289,-99) , 
0, 123.954, 1, 0, 0.495757,-99) , 
0, 135.308, 0, 0, 0.498273,-99)    );
  // itree = 48
  fBoostWeights.push_back(0.025944);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 164.677, 0, 1, 0.516689,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4878,-99) , 
3, 86.5638, 0, 0, 0.507568,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510652,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491041,-99) , 
1, 148.592, 0, 0, 0.503017,-99) , 
NN(
0, 
0, 
-1, 195.638, 1, -1, 0.480448,-99) , 
1, 182.939, 1, 0, 0.498401,-99) , 
1, 207.183, 0, 0, 0.501218,-99)    );
  // itree = 49
  fBoostWeights.push_back(0.0219078);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522894,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5217,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477292,-99) , 
0, 114.393, 1, 0, 0.499317,-99) , 
3, 172.899, 0, 0, 0.50518,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515588,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497985,-99) , 
2, 2.0631, 1, 0, 0.500751,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475992,-99) , 
1, 195.061, 1, 0, 0.498585,-99) , 
1, 207.183, 0, 0, 0.500611,-99)    );
  // itree = 50
  fBoostWeights.push_back(0.0215036);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.96112, 1, 1, 0.513511,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503532,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485575,-99) , 
1, 185.617, 1, 0, 0.495734,-99) , 
2, 2.64684, 0, 0, 0.507174,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514002,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498886,-99) , 
3, 99.2736, 1, 0, 0.505563,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466444,-99) , 
0, 123.954, 1, 0, 0.500525,-99) , 
0, 135.308, 0, 0, 0.50291,-99)    );
  // itree = 51
  fBoostWeights.push_back(0.0125285);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513544,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499195,-99) , 
3, 144.934, 0, 0, 0.504799,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492816,-99) , 
2, 1.76486, 0, 0, 0.503583,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502769,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484997,-99) , 
3, 33.334, 0, 0, 0.49445,-99) , 
3, 49.9552, 0, 0, 0.502373,-99)    );
  // itree = 52
  fBoostWeights.push_back(0.0116745);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 239.912, 0, 1, 0.505485,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495948,-99) , 
2, 1.76486, 0, 0, 0.504518,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503937,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487109,-99) , 
0, 108.506, 1, 0, 0.49425,-99) , 
3, 49.9552, 0, 0, 0.503157,-99)    );
  // itree = 53
  fBoostWeights.push_back(0.0272422);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 106.002, 1, 1, 0.513141,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463088,-99) , 
3, 173.306, 1, 0, 0.504997,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52117,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492561,-99) , 
0, 136.586, 1, 0, 0.50977,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516621,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490788,-99) , 
2, 4.14982, 0, 0, 0.494162,-99) , 
3, 149.682, 0, 0, 0.499433,-99) , 
2, 2.57864, 1, 0, 0.501197,-99)    );
  // itree = 54
  fBoostWeights.push_back(0.014656);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 239.912, 0, 1, 0.50457,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512252,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463535,-99) , 
3, 131.555, 1, 0, 0.49526,-99) , 
2, 2.20497, 0, 0, 0.502842,-99) , 
NN(
0, 
0, 
-1, 30.9595, 0, -1, 0.494209,-99) , 
3, 49.9552, 0, 0, 0.501698,-99)    );
  // itree = 55
  fBoostWeights.push_back(0.00890519);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510534,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507442,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497333,-99) , 
3, 166.303, 0, 0, 0.49926,-99) , 
3, 249.409, 0, 0, 0.500106,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491464,-99) , 
2, 1.54756, 0, 0, 0.499416,-99)    );
  // itree = 56
  fBoostWeights.push_back(0.0169439);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 119.874, 1, 1, 0.506488,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504995,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481009,-99) , 
2, 3.46243, 0, 0, 0.494062,-99) , 
2, 3.09419, 1, 0, 0.501874,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502579,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482065,-99) , 
3, 239.911, 0, 0, 0.493424,-99) , 
3, 199.545, 1, 0, 0.500613,-99)    );
  // itree = 57
  fBoostWeights.push_back(0.012816);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508808,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491138,-99) , 
3, 149.984, 1, 0, 0.502436,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500862,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470536,-99) , 
0, 123.954, 1, 0, 0.496933,-99) , 
0, 135.308, 0, 0, 0.498886,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489799,-99) , 
2, 1.54756, 0, 0, 0.498161,-99)    );
  // itree = 58
  fBoostWeights.push_back(0.0178189);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.96112, 1, 1, 0.506915,-99) , 
NN(
0, 
0, 
-1, 2.01829, 1, -1, 0.488768,-99) , 
2, 2.64684, 0, 0, 0.500445,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506896,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494356,-99) , 
2, 2.57864, 1, 0, 0.498312,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469676,-99) , 
0, 123.954, 1, 0, 0.494628,-99) , 
0, 135.308, 0, 0, 0.496715,-99)    );
  // itree = 59
  fBoostWeights.push_back(0.0123947);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523068,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497628,-99) , 
1, 204.585, 0, 0, 0.500332,-99) , 
NN(
0, 
0, 
-1, 277.319, 1, -1, 0.488186,-99) , 
1, 225.366, 1, 0, 0.498121,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489609,-99) , 
1, 334.467, 1, 0, 0.497542,-99)    );
  // itree = 60
  fBoostWeights.push_back(0.00817667);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 204.585, 0, 1, 0.502772,-99) , 
NN(
0, 
0, 
-1, 277.319, 1, -1, 0.491283,-99) , 
1, 225.366, 1, 0, 0.500681,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492707,-99) , 
1, 334.467, 1, 0, 0.500139,-99)    );
  // itree = 61
  fBoostWeights.push_back(0.0118281);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 164.677, 0, 1, 0.506556,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491372,-99) , 
3, 86.5638, 0, 0, 0.501763,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501957,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481652,-99) , 
1, 123.771, 0, 0, 0.499904,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476668,-99) , 
1, 195.061, 1, 0, 0.497872,-99) , 
1, 207.183, 0, 0, 0.499066,-99)    );
  // itree = 62
  fBoostWeights.push_back(0.0106967);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51499,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502678,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479014,-99) , 
1, 328.407, 1, 0, 0.497353,-99) , 
2, 3.55607, 0, 0, 0.500673,-99) , 
NN(
0, 
0, 
-1, 195.061, 1, -1, 0.495977,-99) , 
1, 207.183, 0, 0, 0.497419,-99)    );
  // itree = 63
  fBoostWeights.push_back(0.0141782);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516289,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510447,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495053,-99) , 
2, 2.0631, 1, 0, 0.497805,-99) , 
3, 171.052, 0, 0, 0.499492,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502524,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484331,-99) , 
0, 136.756, 1, 0, 0.494525,-99) , 
3, 199.545, 1, 0, 0.498751,-99)    );
  // itree = 64
  fBoostWeights.push_back(0.00855142);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503987,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497667,-99) , 
2, 2.83116, 0, 0, 0.502443,-99) , 
NN(
0, 
0, 
-1, 130.387, 1, -1, 0.494968,-99) , 
2, 2.43135, 0, 0, 0.500964,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491041,-99) , 
2, 1.54756, 0, 0, 0.500172,-99)    );
  // itree = 65
  fBoostWeights.push_back(0.0288785);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512888,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488345,-99) , 
3, 114.065, 1, 0, 0.506543,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523168,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489137,-99) , 
3, 121.213, 0, 0, 0.496146,-99) , 
0, 119.874, 1, 0, 0.5018,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521362,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485058,-99) , 
0, 136.756, 1, 0, 0.506877,-99) , 
NN(
0, 
0, 
-1, 2.38565, 0, -1, 0.48332,-99) , 
2, 2.94594, 0, 0, 0.495692,-99) , 
3, 149.682, 1, 0, 0.499925,-99)    );
  // itree = 66
  fBoostWeights.push_back(0.0176935);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523391,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495951,-99) , 
1, 188.386, 1, 0, 0.512423,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501064,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492668,-99) , 
3, 192.71, 0, 0, 0.497596,-99) , 
3, 149.984, 1, 0, 0.507266,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505848,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495178,-99) , 
0, 98.2735, 0, 0, 0.499894,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478425,-99) , 
0, 123.954, 1, 0, 0.497136,-99) , 
0, 135.308, 0, 0, 0.500771,-99)    );
  // itree = 67
  fBoostWeights.push_back(0.0138331);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521789,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497175,-99) , 
3, 78.7741, 0, 0, 0.511539,-99) , 
NN(
0, 
0, 
-1, 192.71, 1, -1, 0.496827,-99) , 
3, 149.984, 1, 0, 0.506421,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502133,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48842,-99) , 
3, 198.455, 1, 0, 0.500407,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482841,-99) , 
0, 123.954, 1, 0, 0.498151,-99) , 
0, 135.308, 0, 0, 0.501118,-99)    );
  // itree = 68
  fBoostWeights.push_back(0.0313113);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515779,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49568,-99) , 
1, 209.499, 1, 0, 0.509703,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4965,-99) , 
3, 199.83, 1, 0, 0.507248,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520507,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476106,-99) , 
3, 126.355, 1, 0, 0.502576,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515419,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48334,-99) , 
3, 148.975, 0, 0, 0.492483,-99) , 
0, 89.8935, 1, 0, 0.496339,-99) , 
0, 135.308, 0, 0, 0.500253,-99)    );
  // itree = 69
  fBoostWeights.push_back(0.0120469);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.87731, 1, 1, 0.508469,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497512,-99) , 
2, 2.20686, 0, 0, 0.506186,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502537,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491929,-99) , 
3, 148.864, 1, 0, 0.499573,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501352,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479499,-99) , 
0, 126.387, 1, 0, 0.491408,-99) , 
0, 118.277, 1, 0, 0.497843,-99) , 
0, 135.308, 0, 0, 0.500837,-99)    );
  // itree = 70
  fBoostWeights.push_back(0.0138683);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515393,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493795,-99) , 
3, 87.0187, 0, 0, 0.508537,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502495,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490617,-99) , 
2, 3.38015, 0, 0, 0.497661,-99) , 
2, 3.08683, 1, 0, 0.50443,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50687,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496186,-99) , 
0, 108.545, 0, 0, 0.498244,-99) , 
NN(
0, 
0, 
-1, 126.387, 1, -1, 0.491136,-99) , 
0, 118.277, 1, 0, 0.496738,-99) , 
0, 135.308, 0, 0, 0.499498,-99)    );
  // itree = 71
  fBoostWeights.push_back(0.0152463);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515999,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510121,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49359,-99) , 
0, 114.393, 1, 0, 0.501789,-99) , 
3, 172.899, 0, 0, 0.505321,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504673,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493097,-99) , 
1, 170.816, 1, 0, 0.500004,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483491,-99) , 
1, 122.328, 0, 0, 0.498618,-99) , 
1, 207.183, 0, 0, 0.500676,-99)    );
  // itree = 72
  fBoostWeights.push_back(0.0110321);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514702,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505925,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488496,-99) , 
1, 328.407, 1, 0, 0.502007,-99) , 
2, 3.55607, 0, 0, 0.504397,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502641,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496248,-99) , 
2, 2.75048, 0, 0, 0.499671,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490054,-99) , 
2, 3.60973, 1, 0, 0.498263,-99) , 
1, 207.183, 0, 0, 0.500146,-99)    );
  // itree = 73
  fBoostWeights.push_back(0.0151298);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.64683, 0, 1, 0.50768,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504095,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491595,-99) , 
1, 197.872, 0, 0, 0.496281,-99) , 
2, 3.08683, 1, 0, 0.503376,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510031,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492145,-99) , 
3, 115.997, 1, 0, 0.503035,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503816,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491526,-99) , 
3, 148.864, 0, 0, 0.495376,-99) , 
2, 2.57864, 1, 0, 0.497756,-99) , 
0, 135.308, 0, 0, 0.499773,-99)    );
  // itree = 74
  fBoostWeights.push_back(0.0126352);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511785,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505435,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494097,-99) , 
3, 130.163, 0, 0, 0.499298,-99) , 
2, 3.55607, 0, 0, 0.501649,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516205,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498659,-99) , 
3, 128.312, 0, 0, 0.501172,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503876,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474397,-99) , 
0, 136.467, 1, 0, 0.49227,-99) , 
3, 149.682, 1, 0, 0.498571,-99) , 
1, 207.183, 0, 0, 0.499516,-99)    );
  // itree = 75
  fBoostWeights.push_back(0.0125844);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 85.8457, 0, 1, 0.512424,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502309,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482094,-99) , 
0, 223.653, 1, 0, 0.499965,-99) , 
2, 2.0631, 1, 0, 0.502266,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504771,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500717,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477548,-99) , 
0, 136.467, 1, 0, 0.491597,-99) , 
1, 207.183, 0, 0, 0.496085,-99) , 
3, 149.682, 1, 0, 0.500368,-99)    );
  // itree = 76
  fBoostWeights.push_back(0.0134615);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510443,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493388,-99) , 
0, 233.41, 1, 0, 0.504969,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500197,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493075,-99) , 
3, 192.71, 0, 0, 0.497254,-99) , 
3, 149.984, 1, 0, 0.502284,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506262,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490784,-99) , 
3, 115.997, 1, 0, 0.500207,-99) , 
NN(
0, 
0, 
-1, 2.97144, 0, -1, 0.493833,-99) , 
2, 2.57864, 1, 0, 0.495815,-99) , 
0, 135.308, 0, 0, 0.498136,-99)    );
  // itree = 77
  fBoostWeights.push_back(0.00522886);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504904,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500937,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495986,-99) , 
3, 83.1972, 0, 0, 0.499275,-99) , 
3, 249.409, 0, 0, 0.499697,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492487,-99) , 
2, 1.54756, 0, 0, 0.499122,-99)    );
  // itree = 78
  fBoostWeights.push_back(0.0156248);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 85.8457, 0, 1, 0.508186,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505183,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49552,-99) , 
2, 3.31514, 0, 0, 0.498607,-99) , 
2, 2.0631, 1, 0, 0.500376,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514369,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481872,-99) , 
3, 192.422, 0, 0, 0.500225,-99) , 
NN(
0, 
0, 
-1, 2.38565, 0, -1, 0.489535,-99) , 
2, 2.94594, 0, 0, 0.495147,-99) , 
3, 149.682, 1, 0, 0.49877,-99)    );
  // itree = 79
  fBoostWeights.push_back(0.0128385);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 161.676, 0, 1, 0.505024,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502925,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488864,-99) , 
2, 3.83068, 0, 0, 0.493429,-99) , 
2, 3.09419, 1, 0, 0.500718,-99) , 
NN(
0, 
0, 
-1, 239.911, 0, -1, 0.492923,-99) , 
3, 199.545, 1, 0, 0.499556,-99)    );
  // itree = 80
  fBoostWeights.push_back(0.00596502);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506014,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499575,-99) , 
3, 199.545, 0, 0, 0.500651,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50165,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492332,-99) , 
2, 2.26301, 0, 0, 0.495004,-99) , 
2, 2.43135, 0, 0, 0.499533,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488734,-99) , 
2, 1.54756, 0, 0, 0.498673,-99)    );
  // itree = 81
  fBoostWeights.push_back(0.00562675);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 135.308, 0, 1, 0.501644,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50017,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492128,-99) , 
2, 2.05258, 1, 0, 0.49564,-99) , 
2, 2.43135, 0, 0, 0.500455,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490225,-99) , 
2, 1.54756, 0, 0, 0.499641,-99)    );
  // itree = 82
  fBoostWeights.push_back(0.00567122);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502725,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498882,-99) , 
0, 135.308, 0, 0, 0.500237,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501565,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493506,-99) , 
2, 2.26301, 0, 0, 0.495818,-99) , 
2, 2.43135, 0, 0, 0.499362,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491631,-99) , 
2, 1.54756, 0, 0, 0.498747,-99)    );
  // itree = 83
  fBoostWeights.push_back(0.00559064);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512677,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500077,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490384,-99) , 
3, 146.629, 1, 0, 0.498908,-99) , 
3, 171.052, 0, 0, 0.500165,-99) , 
NN(
0, 
0, 
-1, 239.911, 0, -1, 0.494217,-99) , 
3, 199.545, 1, 0, 0.499278,-99)    );
  // itree = 84
  fBoostWeights.push_back(0.00518174);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504658,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499062,-99) , 
3, 199.545, 0, 0, 0.499996,-99) , 
NN(
0, 
0, 
-1, 2.05258, 1, -1, 0.495562,-99) , 
2, 2.43135, 0, 0, 0.499119,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492077,-99) , 
2, 1.54756, 0, 0, 0.498558,-99)    );
  // itree = 85
  fBoostWeights.push_back(0.00813587);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 161.676, 0, 1, 0.503367,-99) , 
NN(
0, 
0, 
-1, 124.687, 1, -1, 0.495295,-99) , 
2, 3.09419, 1, 0, 0.500369,-99) , 
NN(
0, 
0, 
-1, 239.911, 0, -1, 0.494767,-99) , 
3, 199.545, 1, 0, 0.499534,-99)    );
  // itree = 86
  fBoostWeights.push_back(0.00489538);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 199.545, 0, 1, 0.501246,-99) , 
NN(
0, 
0, 
-1, 87.2552, 0, -1, 0.495247,-99) , 
2, 2.43135, 0, 0, 0.500058,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491686,-99) , 
2, 1.54756, 0, 0, 0.499392,-99)    );
  // itree = 87
  fBoostWeights.push_back(0.00688077);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505143,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504744,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497459,-99) , 
3, 166.303, 0, 0, 0.498847,-99) , 
3, 249.409, 0, 0, 0.499319,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492909,-99) , 
2, 1.54756, 0, 0, 0.498809,-99)    );
  // itree = 88
  fBoostWeights.push_back(0.00950246);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504444,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496484,-99) , 
2, 3.09419, 1, 0, 0.501515,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487718,-99) , 
1, 334.467, 1, 0, 0.500661,-99) , 
NN(
0, 
0, 
-1, 239.911, 0, -1, 0.494436,-99) , 
3, 199.545, 1, 0, 0.499733,-99)    );
  // itree = 89
  fBoostWeights.push_back(0.0113339);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 136.695, 0, 1, 0.506036,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504361,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491868,-99) , 
3, 100.137, 1, 0, 0.496816,-99) , 
0, 136.255, 1, 0, 0.50281,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508224,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498088,-99) , 
3, 142.332, 0, 0, 0.50037,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482974,-99) , 
3, 198.973, 1, 0, 0.497849,-99) , 
2, 3.09419, 0, 0, 0.499712,-99)    );
  // itree = 90
  fBoostWeights.push_back(0.00937059);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508331,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501506,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488774,-99) , 
0, 223.653, 1, 0, 0.500019,-99) , 
3, 128.312, 0, 0, 0.501241,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505383,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501934,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481481,-99) , 
0, 136.467, 1, 0, 0.493885,-99) , 
1, 207.183, 0, 0, 0.497802,-99) , 
3, 149.682, 1, 0, 0.500186,-99)    );
  // itree = 91
  fBoostWeights.push_back(0.0150401);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516448,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498304,-99) , 
2, 2.96112, 1, 0, 0.503274,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502547,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494617,-99) , 
1, 185.617, 0, 0, 0.498059,-99) , 
2, 2.64684, 0, 0, 0.501416,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512649,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48283,-99) , 
3, 126.355, 1, 0, 0.500608,-99) , 
NN(
0, 
0, 
-1, 98.544, 0, -1, 0.494657,-99) , 
0, 89.8935, 1, 0, 0.496931,-99) , 
0, 135.308, 0, 0, 0.49854,-99)    );
  // itree = 92
  fBoostWeights.push_back(0.0118669);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505759,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505572,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496114,-99) , 
0, 99.3537, 0, 0, 0.501641,-99) , 
NN(
0, 
0, 
-1, 212.888, 1, -1, 0.487192,-99) , 
0, 175.043, 1, 0, 0.49967,-99) , 
0, 254.52, 0, 0, 0.500308,-99)    );
  // itree = 93
  fBoostWeights.push_back(0.00515521);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508329,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505586,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498831,-99) , 
3, 178.175, 0, 0, 0.499827,-99) , 
3, 249.409, 0, 0, 0.500464,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494296,-99) , 
2, 1.54756, 0, 0, 0.499972,-99)    );
  // itree = 94
  fBoostWeights.push_back(0.00476609);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50704,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501377,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49266,-99) , 
3, 35.7084, 0, 0, 0.500736,-99) , 
3, 249.409, 0, 0, 0.501208,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495585,-99) , 
2, 1.54756, 0, 0, 0.50076,-99)    );
  // itree = 95
  fBoostWeights.push_back(0.0104994);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508803,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510257,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4985,-99) , 
2, 4.12527, 0, 0, 0.499623,-99) , 
3, 128.312, 0, 0, 0.500973,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512107,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489038,-99) , 
3, 192.422, 0, 0, 0.502069,-99) , 
NN(
0, 
0, 
-1, 2.38565, 0, -1, 0.492451,-99) , 
2, 2.94594, 0, 0, 0.497502,-99) , 
3, 149.682, 1, 0, 0.499908,-99)    );
  // itree = 96
  fBoostWeights.push_back(0.00961387);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504381,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495182,-99) , 
1, 225.366, 1, 0, 0.502736,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4906,-99) , 
1, 334.467, 1, 0, 0.501985,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501735,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490844,-99) , 
3, 239.911, 0, 0, 0.496872,-99) , 
3, 199.545, 1, 0, 0.501223,-99)    );
  // itree = 97
  fBoostWeights.push_back(0.0081025);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509434,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504065,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498656,-99) , 
2, 3.31514, 0, 0, 0.500209,-99) , 
2, 1.54756, 1, 0, 0.501065,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505122,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50154,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482623,-99) , 
0, 136.467, 1, 0, 0.494096,-99) , 
1, 207.183, 0, 0, 0.497852,-99) , 
3, 149.682, 1, 0, 0.500079,-99)    );
  // itree = 98
  fBoostWeights.push_back(0.00985122);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509892,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498448,-99) , 
0, 90.2232, 1, 0, 0.503818,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505782,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496667,-99) , 
3, 114.095, 0, 0, 0.499082,-99) , 
0, 119.874, 1, 0, 0.501659,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503096,-99) , 
NN(
0, 
0, 
-1, 152.633, 0, -1, 0.493664,-99) , 
1, 207.183, 0, 0, 0.496877,-99) , 
3, 149.682, 1, 0, 0.500192,-99)    );
  // itree = 99
  fBoostWeights.push_back(0.0104022);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 71.6599, 1, 1, 0.507168,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502373,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4919,-99) , 
0, 223.653, 1, 0, 0.50116,-99) , 
2, 2.0631, 1, 0, 0.502269,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508988,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490266,-99) , 
3, 192.422, 0, 0, 0.500841,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501183,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482668,-99) , 
2, 2.38565, 0, 0, 0.494145,-99) , 
2, 2.94594, 0, 0, 0.497662,-99) , 
3, 149.682, 1, 0, 0.500856,-99)    );
   return;
};
 
// Clean up
inline void ReadBDT::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDT::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
