// Class: ReadBDT
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.06/01       [394753]
Creator        : kskovpen
Date           : Sat Aug 20 14:31:31 2016
Host           : Linux vocms0315.cern.ch 2.6.32-573.26.1.el6.x86_64 #1 SMP Wed May 4 09:23:05 CEST 2016 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /grid_mnt/home-pbs/kskovpen/tHFCNC2016/CMSSW_8_0_12/src/TopKinFit/test/Validation/TopHLepbb/MVA
Training events: 21341
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "100" [Number of trees in the forest]
MaxDepth: "3" [Max depth of the decision tree allowed]
nCuts: "20" [Number of grid points in variable range used in finding optimal cut in node splitting]
SeparationType: "giniindex" [Separation criterion for node splitting]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
MinNodeSize: "5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
BoostType: "AdaBoost" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
UseBaggedBoost: "False" [Use only a random subsample of all events for growing the trees in each boost iteration.]
Shrinkage: "1.000000e+00" [Learning rate for GradBoost algorithm]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "2" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split with RandomisedTree option]
BaggedSampleFraction: "6.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "inverseboostnegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "6.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 4
HiggsRecMCSVv2L               HiggsRecMCSVv2L               HiggsRecMCSVv2L               HiggsRecMCSVv2L                                                 'F'    [21.4971313477,2230.15063477]
TopLepRecMTCSVv2L             TopLepRecMTCSVv2L             TopLepRecMTCSVv2L             TopLepRecMTCSVv2L                                               'F'    [2.10873889923,1484.20825195]
HiggsTopLepRecDphiTCSVv2L     HiggsTopLepRecDphiTCSVv2L     HiggsTopLepRecDphiTCSVv2L     HiggsTopLepRecDphiTCSVv2L                                       'F'    [-3.14147543907,3.14158606529]
TopLepRecPtTCSVv2L            TopLepRecPtTCSVv2L            TopLepRecPtTCSVv2L            TopLepRecPtTCSVv2L                                              'F'    [1.50272488594,1322.55407715]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDTNode
   
#ifndef BDTNode__def
#define BDTNode__def
   
class BDTNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDTNode ( BDTNode* left,BDTNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTNode();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTNode* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTNode*   fLeft;     // pointer to the left daughter node
   BDTNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDTNode::~BDTNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDTNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDTNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT : public IClassifierReader {

 public:

   // constructor
   ReadBDT( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDT" ),
        fNvars( 4 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "HiggsRecMCSVv2L", "TopLepRecMTCSVv2L", "HiggsTopLepRecDphiTCSVv2L", "TopLepRecPtTCSVv2L" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[4];
   double fVmax[4];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[4];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTNode*)current->GetRight();
         else current=(BDTNode*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
};

void ReadBDT::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(0.47352835361011);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.682081,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.32211,-99) , 
1, 219.178, 1, 0, 0.639222,-99) , 
NN(
0, 
0, 
-1, 156.004, 0, -1, 0.218046,-99) , 
0, 151.682, 1, 0, 0.562758,-99) , 
NN(
0, 
0, 
-1, 174.198, 0, -1, 0.170794,-99) , 
0, 231.845, 1, 0, 0.5,-99)    );
  // itree = 1
  fBoostWeights.push_back(0.327386);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.636634,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.375885,-99) , 
0, 90.1601, 0, 0, 0.566997,-99) , 
NN(
0, 
0, 
-1, 156.004, 0, -1, 0.331336,-99) , 
0, 141.668, 1, 0, 0.512554,-99) , 
NN(
0, 
0, 
-1, 174.198, 0, -1, 0.248527,-99) , 
0, 231.845, 1, 0, 0.47266,-99)    );
  // itree = 2
  fBoostWeights.push_back(0.213937);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 193.507, 1, 1, 0.673034,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.415455,-99) , 
1, 203.613, 1, 0, 0.622895,-99) , 
NN(
0, 
0, 
-1, 231.845, 1, -1, 0.415026,-99) , 
3, 190.224, 0, 0, 0.474867,-99)    );
  // itree = 3
  fBoostWeights.push_back(0.171391);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.614916,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493855,-99) , 
3, 127.317, 0, 0, 0.556411,-99) , 
NN(
0, 
0, 
-1, 191.748, 1, -1, 0.371262,-99) , 
0, 161.697, 1, 0, 0.532076,-99) , 
NN(
0, 
0, 
-1, 166.468, 1, -1, 0.332579,-99) , 
0, 231.845, 1, 0, 0.503522,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.178351);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.575663,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.39603,-99) , 
0, 69.6566, 0, 0, 0.559522,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513371,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.308473,-99) , 
3, 144.968, 0, 0, 0.419196,-99) , 
0, 223.769, 1, 0, 0.540367,-99) , 
NN(
0, 
0, 
-1, 130.194, 1, -1, 0.370607,-99) , 
1, 213.837, 1, 0, 0.513586,-99)    );
  // itree = 5
  fBoostWeights.push_back(0.107348);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.84239, 0, 1, 0.53147,-99) , 
NN(
0, 
0, 
-1, 191.748, 1, -1, 0.387983,-99) , 
0, 161.697, 1, 0, 0.512628,-99) , 
NN(
0, 
0, 
-1, 166.468, 1, -1, 0.37629,-99) , 
0, 231.845, 1, 0, 0.493558,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.142801);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 136.445, 1, 1, 0.587446,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.567884,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457872,-99) , 
0, 106.634, 0, 0, 0.501287,-99) , 
NN(
0, 
0, 
-1, 206.882, 1, -1, 0.412004,-99) , 
0, 126.671, 1, 0, 0.461795,-99) , 
3, 253.132, 0, 0, 0.48019,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.124482);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -3.01327, 1, 1, 0.589835,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.579247,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491422,-99) , 
2, 2.70741, 0, 0, 0.539925,-99) , 
NN(
0, 
0, 
-1, -1.45803, 1, -1, 0.436308,-99) , 
2, 2.00186, 0, 0, 0.476336,-99) , 
2, -2.84228, 1, 0, 0.491922,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.112711);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.564644,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487636,-99) , 
1, 110.277, 0, 0, 0.535923,-99) , 
NN(
0, 
0, 
-1, 130.194, 1, -1, 0.432401,-99) , 
1, 176.868, 1, 0, 0.513302,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.358152,-99) , 
1, 284.413, 1, 0, 0.503049,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.0851525);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -2.54309, 1, 1, 0.532561,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515684,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.406815,-99) , 
0, 129.411, 1, 0, 0.468965,-99) , 
1, 163.425, 1, 0, 0.513942,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.384454,-99) , 
1, 284.413, 1, 0, 0.505469,-99)    );
  // itree = 10
  fBoostWeights.push_back(0.0894079);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.631834,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.595307,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.437603,-99) , 
2, 2.05853, 0, 0, 0.506874,-99) , 
2, -2.543, 1, 0, 0.539173,-99) , 
NN(
0, 
0, 
-1, 231.845, 1, -1, 0.473534,-99) , 
3, 190.224, 0, 0, 0.491945,-99)    );
  // itree = 11
  fBoostWeights.push_back(0.0976547);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 166.554, 0, 1, 0.559211,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.547275,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463248,-99) , 
2, 2.11578, 0, 0, 0.500673,-99) , 
2, -2.2439, 1, 0, 0.517819,-99) , 
NN(
0, 
0, 
-1, 166.468, 1, -1, 0.438497,-99) , 
0, 231.845, 1, 0, 0.50699,-99)    );
  // itree = 12
  fBoostWeights.push_back(0.0527323);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.588212,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512774,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461312,-99) , 
3, 61.3897, 0, 0, 0.504507,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.411899,-99) , 
1, 284.413, 1, 0, 0.498958,-99) , 
3, 316.039, 0, 0, 0.505804,-99)    );
  // itree = 13
  fBoostWeights.push_back(0.0492463);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.575383,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506502,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.40308,-99) , 
0, 181.725, 1, 0, 0.498628,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509076,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.36226,-99) , 
1, 149.087, 1, 0, 0.441279,-99) , 
0, 231.845, 1, 0, 0.491329,-99) , 
3, 316.039, 0, 0, 0.497755,-99)    );
  // itree = 14
  fBoostWeights.push_back(0.0427814);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.563309,-99) , 
NN(
0, 
0, 
-1, 231.845, 1, -1, 0.482084,-99) , 
3, 316.039, 0, 0, 0.488279,-99)    );
  // itree = 15
  fBoostWeights.push_back(0.0398518);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.571415,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505676,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464859,-99) , 
1, 176.868, 1, 0, 0.496764,-99) , 
3, 316.039, 0, 0, 0.502095,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.428052,-99) , 
1, 284.413, 1, 0, 0.497339,-99)    );
  // itree = 16
  fBoostWeights.push_back(0.0329967);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.576762,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498433,-99) , 
2, -1.0473, 1, 0, 0.530124,-99) , 
NN(
0, 
0, 
-1, 231.845, 1, -1, 0.486108,-99) , 
3, 253.132, 0, 0, 0.492431,-99)    );
  // itree = 17
  fBoostWeights.push_back(0.0595673);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525776,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478275,-99) , 
0, 134.52, 1, 0, 0.511378,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.426372,-99) , 
0, 61.5542, 0, 0, 0.505775,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503636,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.424156,-99) , 
3, 174.198, 0, 0, 0.461088,-99) , 
0, 231.845, 1, 0, 0.49972,-99)    );
  // itree = 18
  fBoostWeights.push_back(0.0295087);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.557269,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502018,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.446781,-99) , 
1, 82.7668, 0, 0, 0.495266,-99) , 
3, 316.039, 0, 0, 0.499683,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.441535,-99) , 
1, 284.413, 1, 0, 0.49597,-99)    );
  // itree = 19
  fBoostWeights.push_back(0.0471297);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.544169,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49183,-99) , 
2, -2.54309, 1, 0, 0.503744,-99) , 
NN(
0, 
0, 
-1, -1.34578, 0, -1, 0.456782,-99) , 
0, 81.5827, 0, 0, 0.496348,-99) , 
NN(
0, 
0, 
-1, 1.34653, 0, -1, 0.457601,-99) , 
0, 231.845, 1, 0, 0.4911,-99)    );
  // itree = 20
  fBoostWeights.push_back(0.059096);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.78615, 0, 1, 0.554003,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519942,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467448,-99) , 
3, 91.2801, 0, 0, 0.498969,-99) , 
3, 172.158, 0, 0, 0.517522,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.556786,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49388,-99) , 
3, 230.878, 0, 0, 0.505062,-99) , 
NN(
0, 
0, 
-1, 0.451394, 0, -1, 0.446963,-99) , 
2, -0.862081, 1, 0, 0.487842,-99) , 
2, 1.64562, 0, 0, 0.498972,-99)    );
  // itree = 21
  fBoostWeights.push_back(0.0381054);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -1.34632, 1, 1, 0.514925,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504899,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.449013,-99) , 
1, 151.114, 0, 0, 0.473548,-99) , 
0, 81.5827, 0, 0, 0.508411,-99) , 
NN(
0, 
0, 
-1, 1.34653, 0, -1, 0.470538,-99) , 
0, 231.845, 1, 0, 0.503295,-99)    );
  // itree = 22
  fBoostWeights.push_back(0.0253491);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.54776,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502704,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458203,-99) , 
1, 82.7668, 0, 0, 0.497272,-99) , 
3, 316.039, 0, 0, 0.50085,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.45289,-99) , 
1, 284.413, 1, 0, 0.497797,-99)    );
  // itree = 23
  fBoostWeights.push_back(0.0468997);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -2.97088, 1, 1, 0.522584,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506043,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.43531,-99) , 
1, 217.873, 0, 0, 0.469826,-99) , 
1, 169.92, 1, 0, 0.507383,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504145,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.443831,-99) , 
3, 58.9664, 0, 0, 0.496214,-99) , 
NN(
0, 
0, 
-1, -0.449884, 1, -1, 0.436815,-99) , 
2, 0.364156, 0, 0, 0.484369,-99) , 
2, -1.34632, 1, 0, 0.49361,-99)    );
  // itree = 24
  fBoostWeights.push_back(0.0480178);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522609,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483175,-99) , 
1, 105.988, 0, 0, 0.508726,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500255,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.439219,-99) , 
0, 130.194, 1, 0, 0.473629,-99) , 
1, 169.92, 1, 0, 0.498459,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506672,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476923,-99) , 
3, 172.158, 0, 0, 0.486834,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.409668,-99) , 
2, 0.178847, 0, 0, 0.478651,-99) , 
2, -0.747928, 1, 0, 0.487538,-99)    );
  // itree = 25
  fBoostWeights.push_back(0.0368763);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530256,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522002,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485124,-99) , 
1, 217.197, 0, 0, 0.488305,-99) , 
3, 316.039, 0, 0, 0.491266,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.453672,-99) , 
1, 284.413, 1, 0, 0.488873,-99)    );
  // itree = 26
  fBoostWeights.push_back(0.0447942);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524358,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49194,-99) , 
0, 95.2333, 0, 0, 0.517118,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511494,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459976,-99) , 
0, 122.633, 0, 0, 0.486308,-99) , 
1, 102.92, 0, 0, 0.503826,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506817,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472075,-99) , 
0, 132.675, 1, 0, 0.496329,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.423106,-99) , 
0, 232.832, 1, 0, 0.486238,-99) , 
1, 143.261, 1, 0, 0.495485,-99)    );
  // itree = 27
  fBoostWeights.push_back(0.0333547);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.533947,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507974,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476887,-99) , 
1, 102.92, 0, 0, 0.494638,-99) , 
2, -2.84215, 1, 0, 0.500196,-99) , 
NN(
0, 
0, 
-1, 232.832, 1, -1, 0.483941,-99) , 
1, 143.261, 1, 0, 0.492487,-99)    );
  // itree = 28
  fBoostWeights.push_back(0.0293763);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530198,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497052,-99) , 
2, -2.84228, 1, 0, 0.501591,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524402,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451658,-99) , 
1, 217.844, 0, 0, 0.480275,-99) , 
1, 176.868, 1, 0, 0.496963,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470481,-99) , 
1, 284.413, 1, 0, 0.495284,-99)    );
  // itree = 29
  fBoostWeights.push_back(0.0402834);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527454,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485022,-99) , 
0, 96.2547, 0, 0, 0.515243,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485617,-99) , 
0, 194.494, 1, 0, 0.509846,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523954,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492903,-99) , 
3, 173.534, 0, 0, 0.503321,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504412,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.430348,-99) , 
3, 127.922, 1, 0, 0.469002,-99) , 
2, -0.634142, 1, 0, 0.49405,-99) , 
2, 1.64562, 0, 0, 0.499978,-99)    );
  // itree = 30
  fBoostWeights.push_back(0.0268734);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 151.881, 0, 1, 0.507659,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51869,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460252,-99) , 
1, 217.844, 0, 0, 0.48324,-99) , 
1, 176.868, 1, 0, 0.502361,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477553,-99) , 
1, 284.413, 1, 0, 0.500792,-99)    );
  // itree = 31
  fBoostWeights.push_back(0.0329975);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515883,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482679,-99) , 
2, -1.88782, 1, 0, 0.508593,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524109,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465064,-99) , 
2, -2.34375, 0, 0, 0.489849,-99) , 
1, 169.92, 1, 0, 0.503124,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503483,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484108,-99) , 
2, 1.73092, 0, 0, 0.498441,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.430282,-99) , 
2, 0.178847, 0, 0, 0.491249,-99) , 
2, -0.747928, 1, 0, 0.496579,-99)    );
  // itree = 32
  fBoostWeights.push_back(0.0282905);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514289,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522735,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484191,-99) , 
3, 173.534, 0, 0, 0.497255,-99) , 
2, -1.65989, 0, 0, 0.500234,-99) , 
NN(
0, 
0, 
-1, 0.178847, 0, -1, 0.488577,-99) , 
2, -0.747928, 1, 0, 0.493808,-99)    );
  // itree = 33
  fBoostWeights.push_back(0.0275226);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507448,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.450363,-99) , 
0, 181.724, 1, 0, 0.503076,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505989,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.443558,-99) , 
0, 327.012, 0, 0, 0.477311,-99) , 
0, 231.845, 1, 0, 0.499619,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479383,-99) , 
1, 72.6849, 0, 0, 0.497994,-99)    );
  // itree = 34
  fBoostWeights.push_back(0.0247142);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511492,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488576,-99) , 
0, 108.541, 0, 0, 0.503533,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467787,-99) , 
3, 58.9664, 0, 0, 0.498879,-99) , 
NN(
0, 
0, 
-1, -0.576988, 1, -1, 0.489284,-99) , 
2, 0.448845, 0, 0, 0.493836,-99)    );
  // itree = 35
  fBoostWeights.push_back(0.0283063);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531998,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479894,-99) , 
3, 116.19, 0, 0, 0.511275,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508015,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458081,-99) , 
0, 81.5893, 0, 0, 0.495926,-99) , 
0, 126.671, 0, 0, 0.502871,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500026,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482656,-99) , 
0, 194.494, 1, 0, 0.496861,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.447269,-99) , 
2, 0.178847, 0, 0, 0.491648,-99) , 
2, -0.747928, 1, 0, 0.496685,-99)    );
  // itree = 36
  fBoostWeights.push_back(0.0268495);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520349,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511497,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482804,-99) , 
3, 127.317, 1, 0, 0.496943,-99) , 
2, -3.01326, 1, 0, 0.500005,-99) , 
NN(
0, 
0, 
-1, 0.406717, 0, -1, 0.488116,-99) , 
2, -0.448735, 1, 0, 0.493683,-99)    );
  // itree = 37
  fBoostWeights.push_back(0.00930189);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510193,-99) , 
NN(
0, 
0, 
-1, 72.6849, 0, -1, 0.495799,-99) , 
3, 316.039, 0, 0, 0.496879,-99)    );
  // itree = 38
  fBoostWeights.push_back(0.0462489);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.539789,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472637,-99) , 
3, 146.536, 0, 0, 0.507023,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515511,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46675,-99) , 
2, -2.5716, 0, 0, 0.505176,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515294,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469638,-99) , 
2, -1.71671, 1, 0, 0.490248,-99) , 
3, 127.317, 1, 0, 0.497582,-99) , 
2, 2.84239, 0, 0, 0.498856,-99)    );
  // itree = 39
  fBoostWeights.push_back(0.0196574);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516284,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498174,-99) , 
2, 2.50067, 1, 0, 0.506667,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470486,-99) , 
3, 58.9664, 0, 0, 0.501952,-99) , 
NN(
0, 
0, 
-1, -0.576988, 1, -1, 0.491531,-99) , 
2, 0.448845, 0, 0, 0.496478,-99)    );
  // itree = 40
  fBoostWeights.push_back(0.026528);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.533176,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489088,-99) , 
3, 146.536, 0, 0, 0.511668,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504866,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471961,-99) , 
2, -2.85654, 0, 0, 0.500614,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508433,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.441392,-99) , 
0, 107.502, 0, 0, 0.48937,-99) , 
3, 190.224, 1, 0, 0.497591,-99) , 
2, 2.84239, 0, 0, 0.499489,-99)    );
  // itree = 41
  fBoostWeights.push_back(0.0175702);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526568,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495719,-99) , 
3, 146.536, 0, 0, 0.511513,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501008,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479769,-99) , 
3, 58.8466, 0, 0, 0.498247,-99) , 
NN(
0, 
0, 
-1, 0.399968, 0, -1, 0.487525,-99) , 
2, -0.577044, 1, 0, 0.493224,-99) , 
2, 2.84239, 0, 0, 0.49569,-99)    );
  // itree = 42
  fBoostWeights.push_back(0.0151035);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 146.536, 0, 1, 0.511411,-99) , 
NN(
NN(
0, 
0, 
-1, -2.85654, 0, -1, 0.496316,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501308,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.447562,-99) , 
0, 107.502, 0, 0, 0.486036,-99) , 
3, 190.224, 1, 0, 0.493553,-99) , 
2, 2.84239, 0, 0, 0.495961,-99)    );
  // itree = 43
  fBoostWeights.push_back(0.0153022);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.50067, 1, 1, 0.506191,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477993,-99) , 
3, 58.9664, 0, 0, 0.502516,-99) , 
NN(
0, 
0, 
-1, -0.576988, 1, -1, 0.492893,-99) , 
2, 0.448845, 0, 0, 0.497461,-99)    );
  // itree = 44
  fBoostWeights.push_back(0.0267833);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509989,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496268,-99) , 
2, 1.432, 1, 0, 0.503769,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480692,-99) , 
2, -2.84228, 0, 0, 0.501016,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532059,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488212,-99) , 
2, -1.94473, 1, 0, 0.503829,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456165,-99) , 
0, 107.502, 0, 0, 0.490566,-99) , 
3, 190.224, 1, 0, 0.498128,-99)    );
  // itree = 45
  fBoostWeights.push_back(0.0219336);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528016,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508072,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483449,-99) , 
2, 2.47731, 0, 0, 0.503093,-99) , 
2, 2.14516, 1, 0, 0.507275,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514014,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494951,-99) , 
0, 151.682, 0, 0, 0.498224,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468793,-99) , 
0, 231.845, 1, 0, 0.494346,-99) , 
2, 1.64562, 0, 0, 0.499206,-99)    );
  // itree = 46
  fBoostWeights.push_back(0.0193235);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524646,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502421,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4838,-99) , 
2, -2.84228, 0, 0, 0.500265,-99) , 
3, 172.243, 0, 0, 0.502303,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528705,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493875,-99) , 
2, -1.94473, 1, 0, 0.506281,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465114,-99) , 
0, 107.502, 0, 0, 0.494837,-99) , 
3, 190.224, 1, 0, 0.50024,-99)    );
  // itree = 47
  fBoostWeights.push_back(0.00833869);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511613,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500376,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483809,-99) , 
0, 231.845, 1, 0, 0.498319,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481859,-99) , 
1, 72.6849, 0, 0, 0.497042,-99) , 
3, 316.039, 0, 0, 0.498134,-99)    );
  // itree = 48
  fBoostWeights.push_back(0.016561);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528919,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487281,-99) , 
2, -3.01327, 1, 0, 0.506451,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513628,-99) , 
NN(
0, 
0, 
-1, 171.671, 1, -1, 0.494039,-99) , 
0, 337.019, 0, 0, 0.495313,-99) , 
2, -2.84228, 1, 0, 0.49679,-99)    );
  // itree = 49
  fBoostWeights.push_back(0.0102527);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511878,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52805,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494489,-99) , 
3, 241.117, 1, 0, 0.508101,-99) , 
NN(
0, 
0, 
-1, 181.182, 1, -1, 0.497296,-99) , 
3, 211.152, 0, 0, 0.498992,-99) , 
3, 316.039, 0, 0, 0.499958,-99)    );
  // itree = 50
  fBoostWeights.push_back(0.0275976);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508337,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472998,-99) , 
0, 62.011, 0, 0, 0.505811,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459738,-99) , 
0, 191.739, 1, 0, 0.503074,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526678,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470004,-99) , 
2, 1.34653, 0, 0, 0.493885,-99) , 
0, 231.845, 1, 0, 0.501835,-99)    );
  // itree = 51
  fBoostWeights.push_back(0.0169544);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522799,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490139,-99) , 
2, -3.01327, 1, 0, 0.505165,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501435,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489084,-99) , 
3, 55.4209, 0, 0, 0.499252,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50749,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469353,-99) , 
2, 1.14681, 0, 0, 0.488321,-99) , 
3, 190.224, 1, 0, 0.496356,-99) , 
2, -2.84228, 1, 0, 0.497523,-99)    );
  // itree = 52
  fBoostWeights.push_back(0.0300751);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518568,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494377,-99) , 
2, -3.01327, 1, 0, 0.505505,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514353,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476833,-99) , 
0, 127.71, 1, 0, 0.49905,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502204,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463205,-99) , 
0, 107.502, 0, 0, 0.489766,-99) , 
3, 127.317, 1, 0, 0.494347,-99) , 
2, -2.84228, 1, 0, 0.495826,-99)    );
  // itree = 53
  fBoostWeights.push_back(0.0261448);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -2.98478, 1, 1, 0.506109,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506838,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484341,-99) , 
0, 127.71, 1, 0, 0.497663,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514232,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481561,-99) , 
1, 213.837, 0, 0, 0.487038,-99) , 
3, 127.317, 1, 0, 0.49228,-99) , 
2, -2.84228, 1, 0, 0.494113,-99)    );
  // itree = 54
  fBoostWeights.push_back(0.0406519);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 117.235, 1, 1, 0.510008,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.453893,-99) , 
1, 203.613, 1, 0, 0.499444,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53481,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515963,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47727,-99) , 
3, 65.0463, 1, 0, 0.484178,-99) , 
1, 219.178, 0, 0, 0.490658,-99) , 
0, 126.671, 0, 0, 0.494639,-99)    );
  // itree = 55
  fBoostWeights.push_back(0.0190395);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5136,-99) , 
NN(
0, 
0, 
-1, 75.8127, 0, -1, 0.493782,-99) , 
3, 304.061, 0, 0, 0.495789,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506962,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451825,-99) , 
0, 129.142, 1, 0, 0.485696,-99) , 
3, 64.4099, 0, 0, 0.494168,-99)    );
  // itree = 56
  fBoostWeights.push_back(0.0161291);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527454,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499022,-99) , 
2, -1.65983, 0, 0, 0.503606,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501779,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454788,-99) , 
2, 0.364019, 0, 0, 0.496255,-99) , 
2, -0.747845, 1, 0, 0.499585,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502202,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456545,-99) , 
0, 129.142, 1, 0, 0.484602,-99) , 
3, 64.4099, 0, 0, 0.497178,-99)    );
  // itree = 57
  fBoostWeights.push_back(0.019131);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511532,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493691,-99) , 
1, 169.92, 1, 0, 0.506338,-99) , 
NN(
0, 
0, 
-1, 0.364019, 0, -1, 0.49317,-99) , 
2, -0.747845, 1, 0, 0.499135,-99) , 
NN(
0, 
0, 
-1, 129.142, 1, -1, 0.483673,-99) , 
3, 64.4099, 0, 0, 0.496652,-99)    );
  // itree = 58
  fBoostWeights.push_back(0.018698);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514703,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487133,-99) , 
3, 118.777, 0, 0, 0.506311,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502873,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487983,-99) , 
2, 0.32123, 0, 0, 0.49842,-99) , 
2, -2.24378, 1, 0, 0.500846,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502953,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465306,-99) , 
0, 129.142, 1, 0, 0.488452,-99) , 
3, 64.4099, 0, 0, 0.498856,-99)    );
  // itree = 59
  fBoostWeights.push_back(0.016231);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522899,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505287,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490132,-99) , 
3, 116.19, 0, 0, 0.499131,-99) , 
2, -1.2183, 0, 0, 0.502078,-99) , 
NN(
0, 
0, 
-1, 0.406717, 0, -1, 0.492753,-99) , 
2, -0.448735, 1, 0, 0.49712,-99)    );
  // itree = 60
  fBoostWeights.push_back(0.0181731);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50738,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491547,-99) , 
3, 184.238, 1, 0, 0.501876,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504521,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468815,-99) , 
2, 2.74274, 0, 0, 0.495243,-99) , 
2, 2.54321, 1, 0, 0.500249,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501702,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473327,-99) , 
0, 129.142, 1, 0, 0.49078,-99) , 
3, 64.4099, 0, 0, 0.498729,-99)    );
  // itree = 61
  fBoostWeights.push_back(0.00928129);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511034,-99) , 
NN(
0, 
0, 
-1, 75.8127, 0, -1, 0.497276,-99) , 
3, 304.061, 0, 0, 0.498669,-99) , 
NN(
0, 
0, 
-1, 1.04719, 1, -1, 0.489733,-99) , 
3, 64.4099, 0, 0, 0.497234,-99)    );
  // itree = 62
  fBoostWeights.push_back(0.0185788);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517582,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498349,-99) , 
1, 154.462, 0, 0, 0.502733,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513353,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454703,-99) , 
1, 217.208, 0, 0, 0.485896,-99) , 
1, 190.311, 1, 0, 0.500005,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486631,-99) , 
1, 284.413, 1, 0, 0.49916,-99)    );
  // itree = 63
  fBoostWeights.push_back(0.0162759);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511147,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498878,-99) , 
1, 134.412, 1, 0, 0.50458,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51804,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488286,-99) , 
3, 198.233, 0, 0, 0.49738,-99) , 
2, 2.54321, 1, 0, 0.502815,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503553,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479002,-99) , 
2, 1.04719, 1, 0, 0.493958,-99) , 
3, 64.4099, 0, 0, 0.501393,-99)    );
  // itree = 64
  fBoostWeights.push_back(0.0125443);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.18934, 0, 1, 0.504867,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505723,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479678,-99) , 
2, 2.74274, 0, 0, 0.498961,-99) , 
2, 2.54321, 1, 0, 0.503419,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500591,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48103,-99) , 
0, 129.142, 1, 0, 0.493068,-99) , 
3, 64.4099, 0, 0, 0.501758,-99)    );
  // itree = 65
  fBoostWeights.push_back(0.0140452);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510087,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497764,-99) , 
2, 2.50067, 1, 0, 0.503499,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502709,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467822,-99) , 
2, -0.747909, 1, 0, 0.498102,-99) , 
2, 0.448903, 0, 0, 0.500683,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504461,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485066,-99) , 
3, 37.4399, 1, 0, 0.492343,-99) , 
3, 64.4099, 0, 0, 0.499344,-99)    );
  // itree = 66
  fBoostWeights.push_back(0.0146365);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523783,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499018,-99) , 
2, 2.5722, 1, 0, 0.508869,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508076,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47408,-99) , 
2, 2.57194, 0, 0, 0.494095,-99) , 
1, 152.953, 1, 0, 0.503143,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500025,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482684,-99) , 
3, 253.132, 1, 0, 0.497454,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47888,-99) , 
2, 0.961434, 1, 0, 0.495621,-99) , 
2, 1.64562, 0, 0, 0.49845,-99)    );
  // itree = 67
  fBoostWeights.push_back(0.0206789);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 145.049, 0, 1, 0.509619,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504417,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477731,-99) , 
2, 2.57194, 0, 0, 0.493444,-99) , 
1, 152.953, 1, 0, 0.50335,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511987,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491789,-99) , 
1, 200.563, 0, 0, 0.495605,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48083,-99) , 
0, 231.845, 1, 0, 0.493662,-99) , 
2, 1.64562, 0, 0, 0.497305,-99)    );
  // itree = 68
  fBoostWeights.push_back(0.0141599);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521647,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499159,-99) , 
0, 223.769, 0, 0, 0.502231,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503616,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456568,-99) , 
1, 217.208, 0, 0, 0.48158,-99) , 
1, 190.311, 1, 0, 0.498888,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48716,-99) , 
1, 284.413, 1, 0, 0.498147,-99)    );
  // itree = 69
  fBoostWeights.push_back(0.013204);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 151.142, 0, 1, 0.503299,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471001,-99) , 
0, 191.739, 1, 0, 0.501385,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514016,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479008,-99) , 
2, 1.34653, 0, 0, 0.493742,-99) , 
0, 231.845, 1, 0, 0.500357,-99)    );
  // itree = 70
  fBoostWeights.push_back(0.0164677);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504223,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4784,-99) , 
1, 64.8422, 0, 0, 0.502317,-99) , 
NN(
0, 
0, 
-1, 208.247, 0, -1, 0.478987,-99) , 
1, 190.311, 1, 0, 0.49854,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488534,-99) , 
1, 284.413, 1, 0, 0.497909,-99)    );
  // itree = 71
  fBoostWeights.push_back(0.0108977);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508744,-99) , 
NN(
0, 
0, 
-1, 75.8127, 0, -1, 0.495876,-99) , 
3, 304.061, 0, 0, 0.497178,-99) , 
NN(
0, 
0, 
-1, 1.04719, 1, -1, 0.490068,-99) , 
3, 64.4099, 0, 0, 0.496037,-99)    );
  // itree = 72
  fBoostWeights.push_back(0.0144392);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527375,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498009,-99) , 
2, -0.732555, 1, 0, 0.501436,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505616,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480813,-99) , 
2, -2.57164, 1, 0, 0.495976,-99) , 
2, -1.64541, 0, 0, 0.499351,-99) , 
NN(
0, 
0, 
-1, 1.04719, 1, -1, 0.492792,-99) , 
3, 64.4099, 0, 0, 0.498298,-99)    );
  // itree = 73
  fBoostWeights.push_back(0.0170808);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514723,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51077,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49497,-99) , 
3, 172.158, 0, 0, 0.500216,-99) , 
2, 1.43291, 1, 0, 0.503169,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507148,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493493,-99) , 
0, 126.671, 0, 0, 0.499662,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480645,-99) , 
2, -0.947473, 1, 0, 0.496995,-99) , 
2, 0.149652, 0, 0, 0.500056,-99)    );
  // itree = 74
  fBoostWeights.push_back(0.0177911);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520496,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506458,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487851,-99) , 
3, 97.4893, 0, 0, 0.501219,-99) , 
2, 2.14516, 1, 0, 0.504455,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506809,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492875,-99) , 
1, 134.412, 0, 0, 0.500569,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484009,-99) , 
0, 231.845, 1, 0, 0.498392,-99) , 
2, 1.64562, 0, 0, 0.500672,-99)    );
  // itree = 75
  fBoostWeights.push_back(0.0224086);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 96.2718, 1, 1, 0.505964,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501698,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467698,-99) , 
1, 173.072, 1, 0, 0.492898,-99) , 
2, -1.64551, 0, 0, 0.501109,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525228,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50746,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456364,-99) , 
1, 136.423, 1, 0, 0.489262,-99) , 
1, 203.613, 0, 0, 0.496723,-99) , 
3, 190.224, 1, 0, 0.499896,-99)    );
  // itree = 76
  fBoostWeights.push_back(0.0121854);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502364,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493822,-99) , 
3, 127.317, 1, 0, 0.498001,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470438,-99) , 
1, 230.64, 1, 0, 0.496382,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489496,-99) , 
1, 284.413, 1, 0, 0.495947,-99)    );
  // itree = 77
  fBoostWeights.push_back(0.0136395);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515898,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496116,-99) , 
1, 213.837, 0, 0, 0.499483,-99) , 
NN(
0, 
0, 
-1, 173.944, 1, -1, 0.493497,-99) , 
3, 124.327, 0, 0, 0.497333,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502339,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484974,-99) , 
2, -1.34633, 1, 0, 0.491302,-99) , 
3, 64.4099, 0, 0, 0.496365,-99)    );
  // itree = 78
  fBoostWeights.push_back(0.0122414);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532985,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497675,-99) , 
1, 219.178, 0, 0, 0.502399,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501743,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479788,-99) , 
1, 203.613, 1, 0, 0.497642,-99) , 
0, 122.633, 1, 0, 0.499999,-99) , 
NN(
0, 
0, 
-1, 129.142, 1, -1, 0.492226,-99) , 
3, 64.4099, 0, 0, 0.498752,-99)    );
  // itree = 79
  fBoostWeights.push_back(0.0171622);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518311,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497595,-99) , 
0, 90.1605, 1, 0, 0.502393,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473583,-99) , 
0, 181.725, 1, 0, 0.500182,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510288,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482299,-99) , 
2, 1.34653, 0, 0, 0.49409,-99) , 
0, 231.845, 1, 0, 0.499363,-99)    );
  // itree = 80
  fBoostWeights.push_back(0.0132142);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 151.195, 0, 1, 0.504697,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477863,-99) , 
0, 181.725, 1, 0, 0.502638,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505999,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486585,-99) , 
2, 1.34653, 0, 0, 0.494764,-99) , 
0, 231.845, 1, 0, 0.50158,-99)    );
  // itree = 81
  fBoostWeights.push_back(0.0115518);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503707,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493829,-99) , 
1, 165.345, 1, 0, 0.501389,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473267,-99) , 
1, 230.64, 1, 0, 0.499739,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491655,-99) , 
1, 284.413, 1, 0, 0.499229,-99)    );
  // itree = 82
  fBoostWeights.push_back(0.0177858);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508452,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479117,-99) , 
0, 194.494, 1, 0, 0.502637,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505501,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490194,-99) , 
3, 184.269, 0, 0, 0.495797,-99) , 
1, 143.261, 0, 0, 0.498987,-99) , 
NN(
0, 
0, 
-1, -0.747955, 0, -1, 0.494197,-99) , 
3, 64.4099, 0, 0, 0.498218,-99)    );
  // itree = 83
  fBoostWeights.push_back(0.0150113);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51972,-99) , 
NN(
0, 
0, 
-1, -2.84228, 0, -1, 0.497783,-99) , 
3, 172.243, 0, 0, 0.499619,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523086,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503538,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46757,-99) , 
1, 126.829, 1, 0, 0.487971,-99) , 
1, 203.613, 0, 0, 0.495262,-99) , 
3, 190.224, 1, 0, 0.498415,-99)    );
  // itree = 84
  fBoostWeights.push_back(0.0172834);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -0.276542, 1, 1, 0.506656,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501799,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479839,-99) , 
1, 173.072, 1, 0, 0.49613,-99) , 
2, -1.64551, 0, 0, 0.502744,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51934,-99) , 
NN(
0, 
0, 
-1, 126.829, 1, -1, 0.487464,-99) , 
1, 203.613, 0, 0, 0.494082,-99) , 
3, 190.224, 1, 0, 0.500349,-99)    );
  // itree = 85
  fBoostWeights.push_back(0.0127596);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50469,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494654,-99) , 
1, 121.815, 0, 0, 0.500598,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474248,-99) , 
1, 230.64, 1, 0, 0.499052,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490627,-99) , 
1, 284.413, 1, 0, 0.498521,-99)    );
  // itree = 86
  fBoostWeights.push_back(0.0168166);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512063,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496928,-99) , 
2, -1.65988, 0, 0, 0.501665,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491626,-99) , 
3, 253.132, 1, 0, 0.500182,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504983,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470472,-99) , 
1, 172.969, 1, 0, 0.499027,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476426,-99) , 
1, 223.02, 1, 0, 0.496187,-99) , 
2, 0.748039, 1, 0, 0.498378,-99)    );
  // itree = 87
  fBoostWeights.push_back(0.0227117);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -2.80036, 1, 1, 0.508431,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509004,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47927,-99) , 
2, -2.7144, 0, 0, 0.498033,-99) , 
3, 116.19, 0, 0, 0.504215,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519552,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484828,-99) , 
0, 88.0622, 1, 0, 0.502069,-99) , 
NN(
0, 
0, 
-1, 203.613, 1, -1, 0.490927,-99) , 
0, 108.541, 1, 0, 0.494844,-99) , 
2, -1.34632, 1, 0, 0.498605,-99)    );
  // itree = 88
  fBoostWeights.push_back(0.0285183);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514536,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49128,-99) , 
3, 172.512, 1, 0, 0.506164,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483178,-99) , 
1, 203.613, 1, 0, 0.501869,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540861,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4936,-99) , 
0, 90.8975, 1, 0, 0.502356,-99) , 
NN(
0, 
0, 
-1, -0.150257, 0, -1, 0.475766,-99) , 
0, 76.5857, 0, 0, 0.497031,-99) , 
0, 126.671, 0, 0, 0.49922,-99)    );
  // itree = 89
  fBoostWeights.push_back(0.0151218);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521779,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486573,-99) , 
2, 1.34594, 1, 0, 0.508729,-99) , 
NN(
NN(
0, 
0, 
-1, 223.769, 0, 1, 0.503455,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476057,-99) , 
1, 183.56, 1, 0, 0.50061,-99) , 
1, 213.837, 0, 0, 0.501836,-99)    );
  // itree = 90
  fBoostWeights.push_back(0.0150457);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518004,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490351,-99) , 
2, 1.34594, 1, 0, 0.507754,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515644,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497153,-99) , 
0, 223.769, 0, 0, 0.499674,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47983,-99) , 
1, 183.56, 1, 0, 0.497614,-99) , 
1, 213.837, 0, 0, 0.499145,-99)    );
  // itree = 91
  fBoostWeights.push_back(0.0159746);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 113.738, 1, 1, 0.518131,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523299,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496514,-99) , 
3, 253.132, 0, 0, 0.499758,-99) , 
1, 213.837, 0, 0, 0.502408,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506089,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486896,-99) , 
2, 1.34653, 0, 0, 0.494977,-99) , 
0, 231.845, 1, 0, 0.501411,-99)    );
  // itree = 92
  fBoostWeights.push_back(0.0146655);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 150.228, 0, 1, 0.506319,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487386,-99) , 
0, 171.711, 1, 0, 0.504423,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50723,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488654,-99) , 
2, -1.64512, 1, 0, 0.495607,-99) , 
0, 231.845, 1, 0, 0.50324,-99)    );
  // itree = 93
  fBoostWeights.push_back(0.00943359);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.84239, 0, 1, 0.503023,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479702,-99) , 
0, 61.5542, 0, 0, 0.501491,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505762,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48981,-99) , 
2, 1.34653, 0, 0, 0.496528,-99) , 
0, 231.845, 1, 0, 0.500825,-99)    );
  // itree = 94
  fBoostWeights.push_back(0.0122361);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508923,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496823,-99) , 
2, 2.50067, 1, 0, 0.502495,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487917,-99) , 
3, 58.9664, 0, 0, 0.500604,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502309,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482748,-99) , 
1, 225.857, 1, 0, 0.499887,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48732,-99) , 
2, -0.918919, 1, 0, 0.497743,-99) , 
2, 0.448845, 0, 0, 0.499101,-99)    );
  // itree = 95
  fBoostWeights.push_back(0.0144215);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513045,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505153,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478956,-99) , 
2, 2.47731, 0, 0, 0.499857,-99) , 
2, 2.14516, 1, 0, 0.502067,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507488,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49562,-99) , 
1, 200.563, 0, 0, 0.497917,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484262,-99) , 
2, 0.961434, 1, 0, 0.496573,-99) , 
2, 1.64562, 0, 0, 0.49864,-99)    );
  // itree = 96
  fBoostWeights.push_back(0.0102597);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50787,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497937,-99) , 
1, 154.463, 0, 0, 0.501037,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475857,-99) , 
1, 230.64, 1, 0, 0.499564,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493844,-99) , 
1, 284.413, 1, 0, 0.499204,-99)    );
  // itree = 97
  fBoostWeights.push_back(0.0209201);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 108.146, 0, 1, 0.509045,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504797,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478475,-99) , 
1, 116.361, 1, 0, 0.494733,-99) , 
0, 122.633, 1, 0, 0.501869,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506496,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477174,-99) , 
3, 229.105, 1, 0, 0.501975,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477515,-99) , 
0, 232.832, 1, 0, 0.498671,-99) , 
1, 143.261, 1, 0, 0.500357,-99)    );
  // itree = 98
  fBoostWeights.push_back(0.0128872);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505396,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513922,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495875,-99) , 
2, 2.84239, 0, 0, 0.498305,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48049,-99) , 
0, 66.5493, 0, 0, 0.496945,-99) , 
0, 337.019, 0, 0, 0.497511,-99)    );
  // itree = 99
  fBoostWeights.push_back(0.0102775);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51549,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510138,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498379,-99) , 
2, -2.99159, 1, 0, 0.500036,-99) , 
2, 0.00691083, 0, 0, 0.501511,-99) , 
NN(
NN(
0, 
0, 
-1, 2.79961, 0, 1, 0.505489,-99) , 
NN(
0, 
0, 
-1, 1.66038, 0, -1, 0.493017,-99) , 
3, 172.158, 0, 0, 0.497175,-99) , 
2, 0.748039, 1, 0, 0.499553,-99)    );
   return;
};
 
// Clean up
inline void ReadBDT::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDT::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
