// Class: ReadBDT
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.06/01       [394753]
Creator        : kskovpen
Date           : Tue Jan 10 22:38:51 2017
Host           : Linux vocms0315.cern.ch 2.6.32-573.26.1.el6.x86_64 #1 SMP Wed May 4 09:23:05 CEST 2016 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /storage_mnt/storage/user/kskovpen/analysis/tHFCNC/CMSSW_8_0_12/src/TopKinFit/test/Validation/TopHLepbb/MVA
Training events: 61171
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "100" [Number of trees in the forest]
MaxDepth: "3" [Max depth of the decision tree allowed]
nCuts: "20" [Number of grid points in variable range used in finding optimal cut in node splitting]
SeparationType: "giniindex" [Separation criterion for node splitting]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
MinNodeSize: "5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
BoostType: "AdaBoost" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
UseBaggedBoost: "False" [Use only a random subsample of all events for growing the trees in each boost iteration.]
Shrinkage: "1.000000e+00" [Learning rate for GradBoost algorithm]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "2" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split with RandomisedTree option]
BaggedSampleFraction: "6.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "inverseboostnegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "6.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 4
HiggsRecMTruth                HiggsRecMTruth                HiggsRecMTruth                HiggsRecMTruth                                                  'F'    [19.1486473083,2332.8527832]
TopLepRecMTTruth              TopLepRecMTTruth              TopLepRecMTTruth              TopLepRecMTTruth                                                'F'    [5.84698343277,1708.35217285]
HiggsTopLepRecDphiTTruth      HiggsTopLepRecDphiTTruth      HiggsTopLepRecDphiTTruth      HiggsTopLepRecDphiTTruth                                        'F'    [-3.14150643349,3.14158296585]
TopLepRecPtTTruth             TopLepRecPtTTruth             TopLepRecPtTTruth             TopLepRecPtTTruth                                               'F'    [0.109748572111,2310.08178711]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDTNode
   
#ifndef BDTNode__def
#define BDTNode__def
   
class BDTNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDTNode ( BDTNode* left,BDTNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTNode();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTNode* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTNode*   fLeft;     // pointer to the left daughter node
   BDTNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDTNode::~BDTNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDTNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDTNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT : public IClassifierReader {

 public:

   // constructor
   ReadBDT( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDT" ),
        fNvars( 4 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "HiggsRecMTruth", "TopLepRecMTTruth", "HiggsTopLepRecDphiTTruth", "TopLepRecPtTTruth" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[4];
   double fVmax[4];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[4];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTNode*)current->GetRight();
         else current=(BDTNode*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
};

void ReadBDT::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(0.704859274376328);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.762441,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.343966,-99) , 
1, 190.034, 1, 0, 0.686319,-99) , 
NN(
0, 
0, 
-1, 167.99, 1, -1, 0.0868353,-99) , 
0, 155.548, 1, 0, 0.580605,-99) , 
NN(
0, 
0, 
-1, 185.115, 1, -1, 0.00998598,-99) , 
0, 239.501, 1, 0, 0.5,-99)    );
  // itree = 1
  fBoostWeights.push_back(0.510159);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.677155,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.301402,-99) , 
0, 85.0991, 0, 0, 0.609558,-99) , 
NN(
0, 
0, 
-1, 167.539, 1, -1, 0.22043,-99) , 
0, 145.055, 1, 0, 0.526693,-99) , 
NN(
0, 
0, 
-1, 185.115, 1, -1, 0.0200028,-99) , 
0, 239.501, 1, 0, 0.466483,-99)    );
  // itree = 2
  fBoostWeights.push_back(0.332604);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.94473, 0, 1, 0.742603,-99) , 
NN(
0, 
0, 
-1, 166.04, 1, -1, 0.41083,-99) , 
3, 220.107, 0, 0, 0.489293,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0328781,-99) , 
0, 239.501, 1, 0, 0.442574,-99)    );
  // itree = 3
  fBoostWeights.push_back(0.335468);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.649676,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.44696,-99) , 
3, 110.108, 0, 0, 0.573095,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.208627,-99) , 
0, 166.04, 1, 0, 0.534126,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0452644,-99) , 
0, 239.501, 1, 0, 0.489426,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.268793);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.578838,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.328861,-99) , 
0, 166.027, 1, 0, 0.556534,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.237462,-99) , 
1, 249.062, 1, 0, 0.526013,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0621846,-99) , 
0, 239.501, 1, 0, 0.487967,-99)    );
  // itree = 5
  fBoostWeights.push_back(0.160985);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520712,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.294902,-99) , 
0, 71.6051, 0, 0, 0.501696,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.289492,-99) , 
1, 249.062, 1, 0, 0.482283,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0798304,-99) , 
0, 239.501, 1, 0, 0.452074,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.192121);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.565441,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.442884,-99) , 
3, 220.107, 0, 0, 0.469017,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.233095,-99) , 
0, 187.024, 1, 0, 0.455241,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0924845,-99) , 
0, 239.501, 1, 0, 0.42952,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.157884);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.561576,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462617,-99) , 
2, 1.9448, 0, 0, 0.496439,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.269178,-99) , 
0, 187.024, 1, 0, 0.483674,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.109921,-99) , 
0, 239.501, 1, 0, 0.458789,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.1702);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 182.916, 0, 1, 0.580617,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509542,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.36742,-99) , 
2, 1.20397, 0, 0, 0.455162,-99) , 
2, -1.94473, 1, 0, 0.49763,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.126346,-99) , 
0, 239.501, 1, 0, 0.474139,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.16707);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.703141,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476454,-99) , 
3, 180.591, 0, 0, 0.535655,-99) , 
NN(
0, 
0, 
-1, 134.563, 1, -1, 0.437821,-99) , 
2, -1.34634, 1, 0, 0.47641,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.146357,-99) , 
0, 239.501, 1, 0, 0.456569,-99)    );
  // itree = 10
  fBoostWeights.push_back(0.177878);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.597491,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457139,-99) , 
0, 101.587, 0, 0, 0.539807,-99) , 
NN(
0, 
0, 
-1, 167.99, 1, -1, 0.431567,-99) , 
0, 134.563, 1, 0, 0.509601,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.168486,-99) , 
0, 239.501, 1, 0, 0.490033,-99)    );
  // itree = 11
  fBoostWeights.push_back(0.101661);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -2.84227, 1, 1, 0.528642,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.386493,-99) , 
1, 249.062, 1, 0, 0.5165,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.194894,-99) , 
0, 239.501, 1, 0, 0.498862,-99)    );
  // itree = 12
  fBoostWeights.push_back(0.0916118);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.683293,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487373,-99) , 
3, 134.68, 0, 0, 0.586639,-99) , 
NN(
0, 
0, 
-1, 176.532, 1, -1, 0.479649,-99) , 
2, -2.84231, 1, 0, 0.495428,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.211342,-99) , 
0, 239.501, 1, 0, 0.480252,-99)    );
  // itree = 13
  fBoostWeights.push_back(0.098391);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.566351,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495037,-99) , 
2, -1.04715, 1, 0, 0.524879,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.383194,-99) , 
0, 176.532, 1, 0, 0.514938,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.227015,-99) , 
0, 239.501, 1, 0, 0.499901,-99)    );
  // itree = 14
  fBoostWeights.push_back(0.112834);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538839,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.42645,-99) , 
0, 71.6078, 0, 0, 0.528974,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.406701,-99) , 
0, 176.532, 1, 0, 0.520463,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.244743,-99) , 
0, 239.501, 1, 0, 0.506382,-99)    );
  // itree = 15
  fBoostWeights.push_back(0.112258);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.636558,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.547647,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462099,-99) , 
3, 156.052, 0, 0, 0.489502,-99) , 
3, 327.649, 0, 0, 0.501107,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.373505,-99) , 
1, 249.062, 1, 0, 0.489102,-99)    );
  // itree = 16
  fBoostWeights.push_back(0.133217);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.94491, 1, 1, 0.564212,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.607176,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471394,-99) , 
2, 2.84238, 0, 0, 0.495124,-99) , 
3, 110.108, 1, 0, 0.523566,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.649754,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482405,-99) , 
3, 219.837, 0, 0, 0.521785,-99) , 
NN(
0, 
0, 
-1, -1.04715, 1, -1, 0.326049,-99) , 
1, 167.99, 1, 0, 0.454871,-99) , 
0, 129.325, 1, 0, 0.49813,-99)    );
  // itree = 17
  fBoostWeights.push_back(0.123612);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.562299,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491293,-99) , 
0, 89.5148, 0, 0, 0.550526,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526154,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.412548,-99) , 
3, 174.13, 0, 0, 0.462345,-99) , 
1, 98.5002, 0, 0, 0.526572,-99) , 
NN(
NN(
0, 
0, 
-1, -1.34626, 1, 1, 0.530534,-99) , 
NN(
0, 
0, 
-1, -1.04715, 1, -1, 0.355971,-99) , 
0, 129.325, 1, 0, 0.463174,-99) , 
1, 167.99, 1, 0, 0.506076,-99)    );
  // itree = 18
  fBoostWeights.push_back(0.0522697);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.598438,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504885,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.453054,-99) , 
1, 98.4921, 0, 0, 0.494804,-99) , 
3, 327.649, 0, 0, 0.502794,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.409359,-99) , 
1, 249.062, 1, 0, 0.494287,-99)    );
  // itree = 19
  fBoostWeights.push_back(0.0858691);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.608417,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534915,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478632,-99) , 
3, 156.052, 0, 0, 0.497108,-99) , 
3, 327.649, 0, 0, 0.505908,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532558,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470455,-99) , 
2, -1.34626, 1, 0, 0.493296,-99) , 
NN(
0, 
0, 
-1, -1.04715, 1, -1, 0.379926,-99) , 
0, 129.325, 1, 0, 0.450011,-99) , 
1, 167.99, 1, 0, 0.487848,-99)    );
  // itree = 20
  fBoostWeights.push_back(0.089327);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.576095,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.544141,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473771,-99) , 
2, 2.28676, 0, 0, 0.4992,-99) , 
2, -2.84227, 1, 0, 0.511028,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535018,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475999,-99) , 
2, 1.34637, 0, 0, 0.498966,-99) , 
NN(
0, 
0, 
-1, -1.04715, 1, -1, 0.400353,-99) , 
0, 129.325, 1, 0, 0.461495,-99) , 
1, 167.99, 1, 0, 0.495055,-99)    );
  // itree = 21
  fBoostWeights.push_back(0.077227);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.633371,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.533278,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499175,-99) , 
3, 137.592, 0, 0, 0.511137,-99) , 
3, 240.751, 0, 0, 0.526206,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.601771,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487181,-99) , 
3, 215.211, 0, 0, 0.507611,-99) , 
NN(
0, 
0, 
-1, 220.4, 1, -1, 0.393179,-99) , 
2, 0.748059, 0, 0, 0.481219,-99) , 
2, -1.04714, 1, 0, 0.5,-99)    );
  // itree = 22
  fBoostWeights.push_back(0.0722653);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 156.225, 1, 1, 0.541784,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50042,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.434374,-99) , 
1, 67.9831, 0, 0, 0.483711,-99) , 
1, 106.221, 0, 0, 0.521937,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538518,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489547,-99) , 
0, 103.092, 1, 0, 0.51469,-99) , 
NN(
0, 
0, 
-1, -1.04715, 1, -1, 0.429878,-99) , 
0, 129.325, 1, 0, 0.482706,-99) , 
1, 167.99, 1, 0, 0.5093,-99)    );
  // itree = 23
  fBoostWeights.push_back(0.10189);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.608068,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504445,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462983,-99) , 
3, 81.6853, 0, 0, 0.490345,-99) , 
3, 153.678, 0, 0, 0.532146,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521242,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475869,-99) , 
0, 129.325, 1, 0, 0.505339,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.652028,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.336934,-99) , 
2, 1.5177, 0, 0, 0.441929,-99) , 
3, 220.107, 1, 0, 0.491816,-99) , 
2, -2.54312, 1, 0, 0.501275,-99)    );
  // itree = 24
  fBoostWeights.push_back(0.0470784);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.564471,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532289,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489903,-99) , 
3, 167.723, 0, 0, 0.496891,-99) , 
NN(
0, 
0, 
-1, 256.773, 0, -1, 0.436118,-99) , 
3, 220.102, 1, 0, 0.489062,-99) , 
3, 330.106, 0, 0, 0.4947,-99)    );
  // itree = 25
  fBoostWeights.push_back(0.0697396);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.614606,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52426,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492582,-99) , 
3, 103.221, 1, 0, 0.506473,-99) , 
3, 240.751, 0, 0, 0.5195,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.544891,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487148,-99) , 
3, 143.688, 0, 0, 0.510484,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504722,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.285674,-99) , 
3, 220.4, 1, 0, 0.415324,-99) , 
2, 0.748059, 0, 0, 0.488712,-99) , 
2, -1.04714, 1, 0, 0.501582,-99)    );
  // itree = 26
  fBoostWeights.push_back(0.054336);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.597961,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515943,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498839,-99) , 
2, -2.74278, 0, 0, 0.508625,-99) , 
3, 240.751, 0, 0, 0.519323,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.541135,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498712,-99) , 
0, 129.325, 0, 0, 0.51385,-99) , 
NN(
0, 
0, 
-1, 220.4, 1, -1, 0.411565,-99) , 
2, 0.748059, 0, 0, 0.49053,-99) , 
2, -1.04714, 1, 0, 0.502572,-99)    );
  // itree = 27
  fBoostWeights.push_back(0.0791427);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.591989,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507392,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48692,-99) , 
3, 88.8841, 0, 0, 0.499231,-99) , 
3, 153.678, 0, 0, 0.531811,-99) , 
NN(
NN(
0, 
0, 
-1, 94.3922, 0, 1, 0.526422,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52441,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.426096,-99) , 
2, 1.51741, 0, 0, 0.474787,-99) , 
3, 110.108, 1, 0, 0.496419,-99) , 
2, -2.54312, 1, 0, 0.504725,-99)    );
  // itree = 28
  fBoostWeights.push_back(0.0471095);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.559649,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510116,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474306,-99) , 
2, 2.244, 1, 0, 0.498629,-99) , 
NN(
0, 
0, 
-1, 256.773, 0, -1, 0.440749,-99) , 
3, 220.102, 1, 0, 0.491272,-99) , 
3, 330.106, 0, 0, 0.496216,-99)    );
  // itree = 29
  fBoostWeights.push_back(0.0272116);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.548008,-99) , 
NN(
0, 
0, 
-1, 220.102, 1, -1, 0.489074,-99) , 
3, 330.106, 0, 0, 0.493327,-99)    );
  // itree = 30
  fBoostWeights.push_back(0.041349);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.564798,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509387,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469735,-99) , 
1, 110.073, 0, 0, 0.498419,-99) , 
3, 327.649, 0, 0, 0.503088,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458726,-99) , 
1, 249.062, 1, 0, 0.499148,-99)    );
  // itree = 31
  fBoostWeights.push_back(0.0595978);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.574964,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462253,-99) , 
3, 124.877, 0, 0, 0.525041,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505365,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486653,-99) , 
0, 129.325, 1, 0, 0.498744,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.572672,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.398282,-99) , 
2, -1.43184, 1, 0, 0.455063,-99) , 
3, 220.107, 1, 0, 0.490203,-99) , 
2, 2.84239, 0, 0, 0.495488,-99)    );
  // itree = 32
  fBoostWeights.push_back(0.033416);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540035,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524642,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491117,-99) , 
3, 188.674, 0, 0, 0.494017,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505157,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.406756,-99) , 
3, 256.773, 0, 0, 0.458252,-99) , 
3, 220.102, 1, 0, 0.489499,-99) , 
3, 330.106, 0, 0, 0.493107,-99)    );
  // itree = 33
  fBoostWeights.push_back(0.0489628);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.563326,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485438,-99) , 
3, 124.877, 0, 0, 0.528738,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505362,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485789,-99) , 
3, 157.247, 1, 0, 0.501347,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.556423,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.408317,-99) , 
2, -1.43184, 1, 0, 0.456433,-99) , 
3, 220.107, 1, 0, 0.492605,-99) , 
2, 2.84239, 0, 0, 0.498068,-99)    );
  // itree = 34
  fBoostWeights.push_back(0.0404571);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.552194,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493665,-99) , 
2, 2.98488, 0, 0, 0.527425,-99) , 
NN(
NN(
0, 
0, 
-1, 42.013, 0, -1, 0.494127,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.544307,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.420198,-99) , 
2, -1.43184, 1, 0, 0.460564,-99) , 
3, 220.107, 1, 0, 0.487613,-99) , 
2, 2.84239, 0, 0, 0.493628,-99)    );
  // itree = 35
  fBoostWeights.push_back(0.050459);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.562076,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.54595,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497334,-99) , 
2, 1.77405, 1, 0, 0.505609,-99) , 
3, 215.211, 0, 0, 0.515222,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513401,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.445961,-99) , 
1, 224.145, 1, 0, 0.505141,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.410486,-99) , 
2, -0.548611, 1, 0, 0.489185,-99) , 
2, 0.748025, 0, 0, 0.500895,-99)    );
  // itree = 36
  fBoostWeights.push_back(0.0502857);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 3.02762, 0, 1, 0.527209,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492037,-99) , 
3, 72.1638, 0, 0, 0.519996,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509196,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469917,-99) , 
0, 106.233, 0, 0, 0.495615,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.422749,-99) , 
2, -0.548611, 1, 0, 0.483368,-99) , 
2, 0.748025, 0, 0, 0.499847,-99)    );
  // itree = 37
  fBoostWeights.push_back(0.0594067);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.592897,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518751,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486293,-99) , 
3, 113.034, 1, 0, 0.503107,-99) , 
3, 215.211, 0, 0, 0.515787,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519728,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48525,-99) , 
2, -1.54602, 0, 0, 0.496932,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529969,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.385315,-99) , 
2, -1.54604, 1, 0, 0.438143,-99) , 
3, 220.107, 1, 0, 0.484058,-99) , 
2, 1.64561, 0, 0, 0.495894,-99)    );
  // itree = 38
  fBoostWeights.push_back(0.0404207);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.578483,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.543396,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493807,-99) , 
3, 164.122, 0, 0, 0.502574,-99) , 
3, 215.211, 0, 0, 0.513252,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50567,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473665,-99) , 
1, 224.145, 1, 0, 0.50172,-99) , 
NN(
0, 
0, 
-1, -0.406456, 1, -1, 0.441856,-99) , 
3, 220.107, 1, 0, 0.488651,-99) , 
2, 1.64561, 0, 0, 0.49783,-99)    );
  // itree = 39
  fBoostWeights.push_back(0.0367267);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.568597,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51489,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480247,-99) , 
3, 61.946, 0, 0, 0.50911,-99) , 
3, 215.211, 0, 0, 0.517459,-99) , 
NN(
NN(
0, 
0, 
-1, 42.013, 0, -1, 0.494108,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501589,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.378092,-99) , 
2, -0.406456, 1, 0, 0.451847,-99) , 
3, 220.107, 1, 0, 0.484897,-99) , 
2, 1.64561, 0, 0, 0.497045,-99)    );
  // itree = 40
  fBoostWeights.push_back(0.0313446);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545621,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505682,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482676,-99) , 
1, 86.9187, 0, 0, 0.503212,-99) , 
NN(
0, 
0, 
-1, 262.011, 0, -1, 0.440929,-99) , 
3, 220.102, 1, 0, 0.495413,-99) , 
3, 330.106, 0, 0, 0.498859,-99)    );
  // itree = 41
  fBoostWeights.push_back(0.0294787);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53784,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514079,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493717,-99) , 
3, 167.723, 0, 0, 0.497058,-99) , 
NN(
0, 
0, 
-1, 262.011, 0, -1, 0.44867,-99) , 
3, 220.102, 1, 0, 0.491008,-99) , 
3, 330.106, 0, 0, 0.494219,-99)    );
  // itree = 42
  fBoostWeights.push_back(0.0334519);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.565806,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511432,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491889,-99) , 
3, 113.034, 1, 0, 0.50202,-99) , 
3, 215.211, 0, 0, 0.510932,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513639,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495798,-99) , 
0, 106.233, 1, 0, 0.502016,-99) , 
NN(
0, 
0, 
-1, -0.406456, 1, -1, 0.452589,-99) , 
3, 220.107, 1, 0, 0.491277,-99) , 
2, 1.64561, 0, 0, 0.498606,-99)    );
  // itree = 43
  fBoostWeights.push_back(0.037848);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.562979,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501529,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483215,-99) , 
3, 110.481, 1, 0, 0.494161,-99) , 
3, 153.678, 0, 0, 0.517933,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528068,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498119,-99) , 
0, 129.325, 0, 0, 0.508711,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500612,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.414423,-99) , 
3, 220.107, 1, 0, 0.477483,-99) , 
2, 0.975996, 0, 0, 0.49508,-99) , 
2, -2.54312, 1, 0, 0.500455,-99)    );
  // itree = 44
  fBoostWeights.push_back(0.0262578);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540941,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503604,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476296,-99) , 
3, 42.013, 0, 0, 0.500946,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512408,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.416282,-99) , 
3, 262.011, 0, 0, 0.4618,-99) , 
3, 220.102, 1, 0, 0.49607,-99) , 
3, 330.106, 0, 0, 0.499131,-99)    );
  // itree = 45
  fBoostWeights.push_back(0.0239869);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534414,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501809,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489989,-99) , 
2, 0.44883, 0, 0, 0.495659,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502423,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.41808,-99) , 
3, 256.773, 0, 0, 0.462098,-99) , 
3, 220.102, 1, 0, 0.491483,-99) , 
3, 330.106, 0, 0, 0.49441,-99)    );
  // itree = 46
  fBoostWeights.push_back(0.0393481);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.552892,-99) , 
NN(
0, 
0, 
-1, 81.6853, 1, -1, 0.492739,-99) , 
3, 153.678, 0, 0, 0.513455,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523799,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493494,-99) , 
2, 2.93535, 0, 0, 0.501278,-99) , 
NN(
0, 
0, 
-1, 220.107, 1, -1, 0.47142,-99) , 
2, 0.975996, 0, 0, 0.488242,-99) , 
2, -2.54312, 1, 0, 0.494168,-99)    );
  // itree = 47
  fBoostWeights.push_back(0.022944);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535156,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504968,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487726,-99) , 
2, 2.84239, 1, 0, 0.502259,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500738,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.426802,-99) , 
3, 256.773, 0, 0, 0.465424,-99) , 
3, 220.102, 1, 0, 0.497688,-99) , 
3, 330.106, 0, 0, 0.500234,-99)    );
  // itree = 48
  fBoostWeights.push_back(0.014796);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529444,-99) , 
NN(
0, 
0, 
-1, 220.102, 1, -1, 0.494209,-99) , 
3, 330.106, 0, 0, 0.496602,-99)    );
  // itree = 49
  fBoostWeights.push_back(0.0284742);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542364,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505266,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4981,-99) , 
3, 81.6853, 1, 0, 0.500538,-99) , 
3, 153.678, 0, 0, 0.514912,-99) , 
NN(
NN(
0, 
0, 
-1, 215.211, 0, 1, 0.5077,-99) , 
NN(
0, 
0, 
-1, 220.107, 1, -1, 0.478971,-99) , 
2, 0.975996, 0, 0, 0.495157,-99) , 
2, -2.54312, 1, 0, 0.499798,-99)    );
  // itree = 50
  fBoostWeights.push_back(0.0351205);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535289,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508669,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497716,-99) , 
3, 103.282, 0, 0, 0.502813,-99) , 
3, 153.678, 0, 0, 0.513966,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.546032,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498286,-99) , 
3, 94.3922, 0, 0, 0.5077,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510644,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467918,-99) , 
2, 2.32949, 0, 0, 0.484385,-99) , 
3, 110.108, 1, 0, 0.494252,-99) , 
2, -2.54312, 1, 0, 0.498883,-99)    );
  // itree = 51
  fBoostWeights.push_back(0.0448813);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 186.58, 0, 1, 0.524442,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.42931,-99) , 
0, 164.683, 1, 0, 0.51176,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538844,-99) , 
NN(
0, 
0, 
-1, 219.853, 1, -1, 0.486586,-99) , 
3, 319.633, 0, 0, 0.493132,-99) , 
3, 110.108, 1, 0, 0.500879,-99)    );
  // itree = 52
  fBoostWeights.push_back(0.0338489);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542351,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492292,-99) , 
3, 109.29, 0, 0, 0.521247,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503629,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478415,-99) , 
3, 126.932, 1, 0, 0.491758,-99) , 
0, 106.233, 0, 0, 0.510992,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532778,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497269,-99) , 
3, 215.211, 0, 0, 0.502938,-99) , 
NN(
0, 
0, 
-1, 0.0459514, 0, -1, 0.469025,-99) , 
2, 0.919169, 0, 0, 0.495532,-99) , 
2, -0.747949, 1, 0, 0.502371,-99)    );
  // itree = 53
  fBoostWeights.push_back(0.0413643);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516567,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489329,-99) , 
3, 178.198, 1, 0, 0.513365,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523795,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490189,-99) , 
3, 157.649, 0, 0, 0.497798,-99) , 
2, 2.244, 1, 0, 0.508383,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.541713,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516797,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.406296,-99) , 
2, -0.577249, 1, 0, 0.471605,-99) , 
2, 1.34636, 0, 0, 0.492341,-99) , 
3, 220.107, 1, 0, 0.505456,-99)    );
  // itree = 54
  fBoostWeights.push_back(0.0331017);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.562467,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509164,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488832,-99) , 
3, 105.812, 1, 0, 0.498766,-99) , 
3, 183.961, 0, 0, 0.512537,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515199,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498347,-99) , 
2, -1.60282, 0, 0, 0.50546,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506462,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.420007,-99) , 
2, -0.577117, 1, 0, 0.465257,-99) , 
3, 220.107, 1, 0, 0.497139,-99) , 
2, 2.244, 0, 0, 0.501742,-99)    );
  // itree = 55
  fBoostWeights.push_back(0.0349676);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 249.062, 0, 1, 0.508901,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521899,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454721,-99) , 
1, 150.98, 1, 0, 0.491964,-99) , 
3, 62.9646, 0, 0, 0.505473,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525973,-99) , 
NN(
0, 
0, 
-1, 258.018, 0, -1, 0.459538,-99) , 
3, 319.633, 0, 0, 0.485917,-99) , 
3, 220.107, 1, 0, 0.501913,-99)    );
  // itree = 56
  fBoostWeights.push_back(0.0581571);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.544383,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516191,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463051,-99) , 
0, 109.477, 0, 0, 0.4926,-99) , 
0, 154.298, 0, 0, 0.50013,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.539368,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483332,-99) , 
1, 221.644, 0, 0, 0.505333,-99) , 
NN(
0, 
0, 
-1, -0.448757, 1, -1, 0.460161,-99) , 
0, 129.325, 1, 0, 0.488488,-99) , 
1, 167.99, 1, 0, 0.496378,-99)    );
  // itree = 57
  fBoostWeights.push_back(0.0272853);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540612,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494254,-99) , 
1, 189.856, 0, 0, 0.501587,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474248,-99) , 
1, 241.342, 1, 0, 0.49852,-99) , 
NN(
0, 
0, 
-1, 177.436, 1, -1, 0.480961,-99) , 
1, 86.9187, 0, 0, 0.496373,-99)    );
  // itree = 58
  fBoostWeights.push_back(0.0293587);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.566073,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503708,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488347,-99) , 
3, 105.8, 1, 0, 0.495637,-99) , 
3, 183.961, 0, 0, 0.511371,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.563594,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496653,-99) , 
1, 192.894, 0, 0, 0.50334,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465212,-99) , 
1, 224.07, 1, 0, 0.498357,-99) , 
2, 2.54319, 0, 0, 0.501513,-99)    );
  // itree = 59
  fBoostWeights.push_back(0.0315796);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538873,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523761,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494074,-99) , 
3, 116.981, 0, 0, 0.503342,-99) , 
3, 153.007, 0, 0, 0.515297,-99) , 
NN(
NN(
0, 
0, 
-1, 1.34642, 1, 1, 0.506522,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526996,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.446222,-99) , 
2, 0.834092, 0, 0, 0.483671,-99) , 
3, 220.107, 1, 0, 0.501798,-99) , 
2, -2.24392, 1, 0, 0.505782,-99)    );
  // itree = 60
  fBoostWeights.push_back(0.0263559);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 153.007, 0, 1, 0.525545,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493956,-99) , 
0, 106.233, 0, 0, 0.514618,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531666,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487315,-99) , 
3, 125.312, 0, 0, 0.511565,-99) , 
NN(
0, 
0, 
-1, 220.107, 1, -1, 0.491994,-99) , 
2, 2.88513, 0, 0, 0.495653,-99) , 
2, -2.24392, 1, 0, 0.501249,-99)    );
  // itree = 61
  fBoostWeights.push_back(0.0238427);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526898,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511352,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497971,-99) , 
2, 1.34641, 1, 0, 0.505693,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518176,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.449182,-99) , 
3, 262.011, 0, 0, 0.48184,-99) , 
3, 220.102, 1, 0, 0.50275,-99) , 
3, 330.106, 0, 0, 0.504346,-99)    );
  // itree = 62
  fBoostWeights.push_back(0.0236489);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.547478,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507912,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486934,-99) , 
3, 88.4471, 0, 0, 0.50073,-99) , 
3, 183.961, 0, 0, 0.51076,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.55325,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498789,-99) , 
1, 192.951, 0, 0, 0.504268,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471829,-99) , 
1, 224.145, 1, 0, 0.500034,-99) , 
2, 2.244, 0, 0, 0.503237,-99)    );
  // itree = 63
  fBoostWeights.push_back(0.0227838);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524655,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510291,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498909,-99) , 
2, 2.54319, 1, 0, 0.507348,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51233,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.453785,-99) , 
3, 256.773, 0, 0, 0.484358,-99) , 
3, 220.102, 1, 0, 0.504514,-99) , 
3, 330.106, 0, 0, 0.505844,-99)    );
  // itree = 64
  fBoostWeights.push_back(0.0384372);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.539034,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51265,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479455,-99) , 
1, 106.253, 0, 0, 0.501288,-99) , 
0, 154.298, 0, 0, 0.506775,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5318,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49501,-99) , 
1, 221.644, 0, 0, 0.509501,-99) , 
NN(
0, 
0, 
-1, 144.327, 1, -1, 0.472287,-99) , 
0, 129.325, 1, 0, 0.495632,-99) , 
1, 167.99, 1, 0, 0.503188,-99)    );
  // itree = 65
  fBoostWeights.push_back(0.0235315);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542997,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506212,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48769,-99) , 
2, 2.97062, 1, 0, 0.500746,-99) , 
3, 183.961, 0, 0, 0.509797,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.551005,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497588,-99) , 
1, 192.951, 0, 0, 0.502962,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470667,-99) , 
1, 224.145, 1, 0, 0.498755,-99) , 
2, 2.244, 0, 0, 0.50205,-99)    );
  // itree = 66
  fBoostWeights.push_back(0.0177258);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522871,-99) , 
NN(
NN(
0, 
0, 
-1, 249.062, 0, 1, 0.505561,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511492,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464089,-99) , 
3, 262.011, 0, 0, 0.486557,-99) , 
3, 220.102, 1, 0, 0.50322,-99) , 
3, 330.106, 0, 0, 0.504515,-99)    );
  // itree = 67
  fBoostWeights.push_back(0.00909393);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518447,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515392,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499849,-99) , 
1, 249.062, 0, 0, 0.50113,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505484,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4663,-99) , 
3, 256.773, 0, 0, 0.486782,-99) , 
3, 220.102, 1, 0, 0.499363,-99) , 
3, 330.106, 0, 0, 0.50062,-99)    );
  // itree = 68
  fBoostWeights.push_back(0.0217148);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52969,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509192,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493383,-99) , 
3, 116.981, 0, 0, 0.498317,-99) , 
3, 153.007, 0, 0, 0.508843,-99) , 
NN(
NN(
0, 
0, 
-1, 125.312, 0, 1, 0.514254,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502371,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472134,-99) , 
3, 220.107, 1, 0, 0.495695,-99) , 
2, 2.88513, 0, 0, 0.499157,-99) , 
2, -2.24392, 1, 0, 0.502014,-99)    );
  // itree = 69
  fBoostWeights.push_back(0.019253);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524277,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506746,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490018,-99) , 
3, 109.777, 1, 0, 0.500357,-99) , 
3, 153.007, 0, 0, 0.50838,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518202,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497575,-99) , 
3, 125.312, 0, 0, 0.508828,-99) , 
NN(
0, 
0, 
-1, 330.106, 1, -1, 0.492663,-99) , 
2, 2.88513, 0, 0, 0.495677,-99) , 
2, -2.24392, 1, 0, 0.499424,-99)    );
  // itree = 70
  fBoostWeights.push_back(0.0324098);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52295,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511654,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.448285,-99) , 
0, 165.897, 1, 0, 0.503726,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503157,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.443319,-99) , 
1, 196.47, 1, 0, 0.491446,-99) , 
3, 157.247, 1, 0, 0.499915,-99) , 
3, 330.106, 0, 0, 0.501428,-99)    );
  // itree = 71
  fBoostWeights.push_back(0.0208215);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51486,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503554,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456314,-99) , 
0, 165.897, 1, 0, 0.497651,-99) , 
NN(
0, 
0, 
-1, 196.47, 1, -1, 0.486509,-99) , 
3, 157.247, 1, 0, 0.494193,-99) , 
3, 330.106, 0, 0, 0.49555,-99)    );
  // itree = 72
  fBoostWeights.push_back(0.0141364);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509658,-99) , 
NN(
0, 
0, 
-1, 47.251, 0, -1, 0.493114,-99) , 
3, 330.106, 0, 0, 0.4942,-99)    );
  // itree = 73
  fBoostWeights.push_back(0.0190842);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535199,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498681,-99) , 
3, 218.469, 0, 0, 0.504289,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477755,-99) , 
1, 224.145, 1, 0, 0.501075,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503985,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486677,-99) , 
1, 167.99, 1, 0, 0.498552,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468901,-99) , 
2, 0.363566, 0, 0, 0.494249,-99) , 
2, -0.747949, 1, 0, 0.49727,-99)    );
  // itree = 74
  fBoostWeights.push_back(0.0232609);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517388,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495046,-99) , 
3, 109.29, 0, 0, 0.508042,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477453,-99) , 
1, 224.145, 1, 0, 0.50432,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513936,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494772,-99) , 
2, 1.1877, 1, 0, 0.497229,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46095,-99) , 
2, 0.406127, 0, 0, 0.493132,-99) , 
2, -0.448754, 1, 0, 0.498351,-99)    );
  // itree = 75
  fBoostWeights.push_back(0.0167249);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511029,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490902,-99) , 
1, 99.4424, 0, 0, 0.506716,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488328,-99) , 
1, 224.145, 1, 0, 0.504489,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516855,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499988,-99) , 
3, 215.211, 0, 0, 0.502639,-99) , 
NN(
0, 
0, 
-1, 0.0459514, 0, -1, 0.479891,-99) , 
2, 0.919169, 0, 0, 0.497671,-99) , 
2, -0.747949, 1, 0, 0.500689,-99)    );
  // itree = 76
  fBoostWeights.push_back(0.0333526);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.563174,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498077,-99) , 
1, 186.58, 0, 0, 0.512595,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459632,-99) , 
0, 164.683, 1, 0, 0.505615,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53133,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488362,-99) , 
3, 165.743, 0, 0, 0.508824,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505595,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474618,-99) , 
2, -0.577142, 1, 0, 0.494703,-99) , 
2, 2.24399, 0, 0, 0.498968,-99) , 
3, 110.108, 1, 0, 0.501742,-99)    );
  // itree = 77
  fBoostWeights.push_back(0.0277308);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 186.58, 0, 1, 0.517223,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467926,-99) , 
0, 164.683, 1, 0, 0.51073,-99) , 
NN(
NN(
0, 
0, 
-1, 242.751, 0, 1, 0.508396,-99) , 
NN(
0, 
0, 
-1, -0.363655, 1, -1, 0.488633,-99) , 
2, 0.748021, 0, 0, 0.49736,-99) , 
3, 110.108, 1, 0, 0.502939,-99)    );
  // itree = 78
  fBoostWeights.push_back(0.0172528);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.548093,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499482,-99) , 
1, 186.58, 0, 0, 0.510295,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474836,-99) , 
0, 164.683, 1, 0, 0.505627,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515223,-99) , 
NN(
0, 
0, 
-1, 2.84238, 1, -1, 0.495812,-99) , 
3, 319.633, 0, 0, 0.498169,-99) , 
3, 110.108, 1, 0, 0.501281,-99)    );
  // itree = 79
  fBoostWeights.push_back(0.0346754);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.448896, 0, 1, 0.517734,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508999,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470251,-99) , 
3, 144.327, 1, 0, 0.491956,-99) , 
1, 167.99, 1, 0, 0.509177,-99) , 
NN(
NN(
0, 
0, 
-1, 97.8311, 1, 1, 0.543196,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500212,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.440218,-99) , 
1, 163.709, 1, 0, 0.490356,-99) , 
1, 190.034, 0, 0, 0.501551,-99) , 
0, 129.325, 0, 0, 0.504289,-99)    );
  // itree = 80
  fBoostWeights.push_back(0.0359122);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525121,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494618,-99) , 
2, 0.448896, 0, 0, 0.509071,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506206,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471771,-99) , 
2, 0.448826, 1, 0, 0.490907,-99) , 
1, 167.99, 1, 0, 0.503042,-99) , 
NN(
NN(
0, 
0, 
-1, 97.8311, 1, 1, 0.53458,-99) , 
NN(
0, 
0, 
-1, 77.1937, 0, -1, 0.48453,-99) , 
1, 190.034, 0, 0, 0.495125,-99) , 
0, 129.325, 0, 0, 0.497967,-99)    );
  // itree = 81
  fBoostWeights.push_back(0.0180001);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512021,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498019,-99) , 
1, 151.408, 1, 0, 0.505787,-99) , 
NN(
0, 
0, 
-1, 84.8363, 0, -1, 0.496107,-99) , 
2, 2.244, 1, 0, 0.502689,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513063,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509737,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.455131,-99) , 
2, -0.577249, 1, 0, 0.487355,-99) , 
2, 1.34636, 0, 0, 0.494875,-99) , 
3, 220.107, 1, 0, 0.50128,-99)    );
  // itree = 82
  fBoostWeights.push_back(0.0134237);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 249.062, 0, 1, 0.504999,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492593,-99) , 
3, 42.013, 0, 0, 0.503794,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508185,-99) , 
NN(
0, 
0, 
-1, 258.018, 0, -1, 0.483189,-99) , 
3, 319.633, 0, 0, 0.492982,-99) , 
3, 220.107, 1, 0, 0.501844,-99)    );
  // itree = 83
  fBoostWeights.push_back(0.0178174);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 88.4467, 1, 1, 0.508514,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469375,-99) , 
0, 164.683, 1, 0, 0.503356,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502949,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480514,-99) , 
1, 241.344, 1, 0, 0.500112,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482656,-99) , 
1, 86.9187, 0, 0, 0.497184,-99) , 
3, 110.108, 1, 0, 0.499759,-99)    );
  // itree = 84
  fBoostWeights.push_back(0.0216417);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.533781,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497138,-99) , 
0, 88.4467, 1, 0, 0.50406,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473815,-99) , 
0, 164.683, 1, 0, 0.500076,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507799,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468214,-99) , 
1, 195.507, 1, 0, 0.500189,-99) , 
NN(
0, 
0, 
-1, 0.748144, 0, -1, 0.490808,-99) , 
2, -0.448757, 1, 0, 0.495161,-99) , 
3, 110.108, 1, 0, 0.497211,-99)    );
  // itree = 85
  fBoostWeights.push_back(0.0200981);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518008,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505313,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490692,-99) , 
2, 2.04255, 0, 0, 0.50242,-99) , 
2, 1.21819, 1, 0, 0.504414,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509461,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48893,-99) , 
0, 122.449, 0, 0, 0.498085,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475117,-99) , 
1, 224.145, 1, 0, 0.495166,-99) , 
2, 0.44883, 0, 0, 0.499517,-99)    );
  // itree = 86
  fBoostWeights.push_back(0.0179336);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 186.58, 0, 1, 0.506973,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475802,-99) , 
0, 164.683, 1, 0, 0.50287,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520624,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495537,-99) , 
3, 242.751, 0, 0, 0.501083,-99) , 
NN(
0, 
0, 
-1, -0.918944, 1, -1, 0.490592,-99) , 
2, 0.448826, 0, 0, 0.495472,-99) , 
3, 110.108, 1, 0, 0.498558,-99)    );
  // itree = 87
  fBoostWeights.push_back(0.0155432);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520346,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501882,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467288,-99) , 
1, 202.711, 1, 0, 0.498519,-99) , 
1, 249.062, 0, 0, 0.500308,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505201,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509003,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463001,-99) , 
2, 1.43194, 0, 0, 0.486091,-99) , 
2, -0.44877, 1, 0, 0.494467,-99) , 
3, 220.107, 1, 0, 0.499256,-99)    );
  // itree = 88
  fBoostWeights.push_back(0.0375324);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52355,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.44401,-99) , 
1, 213.388, 1, 0, 0.505152,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488336,-99) , 
1, 241.342, 1, 0, 0.500013,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535717,-99) , 
NN(
0, 
0, 
-1, 96.6729, 0, -1, 0.487628,-99) , 
0, 154.298, 0, 0, 0.494592,-99) , 
1, 167.99, 0, 0, 0.49633,-99)    );
  // itree = 89
  fBoostWeights.push_back(0.0142047);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507694,-99) , 
NN(
NN(
0, 
0, 
-1, 194.449, 0, 1, 0.503755,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.44558,-99) , 
1, 214.306, 1, 0, 0.499977,-99) , 
1, 249.062, 0, 0, 0.500656,-99)    );
  // itree = 90
  fBoostWeights.push_back(0.0145797);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504143,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536412,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497654,-99) , 
1, 194.449, 0, 0, 0.500204,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.449092,-99) , 
1, 214.306, 1, 0, 0.496887,-99) , 
1, 249.062, 0, 0, 0.497525,-99)    );
  // itree = 91
  fBoostWeights.push_back(0.0127666);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.85955, 1, 1, 0.506736,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50339,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484484,-99) , 
3, 144.327, 0, 0, 0.491935,-99) , 
1, 167.99, 1, 0, 0.502113,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512252,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498544,-99) , 
2, -1.43187, 0, 0, 0.500686,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48351,-99) , 
2, -0.577012, 1, 0, 0.498349,-99) , 
2, 0.44883, 0, 0, 0.50012,-99)    );
  // itree = 92
  fBoostWeights.push_back(0.0203353);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516545,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497213,-99) , 
2, -1.44617, 0, 0, 0.504623,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477031,-99) , 
3, 330.106, 1, 0, 0.502279,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512625,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491327,-99) , 
3, 123.181, 0, 0, 0.502581,-99) , 
NN(
0, 
0, 
-1, 2.3357, 0, -1, 0.486334,-99) , 
2, 2.62875, 0, 0, 0.496819,-99) , 
2, 1.9448, 1, 0, 0.50042,-99)    );
  // itree = 93
  fBoostWeights.push_back(0.0142835);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526402,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513773,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499823,-99) , 
3, 130.449, 0, 0, 0.504012,-99) , 
3, 181.967, 0, 0, 0.508784,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52891,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49787,-99) , 
1, 249.062, 0, 0, 0.500653,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47546,-99) , 
3, 330.106, 1, 0, 0.498534,-99) , 
2, -1.94473, 1, 0, 0.501972,-99)    );
  // itree = 94
  fBoostWeights.push_back(0.0186394);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519374,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509133,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492469,-99) , 
3, 180.591, 1, 0, 0.50547,-99) , 
2, -2.97055, 1, 0, 0.508556,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517784,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497758,-99) , 
2, 1.21828, 1, 0, 0.503467,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475983,-99) , 
3, 330.383, 1, 0, 0.501151,-99) , 
2, -1.34634, 1, 0, 0.504077,-99)    );
  // itree = 95
  fBoostWeights.push_back(0.0173546);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 208.401, 1, 1, 0.509474,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498706,-99) , 
3, 72.1638, 0, 0, 0.507242,-99) , 
NN(
NN(
0, 
0, 
-1, 120.431, 0, 1, 0.506579,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504613,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46623,-99) , 
0, 123.159, 1, 0, 0.486772,-99) , 
2, -1.10423, 1, 0, 0.501741,-99) , 
2, 0.748025, 0, 0, 0.504213,-99)    );
  // itree = 96
  fBoostWeights.push_back(0.0201114);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515631,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494747,-99) , 
1, 113.941, 0, 0, 0.506958,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508391,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484388,-99) , 
0, 129.325, 1, 0, 0.499705,-99) , 
1, 167.99, 1, 0, 0.504703,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507166,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491867,-99) , 
2, -2.03023, 1, 0, 0.501022,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480265,-99) , 
1, 224.145, 1, 0, 0.498387,-99) , 
2, 0.748025, 0, 0, 0.501226,-99)    );
  // itree = 97
  fBoostWeights.push_back(0.012892);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513026,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518493,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4993,-99) , 
2, 0.63421, 1, 0, 0.50414,-99) , 
NN(
0, 
0, 
-1, -2.85664, 0, -1, 0.492693,-99) , 
2, -1.64553, 0, 0, 0.49979,-99) , 
3, 330.106, 0, 0, 0.500644,-99)    );
  // itree = 98
  fBoostWeights.push_back(0.0155711);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516204,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499356,-99) , 
1, 137.104, 1, 0, 0.510736,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507612,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489078,-99) , 
2, 2.62867, 0, 0, 0.497034,-99) , 
1, 167.99, 1, 0, 0.506457,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511489,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499459,-99) , 
3, 180.591, 0, 0, 0.502281,-99) , 
NN(
0, 
0, 
-1, -0.357174, 0, -1, 0.486801,-99) , 
2, -1.08991, 1, 0, 0.498998,-99) , 
2, 0.44883, 0, 0, 0.502509,-99)    );
  // itree = 99
  fBoostWeights.push_back(0.0186437);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 186.58, 0, 1, 0.510915,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478705,-99) , 
0, 164.683, 1, 0, 0.506684,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51544,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503143,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479211,-99) , 
2, -2.84231, 0, 0, 0.499169,-99) , 
3, 319.633, 0, 0, 0.501125,-99) , 
3, 110.108, 1, 0, 0.503447,-99)    );
   return;
};
 
// Clean up
inline void ReadBDT::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDT::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
