// Class: ReadBDT
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.06/01       [394753]
Creator        : kskovpen
Date           : Thu Feb  2 15:58:09 2017
Host           : Linux vocms0301.cern.ch 2.6.32-642.11.1.el6.x86_64 #1 SMP Wed Nov 16 09:40:09 CET 2016 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /storage_mnt/storage/user/kskovpen/analysis/tHFCNC/CMSSW_8_0_25/src/TopKinFit/test/Validation/TopHLepbb/MVA
Training events: 24680
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "100" [Number of trees in the forest]
MaxDepth: "3" [Max depth of the decision tree allowed]
nCuts: "20" [Number of grid points in variable range used in finding optimal cut in node splitting]
SeparationType: "giniindex" [Separation criterion for node splitting]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
MinNodeSize: "5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
BoostType: "AdaBoost" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
UseBaggedBoost: "False" [Use only a random subsample of all events for growing the trees in each boost iteration.]
Shrinkage: "1.000000e+00" [Learning rate for GradBoost algorithm]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "2" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split with RandomisedTree option]
BaggedSampleFraction: "6.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "inverseboostnegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "6.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 4
HiggsRecMCSVv2T               HiggsRecMCSVv2T               HiggsRecMCSVv2T               HiggsRecMCSVv2T                                                 'F'    [17.7585430145,1071.03320312]
TopLepRecMTCSVv2T             TopLepRecMTCSVv2T             TopLepRecMTCSVv2T             TopLepRecMTCSVv2T                                               'F'    [9.63081073761,969.55670166]
HiggsTopLepRecDphiTCSVv2T     HiggsTopLepRecDphiTCSVv2T     HiggsTopLepRecDphiTCSVv2T     HiggsTopLepRecDphiTCSVv2T                                       'F'    [-3.14159059525,3.14158010483]
TopLepRecPtTCSVv2T            TopLepRecPtTCSVv2T            TopLepRecPtTCSVv2T            TopLepRecPtTCSVv2T                                              'F'    [0.835266888142,685.404418945]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDTNode
   
#ifndef BDTNode__def
#define BDTNode__def
   
class BDTNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDTNode ( BDTNode* left,BDTNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTNode();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTNode* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTNode*   fLeft;     // pointer to the left daughter node
   BDTNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDTNode::~BDTNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDTNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDTNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT : public IClassifierReader {

 public:

   // constructor
   ReadBDT( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDT" ),
        fNvars( 4 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "HiggsRecMCSVv2T", "TopLepRecMTCSVv2T", "HiggsTopLepRecDphiTCSVv2T", "TopLepRecPtTCSVv2T" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[4];
   double fVmax[4];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[4];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTNode*)current->GetRight();
         else current=(BDTNode*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
};

void ReadBDT::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(0.583259296360468);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.72013,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.37794,-99) , 
0, 82.2331, 0, 0, 0.669774,-99) , 
NN(
0, 
0, 
-1, 229.478, 1, -1, 0.231534,-99) , 
1, 192.474, 1, 0, 0.611179,-99) , 
NN(
0, 
0, 
-1, 129.492, 0, -1, 0.0349145,-99) , 
0, 168.226, 1, 0, 0.5,-99)    );
  // itree = 1
  fBoostWeights.push_back(0.38047);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 163.828, 0, 1, 0.602401,-99) , 
NN(
0, 
0, 
-1, 151.827, 1, -1, 0.175229,-99) , 
0, 139.544, 1, 0, 0.549449,-99) , 
NN(
0, 
0, 
-1, 103.817, 0, -1, 0.060879,-99) , 
0, 168.226, 1, 0, 0.467916,-99)    );
  // itree = 2
  fBoostWeights.push_back(0.346576);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 213.512, 0, 1, 0.755702,-99) , 
NN(
0, 
0, 
-1, 132.38, 1, -1, 0.409283,-99) , 
3, 163.828, 0, 0, 0.477673,-99) , 
NN(
0, 
0, 
-1, 103.817, 0, -1, 0.0866228,-99) , 
0, 168.226, 1, 0, 0.419196,-99)    );
  // itree = 3
  fBoostWeights.push_back(0.236666);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 196.426, 0, 1, 0.556557,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.188613,-99) , 
0, 146.708, 1, 0, 0.530895,-99) , 
NN(
0, 
0, 
-1, 103.817, 0, -1, 0.11826,-99) , 
0, 168.226, 1, 0, 0.474731,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.220789);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.761804,-99) , 
NN(
0, 
0, 
-1, 226.524, 1, -1, 0.448392,-99) , 
3, 196.426, 0, 0, 0.479865,-99) , 
NN(
0, 
0, 
-1, 103.817, 0, -1, 0.145251,-99) , 
0, 168.226, 1, 0, 0.43725,-99)    );
  // itree = 5
  fBoostWeights.push_back(0.204649);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 131.229, 0, 1, 0.554435,-99) , 
NN(
0, 
0, 
-1, 229.478, 1, -1, 0.326159,-99) , 
1, 192.474, 1, 0, 0.524185,-99) , 
NN(
0, 
0, 
-1, 103.817, 0, -1, 0.174862,-99) , 
0, 168.226, 1, 0, 0.482163,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.25255);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.580462,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.398443,-99) , 
0, 94.1668, 0, 0, 0.518232,-99) , 
NN(
0, 
0, 
-1, 147.732, 1, -1, 0.32897,-99) , 
0, 132.38, 1, 0, 0.48652,-99) , 
NN(
0, 
0, 
-1, 103.817, 0, -1, 0.206377,-99) , 
0, 168.226, 1, 0, 0.454393,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.198012);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.703274,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.562002,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.411134,-99) , 
1, 165.487, 1, 0, 0.523084,-99) , 
3, 210.402, 0, 0, 0.564558,-99) , 
NN(
0, 
0, 
-1, 168.226, 1, -1, 0.403266,-99) , 
3, 131.229, 0, 0, 0.454874,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.139664);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529905,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.311242,-99) , 
0, 146.708, 1, 0, 0.516957,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.306907,-99) , 
0, 168.226, 1, 0, 0.497217,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.189597,-99) , 
1, 238.185, 1, 0, 0.478496,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.13616);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.648013,-99) , 
NN(
0, 
0, 
-1, 168.226, 1, -1, 0.455294,-99) , 
3, 196.426, 0, 0, 0.472443,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.211991,-99) , 
1, 238.185, 1, 0, 0.457131,-99)    );
  // itree = 10
  fBoostWeights.push_back(0.118065);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527407,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.320552,-99) , 
0, 60.7416, 0, 0, 0.514318,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.359888,-99) , 
0, 168.226, 1, 0, 0.500385,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.235627,-99) , 
1, 238.185, 1, 0, 0.48529,-99)    );
  // itree = 11
  fBoostWeights.push_back(0.100005);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.632655,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498318,-99) , 
3, 210.398, 0, 0, 0.515981,-99) , 
NN(
0, 
0, 
-1, 144.592, 1, -1, 0.440629,-99) , 
3, 98.6309, 0, 0, 0.479505,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.25755,-99) , 
1, 238.185, 1, 0, 0.46716,-99)    );
  // itree = 12
  fBoostWeights.push_back(0.0898363);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -2.84239, 1, 1, 0.534458,-99) , 
NN(
0, 
0, 
-1, 144.592, 1, -1, 0.465404,-99) , 
3, 98.6309, 0, 0, 0.501101,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.277131,-99) , 
1, 238.185, 1, 0, 0.488884,-99)    );
  // itree = 13
  fBoostWeights.push_back(0.097457);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524398,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.394335,-99) , 
0, 163.454, 1, 0, 0.510476,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.384349,-99) , 
0, 67.9145, 0, 0, 0.500341,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.295483,-99) , 
1, 238.185, 1, 0, 0.489347,-99)    );
  // itree = 14
  fBoostWeights.push_back(0.0833475);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.589766,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489079,-99) , 
1, 118.756, 0, 0, 0.548214,-99) , 
NN(
0, 
0, 
-1, 161.978, 1, -1, 0.471308,-99) , 
2, -2.84239, 1, 0, 0.484642,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.316167,-99) , 
1, 238.185, 1, 0, 0.475738,-99)    );
  // itree = 15
  fBoostWeights.push_back(0.108268);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.55211,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463121,-99) , 
1, 111.194, 0, 0, 0.517982,-99) , 
NN(
0, 
0, 
-1, 64.4683, 0, -1, 0.447394,-99) , 
1, 161.978, 1, 0, 0.50123,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.334457,-99) , 
1, 238.185, 1, 0, 0.49252,-99)    );
  // itree = 16
  fBoostWeights.push_back(0.106809);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.537954,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.426262,-99) , 
0, 70.3027, 0, 0, 0.521095,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532259,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.42053,-99) , 
3, 98.6519, 0, 0, 0.476975,-99) , 
0, 118.07, 1, 0, 0.502857,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.358972,-99) , 
1, 238.185, 1, 0, 0.495434,-99)    );
  // itree = 17
  fBoostWeights.push_back(0.0598878);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.552179,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490893,-99) , 
2, 2.84238, 0, 0, 0.502048,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.371056,-99) , 
0, 146.708, 1, 0, 0.494282,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.40988,-99) , 
0, 168.226, 1, 0, 0.486262,-99)    );
  // itree = 18
  fBoostWeights.push_back(0.0914869);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -3.06023, 1, 1, 0.578456,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52147,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477506,-99) , 
1, 163.474, 1, 0, 0.510117,-99) , 
2, -2.97065, 1, 0, 0.528714,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525431,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.410486,-99) , 
0, 144.884, 1, 0, 0.509667,-99) , 
NN(
0, 
0, 
-1, 103.59, 1, -1, 0.422545,-99) , 
2, 2.1728, 0, 0, 0.475567,-99) , 
2, -1.9448, 1, 0, 0.496585,-99)    );
  // itree = 19
  fBoostWeights.push_back(0.0466226);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.552472,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494096,-99) , 
2, -2.84239, 1, 0, 0.503765,-99) , 
NN(
0, 
0, 
-1, 104.448, 0, -1, 0.455113,-99) , 
1, 96.6863, 0, 0, 0.494915,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.401532,-99) , 
1, 238.185, 1, 0, 0.490209,-99)    );
  // itree = 20
  fBoostWeights.push_back(0.0532021);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521085,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478561,-99) , 
1, 170.787, 1, 0, 0.511566,-99) , 
NN(
0, 
0, 
-1, 104.448, 0, -1, 0.466697,-99) , 
1, 96.6863, 0, 0, 0.503414,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.412785,-99) , 
1, 238.185, 1, 0, 0.498862,-99)    );
  // itree = 21
  fBoostWeights.push_back(0.0612143);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.554298,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513599,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.449333,-99) , 
0, 125.216, 1, 0, 0.498105,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.413712,-99) , 
0, 168.226, 1, 0, 0.4905,-99) , 
3, 196.426, 0, 0, 0.496111,-99)    );
  // itree = 22
  fBoostWeights.push_back(0.0613409);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.553343,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517263,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473211,-99) , 
1, 125.228, 0, 0, 0.498943,-99) , 
2, -3.02763, 1, 0, 0.508934,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522415,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48007,-99) , 
2, 2.93399, 0, 0, 0.49171,-99) , 
NN(
0, 
0, 
-1, 77.9224, 1, -1, 0.423688,-99) , 
2, 0.96183, 0, 0, 0.476671,-99) , 
2, -1.9448, 1, 0, 0.489429,-99)    );
  // itree = 23
  fBoostWeights.push_back(0.0286894);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540659,-99) , 
NN(
0, 
0, 
-1, 168.226, 1, -1, 0.488181,-99) , 
3, 196.426, 0, 0, 0.492769,-99)    );
  // itree = 24
  fBoostWeights.push_back(0.0652919);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517218,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.44805,-99) , 
0, 136.158, 1, 0, 0.508932,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.561649,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.340963,-99) , 
0, 206.674, 1, 0, 0.454086,-99) , 
0, 163.454, 1, 0, 0.50272,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.452788,-99) , 
0, 67.9145, 0, 0, 0.498686,-99)    );
  // itree = 25
  fBoostWeights.push_back(0.0393154);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.588435,-99) , 
NN(
0, 
0, 
-1, 86.9703, 0, -1, 0.487876,-99) , 
3, 219.718, 0, 0, 0.493707,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.442761,-99) , 
3, 33.4338, 0, 0, 0.489827,-99)    );
  // itree = 26
  fBoostWeights.push_back(0.0290179);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.578882,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503058,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458934,-99) , 
1, 86.9703, 0, 0, 0.497703,-99) , 
3, 219.718, 0, 0, 0.502396,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.452482,-99) , 
3, 33.4338, 0, 0, 0.4986,-99)    );
  // itree = 27
  fBoostWeights.push_back(0.0273593);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.571792,-99) , 
NN(
0, 
0, 
-1, 166.489, 1, -1, 0.492208,-99) , 
3, 219.718, 0, 0, 0.4968,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.45968,-99) , 
3, 33.4338, 0, 0, 0.49398,-99)    );
  // itree = 28
  fBoostWeights.push_back(0.0235264);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.565081,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503234,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470033,-99) , 
3, 166.489, 1, 0, 0.499047,-99) , 
3, 219.718, 0, 0, 0.502851,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466483,-99) , 
3, 33.4338, 0, 0, 0.50009,-99)    );
  // itree = 29
  fBoostWeights.push_back(0.0410396);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517622,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484565,-99) , 
0, 103.716, 0, 0, 0.503119,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.437095,-99) , 
0, 146.708, 1, 0, 0.499279,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468207,-99) , 
0, 168.226, 1, 0, 0.496392,-99)    );
  // itree = 30
  fBoostWeights.push_back(0.0503058);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.557741,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505873,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.452771,-99) , 
1, 81.4564, 0, 0, 0.498287,-99) , 
3, 196.426, 0, 0, 0.503738,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52052,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.45624,-99) , 
3, 64.4683, 0, 0, 0.502645,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.389501,-99) , 
0, 153.773, 1, 0, 0.486206,-99) , 
1, 146.763, 1, 0, 0.49681,-99)    );
  // itree = 31
  fBoostWeights.push_back(0.0322748);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -3.06023, 1, 1, 0.525406,-99) , 
NN(
0, 
0, 
-1, -2.82409, 0, -1, 0.491015,-99) , 
2, -2.97065, 1, 0, 0.50027,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500987,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473428,-99) , 
1, 101.052, 0, 0, 0.495165,-99) , 
NN(
0, 
0, 
-1, 77.9224, 1, -1, 0.441524,-99) , 
2, 0.96183, 0, 0, 0.4833,-99) , 
2, -1.9448, 1, 0, 0.490003,-99)    );
  // itree = 32
  fBoostWeights.push_back(0.0387194);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 151.65, 0, 1, 0.510992,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478069,-99) , 
3, 65.4123, 0, 0, 0.503998,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50606,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482684,-99) , 
3, 131.229, 0, 0, 0.490504,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506333,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.376201,-99) , 
3, 77.9224, 1, 0, 0.449497,-99) , 
2, 0.96183, 0, 0, 0.481445,-99) , 
2, -1.9448, 1, 0, 0.490353,-99)    );
  // itree = 33
  fBoostWeights.push_back(0.0356903);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518423,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51085,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466556,-99) , 
2, -2.85669, 0, 0, 0.493373,-99) , 
3, 160.676, 0, 0, 0.498431,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500417,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482153,-99) , 
0, 102.509, 0, 0, 0.493704,-99) , 
NN(
0, 
0, 
-1, 77.9224, 1, -1, 0.448157,-99) , 
2, 0.96183, 0, 0, 0.483656,-99) , 
2, -1.9448, 1, 0, 0.489493,-99)    );
  // itree = 34
  fBoostWeights.push_back(0.0583718);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522398,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482087,-99) , 
0, 111.134, 1, 0, 0.504321,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.436934,-99) , 
0, 147.354, 1, 0, 0.494688,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.544584,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477041,-99) , 
0, 113.559, 0, 0, 0.50883,-99) , 
NN(
0, 
0, 
-1, 2.05877, 0, -1, 0.469116,-99) , 
2, -2.54319, 1, 0, 0.482278,-99) , 
3, 98.6309, 1, 0, 0.488257,-99)    );
  // itree = 35
  fBoostWeights.push_back(0.0374492);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.543413,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504223,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471231,-99) , 
2, 2.54319, 1, 0, 0.494496,-99) , 
3, 196.426, 0, 0, 0.498945,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50809,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460772,-99) , 
0, 127.864, 1, 0, 0.499664,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.405069,-99) , 
0, 153.773, 1, 0, 0.485997,-99) , 
1, 146.763, 1, 0, 0.493832,-99)    );
  // itree = 36
  fBoostWeights.push_back(0.0405079);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529637,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495179,-99) , 
2, 2.94213, 0, 0, 0.504414,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534607,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454525,-99) , 
0, 82.3242, 1, 0, 0.489741,-99) , 
0, 102.509, 0, 0, 0.499025,-99) , 
NN(
0, 
0, 
-1, -0.548621, 1, -1, 0.481483,-99) , 
2, 1.04719, 0, 0, 0.489694,-99)    );
  // itree = 37
  fBoostWeights.push_back(0.0357658);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.539733,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506169,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474,-99) , 
3, 131.204, 1, 0, 0.497666,-99) , 
3, 196.426, 0, 0, 0.501483,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510651,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474661,-99) , 
3, 64.4683, 0, 0, 0.500627,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.421945,-99) , 
0, 153.773, 1, 0, 0.489313,-99) , 
1, 146.763, 1, 0, 0.496679,-99)    );
  // itree = 38
  fBoostWeights.push_back(0.0239172);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510812,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491038,-99) , 
1, 120.634, 0, 0, 0.499249,-99) , 
NN(
0, 
0, 
-1, 153.825, 1, -1, 0.487812,-99) , 
1, 146.763, 1, 0, 0.494728,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473841,-99) , 
0, 67.9145, 0, 0, 0.493033,-99)    );
  // itree = 39
  fBoostWeights.push_back(0.0492828);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.562267,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456509,-99) , 
2, 2.74474, 0, 0, 0.514571,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.555733,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481971,-99) , 
2, 1.94491, 1, 0, 0.495348,-99) , 
3, 131.229, 0, 0, 0.501803,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506531,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48941,-99) , 
0, 120.678, 1, 0, 0.499971,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.416343,-99) , 
2, -0.548621, 1, 0, 0.491369,-99) , 
2, 1.04719, 0, 0, 0.496252,-99)    );
  // itree = 40
  fBoostWeights.push_back(0.0339535);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 131.229, 0, 1, 0.513296,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529466,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468151,-99) , 
0, 82.3242, 1, 0, 0.495122,-99) , 
0, 102.509, 0, 0, 0.506623,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518373,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493644,-99) , 
2, -1.78358, 0, 0, 0.497091,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.428366,-99) , 
2, -0.548621, 1, 0, 0.490046,-99) , 
2, 1.04719, 0, 0, 0.4978,-99)    );
  // itree = 41
  fBoostWeights.push_back(0.0234369);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -3.02763, 1, 1, 0.510594,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503353,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464096,-99) , 
2, 0.96183, 0, 0, 0.494562,-99) , 
2, -1.9448, 1, 0, 0.500877,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475919,-99) , 
0, 67.9145, 0, 0, 0.498849,-99)    );
  // itree = 42
  fBoostWeights.push_back(0.0211476);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526478,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501265,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470838,-99) , 
3, 160.159, 1, 0, 0.495887,-99) , 
2, -3.02764, 1, 0, 0.500587,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502253,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487664,-99) , 
2, 2.85061, 1, 0, 0.496938,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.447465,-99) , 
2, 1.10435, 0, 0, 0.490824,-99) , 
2, -0.748002, 1, 0, 0.495402,-99)    );
  // itree = 43
  fBoostWeights.push_back(0.0359322);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.544184,-99) , 
NN(
0, 
0, 
-1, 163.454, 1, -1, 0.488031,-99) , 
3, 163.847, 0, 0, 0.498423,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528737,-99) , 
NN(
0, 
0, 
-1, 174.346, 1, -1, 0.483701,-99) , 
1, 190.673, 0, 0, 0.489781,-99) , 
0, 118.07, 0, 0, 0.493342,-99)    );
  // itree = 44
  fBoostWeights.push_back(0.0314239);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.563623,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500926,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454121,-99) , 
0, 168.226, 1, 0, 0.496994,-99) , 
3, 148.302, 0, 0, 0.501984,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532286,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.433831,-99) , 
0, 111.341, 0, 0, 0.487627,-99) , 
3, 163.828, 1, 0, 0.499529,-99)    );
  // itree = 45
  fBoostWeights.push_back(0.035539);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508991,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.553194,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488099,-99) , 
0, 81.2202, 1, 0, 0.495287,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.448084,-99) , 
0, 60.7416, 0, 0, 0.492375,-99) , 
0, 168.226, 0, 0, 0.493901,-99)    );
  // itree = 46
  fBoostWeights.push_back(0.0226986);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -3.04188, 1, 1, 0.506586,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50777,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470311,-99) , 
2, 2.14429, 0, 0, 0.495909,-99) , 
2, -1.0472, 1, 0, 0.500783,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484739,-99) , 
0, 67.9145, 0, 0, 0.499481,-99)    );
  // itree = 47
  fBoostWeights.push_back(0.0360496);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532077,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520107,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490052,-99) , 
3, 56.7075, 1, 0, 0.496514,-99) , 
3, 196.426, 0, 0, 0.499716,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.550255,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490636,-99) , 
1, 195.273, 0, 0, 0.501953,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.439734,-99) , 
1, 225.126, 1, 0, 0.49162,-99) , 
1, 146.763, 1, 0, 0.496521,-99)    );
  // itree = 48
  fBoostWeights.push_back(0.0190006);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53338,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504811,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475027,-99) , 
3, 166.489, 1, 0, 0.501066,-99) , 
3, 219.718, 0, 0, 0.502874,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482013,-99) , 
3, 33.4338, 0, 0, 0.50129,-99)    );
  // itree = 49
  fBoostWeights.push_back(0.00950028);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528648,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500061,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479768,-99) , 
3, 166.489, 1, 0, 0.49751,-99) , 
3, 219.718, 0, 0, 0.499251,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486758,-99) , 
3, 33.4338, 0, 0, 0.498303,-99)    );
  // itree = 50
  fBoostWeights.push_back(0.0242482);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521588,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502845,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482815,-99) , 
2, 2.54319, 1, 0, 0.496946,-99) , 
3, 196.426, 0, 0, 0.499157,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517081,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493419,-99) , 
0, 114.91, 0, 0, 0.50238,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.438366,-99) , 
0, 153.773, 1, 0, 0.493206,-99) , 
1, 146.763, 1, 0, 0.496809,-99)    );
  // itree = 51
  fBoostWeights.push_back(0.0296811);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.84256, 0, 1, 0.530465,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503397,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469085,-99) , 
2, 2.79964, 1, 0, 0.485639,-99) , 
3, 131.98, 0, 0, 0.502147,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515964,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493827,-99) , 
3, 155.226, 0, 0, 0.496242,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.452116,-99) , 
3, 191.668, 1, 0, 0.492515,-99) , 
2, 2.24398, 0, 0, 0.495945,-99)    );
  // itree = 52
  fBoostWeights.push_back(0.0263093);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.555227,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500527,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454408,-99) , 
0, 168.226, 1, 0, 0.496658,-99) , 
3, 148.302, 0, 0, 0.501033,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523735,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.44553,-99) , 
0, 111.341, 0, 0, 0.488247,-99) , 
3, 163.828, 1, 0, 0.498853,-99)    );
  // itree = 53
  fBoostWeights.push_back(0.0301864);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.548721,-99) , 
NN(
0, 
0, 
-1, -2.84208, 0, -1, 0.491184,-99) , 
3, 148.302, 0, 0, 0.495476,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517168,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.452038,-99) , 
0, 111.341, 0, 0, 0.487626,-99) , 
3, 163.828, 1, 0, 0.494139,-99)    );
  // itree = 54
  fBoostWeights.push_back(0.0351902);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.541235,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503768,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471257,-99) , 
2, -2.84208, 0, 0, 0.498729,-99) , 
3, 148.302, 0, 0, 0.501897,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530867,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529807,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.397995,-99) , 
2, -2.60016, 1, 0, 0.463618,-99) , 
2, 2.54318, 0, 0, 0.486914,-99) , 
3, 163.828, 1, 0, 0.499346,-99)    );
  // itree = 55
  fBoostWeights.push_back(0.0235908);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520093,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503551,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464844,-99) , 
3, 143.114, 1, 0, 0.494256,-99) , 
2, -3.01354, 1, 0, 0.498605,-99) , 
NN(
0, 
0, 
-1, 1.26142, 0, -1, 0.488999,-99) , 
2, -0.448803, 1, 0, 0.493622,-99)    );
  // itree = 56
  fBoostWeights.push_back(0.0385316);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534648,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484002,-99) , 
3, 131.98, 0, 0, 0.503377,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512062,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469188,-99) , 
3, 99.9841, 1, 0, 0.493297,-99) , 
2, 2.64297, 0, 0, 0.498749,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.543565,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48801,-99) , 
3, 129.552, 0, 0, 0.51202,-99) , 
NN(
0, 
0, 
-1, 142.887, 1, -1, 0.485575,-99) , 
2, -2.94213, 1, 0, 0.491656,-99) , 
2, 1.04719, 0, 0, 0.494975,-99)    );
  // itree = 57
  fBoostWeights.push_back(0.0218358);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538059,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502758,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477297,-99) , 
2, 2.8424, 1, 0, 0.498656,-99) , 
3, 148.302, 0, 0, 0.501586,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511076,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461686,-99) , 
0, 111.341, 0, 0, 0.488681,-99) , 
3, 163.828, 1, 0, 0.499395,-99)    );
  // itree = 58
  fBoostWeights.push_back(0.0187727);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504443,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49108,-99) , 
2, -2.244, 0, 0, 0.499516,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506132,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.445243,-99) , 
2, 1.64567, 1, 0, 0.485669,-99) , 
3, 47.4001, 0, 0, 0.497254,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483965,-99) , 
3, 196.426, 1, 0, 0.496128,-99)    );
  // itree = 59
  fBoostWeights.push_back(0.0322417);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523425,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516269,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485844,-99) , 
3, 115.281, 0, 0, 0.495248,-99) , 
3, 160.676, 0, 0, 0.500888,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523894,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491951,-99) , 
3, 131.98, 0, 0, 0.504252,-99) , 
NN(
0, 
0, 
-1, 129.279, 1, -1, 0.482979,-99) , 
2, 2.65719, 0, 0, 0.491724,-99) , 
2, -1.9448, 1, 0, 0.495351,-99)    );
  // itree = 60
  fBoostWeights.push_back(0.0374667);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51446,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492514,-99) , 
2, -2.84198, 0, 0, 0.511081,-99) , 
NN(
0, 
0, 
-1, 2.24399, 1, -1, 0.483787,-99) , 
1, 164.31, 1, 0, 0.50398,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52766,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505514,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.439746,-99) , 
2, 2.00177, 0, 0, 0.477331,-99) , 
2, -2.84239, 1, 0, 0.488268,-99) , 
3, 131.229, 1, 0, 0.499014,-99)    );
  // itree = 61
  fBoostWeights.push_back(0.0243718);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.533014,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500979,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465993,-99) , 
0, 170.353, 1, 0, 0.498107,-99) , 
3, 118.807, 0, 0, 0.501622,-99) , 
NN(
NN(
0, 
0, 
-1, -2.94235, 1, 1, 0.513852,-99) , 
NN(
0, 
0, 
-1, 1.78831, 0, -1, 0.470555,-99) , 
2, -2.54319, 1, 0, 0.485169,-99) , 
3, 131.229, 1, 0, 0.496424,-99)    );
  // itree = 62
  fBoostWeights.push_back(0.0348498);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507118,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542834,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499797,-99) , 
2, -0.44847, 1, 0, 0.52158,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517956,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482004,-99) , 
0, 82.2331, 1, 0, 0.488001,-99) , 
1, 192.474, 0, 0, 0.492124,-99) , 
0, 168.226, 0, 0, 0.493495,-99)    );
  // itree = 63
  fBoostWeights.push_back(0.0235064);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530199,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500196,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463387,-99) , 
0, 170.353, 1, 0, 0.497173,-99) , 
3, 118.807, 0, 0, 0.500495,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527662,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496563,-99) , 
3, 184.033, 0, 0, 0.507512,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508212,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.411509,-99) , 
2, -2.41498, 1, 0, 0.476274,-99) , 
2, 1.94478, 0, 0, 0.490411,-99) , 
3, 131.229, 1, 0, 0.497311,-99)    );
  // itree = 64
  fBoostWeights.push_back(0.0236048);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532541,-99) , 
NN(
0, 
0, 
-1, 168.226, 1, -1, 0.492486,-99) , 
3, 148.302, 0, 0, 0.495457,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51037,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465364,-99) , 
2, 1.94479, 0, 0, 0.485581,-99) , 
3, 163.828, 1, 0, 0.493786,-99)    );
  // itree = 65
  fBoostWeights.push_back(0.0144622);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52666,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500799,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471909,-99) , 
0, 168.226, 1, 0, 0.498387,-99) , 
3, 148.302, 0, 0, 0.500483,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504779,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463787,-99) , 
0, 111.341, 0, 0, 0.486173,-99) , 
3, 163.828, 1, 0, 0.498062,-99)    );
  // itree = 66
  fBoostWeights.push_back(0.0175553);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523054,-99) , 
NN(
0, 
0, 
-1, 134.231, 1, -1, 0.495375,-99) , 
3, 148.302, 0, 0, 0.497426,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510306,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469332,-99) , 
2, -2.24396, 1, 0, 0.485836,-99) , 
3, 163.828, 1, 0, 0.495466,-99)    );
  // itree = 67
  fBoostWeights.push_back(0.025471);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531635,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5023,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478966,-99) , 
3, 107.565, 1, 0, 0.499548,-99) , 
3, 118.807, 0, 0, 0.502776,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517103,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496537,-99) , 
2, 2.80138, 0, 0, 0.507733,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510191,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.432378,-99) , 
2, -2.65719, 1, 0, 0.475142,-99) , 
2, 1.94478, 0, 0, 0.489903,-99) , 
3, 131.229, 1, 0, 0.498716,-99)    );
  // itree = 68
  fBoostWeights.push_back(0.0167509);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518318,-99) , 
NN(
0, 
0, 
-1, 2.8424, 1, -1, 0.495253,-99) , 
3, 148.302, 0, 0, 0.49696,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507973,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467855,-99) , 
2, 1.94479, 0, 0, 0.485894,-99) , 
3, 163.828, 1, 0, 0.495091,-99)    );
  // itree = 69
  fBoostWeights.push_back(0.0219472);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529463,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503681,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490613,-99) , 
2, 1.94485, 1, 0, 0.49887,-99) , 
3, 118.807, 0, 0, 0.501947,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511583,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495803,-99) , 
2, 2.91478, 1, 0, 0.505321,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500772,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.428424,-99) , 
2, -2.41498, 1, 0, 0.476987,-99) , 
2, 1.94478, 0, 0, 0.489826,-99) , 
3, 131.229, 1, 0, 0.498127,-99)    );
  // itree = 70
  fBoostWeights.push_back(0.0225968);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523992,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503129,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485661,-99) , 
2, -2.24371, 0, 0, 0.497423,-99) , 
3, 118.807, 0, 0, 0.500094,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51138,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495614,-99) , 
2, 2.80138, 0, 0, 0.50419,-99) , 
NN(
0, 
0, 
-1, -2.41498, 1, -1, 0.475095,-99) , 
2, 1.94478, 0, 0, 0.488281,-99) , 
3, 131.229, 1, 0, 0.496371,-99)    );
  // itree = 71
  fBoostWeights.push_back(0.0243011);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507407,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534506,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492434,-99) , 
0, 81.2202, 1, 0, 0.49706,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.455315,-99) , 
0, 60.7416, 0, 0, 0.494495,-99) , 
0, 168.226, 0, 0, 0.495677,-99)    );
  // itree = 72
  fBoostWeights.push_back(0.0124495);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -3.04188, 1, 1, 0.506292,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500512,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465698,-99) , 
2, 0.947532, 0, 0, 0.495894,-99) , 
2, -1.0472, 1, 0, 0.500642,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486553,-99) , 
0, 67.9145, 0, 0, 0.499501,-99)    );
  // itree = 73
  fBoostWeights.push_back(0.019725);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504423,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480569,-99) , 
3, 39.6424, 0, 0, 0.501429,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473272,-99) , 
0, 168.226, 1, 0, 0.499047,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508603,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473047,-99) , 
2, -1.94477, 1, 0, 0.488722,-99) , 
3, 163.828, 1, 0, 0.497305,-99)    );
  // itree = 74
  fBoostWeights.push_back(0.025767);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.541294,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496862,-99) , 
1, 195.583, 0, 0, 0.500578,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.450347,-99) , 
1, 225.125, 1, 0, 0.496464,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520389,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490557,-99) , 
2, 1.64569, 1, 0, 0.506991,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460903,-99) , 
0, 103.808, 0, 0, 0.488913,-99) , 
1, 101.052, 0, 0, 0.494939,-99)    );
  // itree = 75
  fBoostWeights.push_back(0.0221893);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 195.583, 0, 1, 0.505943,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456733,-99) , 
1, 225.125, 1, 0, 0.501917,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520234,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496146,-99) , 
1, 79.2771, 1, 0, 0.506338,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467311,-99) , 
0, 103.808, 0, 0, 0.491036,-99) , 
1, 101.052, 0, 0, 0.499719,-99)    );
  // itree = 76
  fBoostWeights.push_back(0.0131321);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503492,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493715,-99) , 
2, -2.28674, 0, 0, 0.499471,-99) , 
NN(
0, 
0, 
-1, 95.6274, 1, -1, 0.487108,-99) , 
2, 2.84238, 1, 0, 0.497367,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487745,-99) , 
3, 196.426, 1, 0, 0.49656,-99)    );
  // itree = 77
  fBoostWeights.push_back(0.0312433);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527402,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506083,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480468,-99) , 
1, 126.375, 0, 0, 0.495524,-99) , 
2, -3.04188, 1, 0, 0.499977,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508209,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467074,-99) , 
3, 66.8707, 0, 0, 0.499986,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506187,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.442044,-99) , 
3, 86.1189, 1, 0, 0.481654,-99) , 
2, 2.14429, 0, 0, 0.494317,-99) , 
2, -1.0472, 1, 0, 0.496904,-99)    );
  // itree = 78
  fBoostWeights.push_back(0.0199547);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509631,-99) , 
NN(
0, 
0, 
-1, 143.114, 1, -1, 0.494775,-99) , 
2, -2.99917, 1, 0, 0.497465,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519865,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492044,-99) , 
3, 164.534, 0, 0, 0.49794,-99) , 
NN(
0, 
0, 
-1, 146.763, 1, -1, 0.483109,-99) , 
2, 2.67142, 0, 0, 0.490242,-99) , 
2, -0.149605, 1, 0, 0.493797,-99)    );
  // itree = 79
  fBoostWeights.push_back(0.0142601);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510807,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504184,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49246,-99) , 
0, 111.042, 0, 0, 0.498453,-99) , 
2, -1.8598, 0, 0, 0.500647,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50134,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482302,-99) , 
3, 66.0323, 0, 0, 0.497266,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47928,-99) , 
2, 1.73111, 0, 0, 0.494212,-99) , 
2, -0.149605, 1, 0, 0.497379,-99)    );
  // itree = 80
  fBoostWeights.push_back(0.020466);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51351,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49987,-99) , 
3, 56.7086, 1, 0, 0.503927,-99) , 
NN(
0, 
0, 
-1, 93.9779, 1, -1, 0.484836,-99) , 
1, 164.31, 1, 0, 0.498964,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522707,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4889,-99) , 
3, 182.434, 0, 0, 0.501293,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501873,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461157,-99) , 
2, 2.65736, 0, 0, 0.483238,-99) , 
2, -1.9448, 1, 0, 0.491084,-99) , 
3, 131.229, 1, 0, 0.496483,-99)    );
  // itree = 81
  fBoostWeights.push_back(0.0202723);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50673,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490182,-99) , 
0, 125.216, 1, 0, 0.502743,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479171,-99) , 
0, 168.226, 1, 0, 0.500757,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50612,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473138,-99) , 
2, -1.94477, 1, 0, 0.487688,-99) , 
3, 163.828, 1, 0, 0.498554,-99)    );
  // itree = 82
  fBoostWeights.push_back(0.0159627);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520897,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500467,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487643,-99) , 
3, 45.774, 0, 0, 0.497557,-99) , 
3, 118.807, 0, 0, 0.499905,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516564,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491346,-99) , 
3, 184.033, 0, 0, 0.500209,-99) , 
NN(
0, 
0, 
-1, -2.41498, 1, -1, 0.482808,-99) , 
2, 1.94478, 0, 0, 0.490708,-99) , 
3, 131.229, 1, 0, 0.49701,-99)    );
  // itree = 83
  fBoostWeights.push_back(0.0186196);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508219,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496226,-99) , 
1, 125.64, 1, 0, 0.500837,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504289,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461505,-99) , 
1, 119.099, 0, 0, 0.488465,-99) , 
2, 2.54318, 1, 0, 0.497356,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484098,-99) , 
3, 196.426, 1, 0, 0.496247,-99)    );
  // itree = 84
  fBoostWeights.push_back(0.0119064);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510523,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501805,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489229,-99) , 
3, 65.4123, 0, 0, 0.499086,-99) , 
2, -1.8598, 0, 0, 0.501115,-99) , 
NN(
0, 
0, 
-1, 1.73111, 0, -1, 0.493072,-99) , 
2, -0.149605, 1, 0, 0.497031,-99)    );
  // itree = 85
  fBoostWeights.push_back(0.0165396);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507911,-99) , 
NN(
NN(
0, 
0, 
-1, 105.05, 1, 1, 0.51985,-99) , 
NN(
0, 
0, 
-1, 163.828, 1, -1, 0.493308,-99) , 
1, 192.474, 0, 0, 0.496562,-99) , 
0, 168.226, 0, 0, 0.497599,-99)    );
  // itree = 86
  fBoostWeights.push_back(0.0155756);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505324,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485077,-99) , 
1, 202.98, 1, 0, 0.503185,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504962,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48007,-99) , 
3, 95.6274, 1, 0, 0.489757,-99) , 
2, 2.84238, 1, 0, 0.5009,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490823,-99) , 
3, 196.426, 1, 0, 0.500057,-99)    );
  // itree = 87
  fBoostWeights.push_back(0.0156253);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527585,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496542,-99) , 
3, 84.6488, 0, 0, 0.502618,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502409,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488016,-99) , 
0, 115.686, 0, 0, 0.494999,-99) , 
3, 98.6309, 1, 0, 0.498768,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491547,-99) , 
0, 67.9145, 0, 0, 0.498182,-99)    );
  // itree = 88
  fBoostWeights.push_back(0.0248958);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528233,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483919,-99) , 
2, -2.45771, 0, 0, 0.514126,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489166,-99) , 
2, 1.64567, 1, 0, 0.505353,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526694,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497641,-99) , 
2, 2.42961, 1, 0, 0.504213,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50232,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457592,-99) , 
2, -2.0019, 1, 0, 0.491993,-99) , 
2, 1.64558, 0, 0, 0.497582,-99) , 
3, 66.0323, 1, 0, 0.499633,-99)    );
  // itree = 89
  fBoostWeights.push_back(0.0220107);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 131.98, 0, 1, 0.510737,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509215,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487466,-99) , 
2, 2.41958, 1, 0, 0.500307,-99) , 
2, 2.74269, 0, 0, 0.505117,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527919,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496388,-99) , 
2, -1.74546, 0, 0, 0.508921,-99) , 
NN(
0, 
0, 
-1, -1.54592, 1, -1, 0.48943,-99) , 
3, 64.4683, 1, 0, 0.494804,-99) , 
2, 1.04719, 0, 0, 0.499633,-99)    );
  // itree = 90
  fBoostWeights.push_back(0.0202368);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 56.2615, 1, 1, 0.51731,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510661,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479812,-99) , 
2, 0.448934, 1, 0, 0.496472,-99) , 
3, 47.3928, 0, 0, 0.505491,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52048,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498396,-99) , 
3, 154.518, 0, 0, 0.504698,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501599,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466962,-99) , 
2, -2.0019, 1, 0, 0.493611,-99) , 
2, 1.64558, 0, 0, 0.498681,-99) , 
3, 66.0323, 1, 0, 0.500478,-99)    );
  // itree = 91
  fBoostWeights.push_back(0.020206);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514097,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483623,-99) , 
1, 167.088, 1, 0, 0.507457,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506534,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4848,-99) , 
2, 2.41501, 1, 0, 0.49982,-99) , 
2, 2.64297, 0, 0, 0.503955,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515497,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495005,-99) , 
2, -1.78358, 0, 0, 0.497845,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474961,-99) , 
2, -0.548621, 1, 0, 0.495544,-99) , 
2, 1.04719, 0, 0, 0.499482,-99)    );
  // itree = 92
  fBoostWeights.push_back(0.0140475);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51099,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499683,-99) , 
1, 148.527, 0, 0, 0.503936,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477815,-99) , 
0, 168.226, 1, 0, 0.501745,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507143,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482323,-99) , 
2, 1.94479, 0, 0, 0.493527,-99) , 
3, 163.828, 1, 0, 0.500362,-99)    );
  // itree = 93
  fBoostWeights.push_back(0.0150143);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 125.018, 0, 1, 0.504807,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481321,-99) , 
0, 168.226, 1, 0, 0.502837,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510131,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480958,-99) , 
2, -1.94477, 1, 0, 0.493867,-99) , 
3, 163.828, 1, 0, 0.501327,-99)    );
  // itree = 94
  fBoostWeights.push_back(0.0120407);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507112,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502202,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468105,-99) , 
0, 60.7374, 0, 0, 0.49998,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46517,-99) , 
0, 146.708, 1, 0, 0.497969,-99) , 
0, 168.226, 0, 0, 0.498801,-99)    );
  // itree = 95
  fBoostWeights.push_back(0.0149345);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504102,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507911,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496239,-99) , 
3, 125.018, 0, 0, 0.498743,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504201,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458355,-99) , 
2, 1.94479, 0, 0, 0.479782,-99) , 
3, 163.828, 1, 0, 0.495676,-99) , 
0, 168.226, 0, 0, 0.496443,-99)    );
  // itree = 96
  fBoostWeights.push_back(0.0209444);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 112.582, 0, 1, 0.504883,-99) , 
NN(
0, 
0, 
-1, 93.9779, 1, -1, 0.486934,-99) , 
1, 164.31, 1, 0, 0.500221,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519375,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482294,-99) , 
2, -1.94477, 1, 0, 0.498802,-99) , 
NN(
0, 
0, 
-1, 1.64546, 0, -1, 0.482651,-99) , 
3, 157.624, 0, 0, 0.492409,-99) , 
3, 131.229, 1, 0, 0.497763,-99)    );
  // itree = 97
  fBoostWeights.push_back(0.0172102);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511552,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501164,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460475,-99) , 
0, 150.058, 1, 0, 0.495797,-99) , 
3, 84.6488, 0, 0, 0.498918,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523836,-99) , 
NN(
0, 
0, 
-1, 132.374, 1, -1, 0.491665,-99) , 
0, 168.226, 0, 0, 0.494808,-99) , 
3, 98.6309, 1, 0, 0.496799,-99)    );
  // itree = 98
  fBoostWeights.push_back(0.0180469);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.88528, 1, 1, 0.510796,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504485,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48682,-99) , 
2, 2.92787, 0, 0, 0.492952,-99) , 
3, 131.98, 0, 0, 0.499505,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517289,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500218,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466796,-99) , 
0, 127.821, 1, 0, 0.493089,-99) , 
0, 170.696, 0, 0, 0.495516,-99) , 
2, 2.24398, 0, 0, 0.49694,-99)    );
  // itree = 99
  fBoostWeights.push_back(0.0168417);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509783,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498535,-99) , 
3, 155.24, 0, 0, 0.501824,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485951,-99) , 
3, 66.8707, 0, 0, 0.498721,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512782,-99) , 
NN(
0, 
0, 
-1, 127.821, 1, -1, 0.490501,-99) , 
0, 170.696, 0, 0, 0.492735,-99) , 
2, 2.24398, 0, 0, 0.494871,-99)    );
   return;
};
 
// Clean up
inline void ReadBDT::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDT::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
