// Class: ReadBDT
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.06/01       [394753]
Creator        : kskovpen
Date           : Sat Aug 20 14:19:42 2016
Host           : Linux vocms0315.cern.ch 2.6.32-573.26.1.el6.x86_64 #1 SMP Wed May 4 09:23:05 CEST 2016 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /grid_mnt/home-pbs/kskovpen/tHFCNC2016/CMSSW_8_0_12/src/TopKinFit/test/Validation/TopHLepbb/MVA
Training events: 16636
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "100" [Number of trees in the forest]
MaxDepth: "3" [Max depth of the decision tree allowed]
nCuts: "20" [Number of grid points in variable range used in finding optimal cut in node splitting]
SeparationType: "giniindex" [Separation criterion for node splitting]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
MinNodeSize: "5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
BoostType: "AdaBoost" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
UseBaggedBoost: "False" [Use only a random subsample of all events for growing the trees in each boost iteration.]
Shrinkage: "1.000000e+00" [Learning rate for GradBoost algorithm]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "2" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split with RandomisedTree option]
BaggedSampleFraction: "6.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "inverseboostnegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "6.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 4
HiggsRecMTruth                HiggsRecMTruth                HiggsRecMTruth                HiggsRecMTruth                                                  'F'    [22.9993610382,1659.66638184]
TopLepRecMTruth               TopLepRecMTruth               TopLepRecMTruth               TopLepRecMTruth                                                 'F'    [86.6839904785,2599.60620117]
HiggsTopLepRecDrTruth         HiggsTopLepRecDrTruth         HiggsTopLepRecDrTruth         HiggsTopLepRecDrTruth                                           'F'    [0.0341337248683,7.5580239296]
TopLepRecPtTruth              TopLepRecPtTruth              TopLepRecPtTruth              TopLepRecPtTruth                                                'F'    [1.6324262619,1544.73852539]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDTNode
   
#ifndef BDTNode__def
#define BDTNode__def
   
class BDTNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDTNode ( BDTNode* left,BDTNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTNode();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTNode* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTNode*   fLeft;     // pointer to the left daughter node
   BDTNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDTNode::~BDTNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDTNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDTNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT : public IClassifierReader {

 public:

   // constructor
   ReadBDT( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDT" ),
        fNvars( 4 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "HiggsRecMTruth", "TopLepRecMTruth", "HiggsTopLepRecDrTruth", "TopLepRecPtTruth" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[4];
   double fVmax[4];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[4];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTNode*)current->GetRight();
         else current=(BDTNode*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
};

void ReadBDT::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(0.656836129524499);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.811559,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.448634,-99) , 
0, 141.701, 1, 0, 0.770983,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503394,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0748901,-99) , 
1, 320.32, 1, 0, 0.385377,-99) , 
1, 206.347, 1, 0, 0.64743,-99) , 
NN(
0, 
0, 
-1, 194.49, 1, -1, 0.0257355,-99) , 
0, 178.872, 1, 0, 0.5,-99)    );
  // itree = 1
  fBoostWeights.push_back(0.529836);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 148.964, 0, 1, 0.680161,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510495,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.216409,-99) , 
3, 180.545, 0, 0, 0.298917,-99) , 
1, 206.347, 1, 0, 0.54796,-99) , 
NN(
0, 
0, 
-1, 249.416, 1, -1, 0.0484769,-99) , 
0, 178.872, 1, 0, 0.446621,-99)    );
  // itree = 2
  fBoostWeights.push_back(0.49315);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.752643,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.388047,-99) , 
2, 2.35985, 0, 0, 0.627044,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.614928,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.310912,-99) , 
2, 3.27343, 0, 0, 0.372938,-99) , 
3, 148.595, 0, 0, 0.481264,-99) , 
NN(
0, 
0, 
-1, 249.416, 1, -1, 0.0796479,-99) , 
0, 178.872, 1, 0, 0.40986,-99)    );
  // itree = 3
  fBoostWeights.push_back(0.360225);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.591186,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.222273,-99) , 
0, 149.169, 1, 0, 0.547077,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.215237,-99) , 
0, 74.948, 0, 0, 0.506905,-99) , 
NN(
0, 
0, 
-1, 249.416, 1, -1, 0.124119,-99) , 
0, 178.872, 1, 0, 0.445949,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.363812);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 167.511, 0, 1, 0.781071,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.584231,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.40048,-99) , 
2, 3.22816, 0, 0, 0.440393,-99) , 
3, 222.426, 0, 0, 0.510278,-99) , 
NN(
0, 
0, 
-1, 178.962, 1, -1, 0.262892,-99) , 
1, 206.347, 1, 0, 0.413805,-99)    );
  // itree = 5
  fBoostWeights.push_back(0.253216);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.558084,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.304641,-99) , 
1, 246.198, 1, 0, 0.523304,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.154578,-99) , 
0, 206.568, 1, 0, 0.49542,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.124345,-99) , 
1, 326.01, 1, 0, 0.459779,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.215273);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.705448,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.446633,-99) , 
3, 295.557, 0, 0, 0.47233,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.186406,-99) , 
1, 326.01, 1, 0, 0.451519,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0520712,-99) , 
0, 256.809, 1, 0, 0.429763,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.188536);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.593914,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46301,-99) , 
3, 148.595, 0, 0, 0.515524,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.221273,-99) , 
1, 326.01, 1, 0, 0.49517,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.063781,-99) , 
0, 256.809, 1, 0, 0.473437,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.208479);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.566005,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.38703,-99) , 
0, 82.3692, 0, 0, 0.537416,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.299192,-99) , 
2, 1.13114, 0, 0, 0.517842,-99) , 
NN(
0, 
0, 
-1, 249.416, 1, -1, 0.258986,-99) , 
0, 178.872, 1, 0, 0.486874,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.130137);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 3.63048, 0, 1, 0.521894,-99) , 
NN(
0, 
0, 
-1, 213.73, 1, -1, 0.360016,-99) , 
0, 145.379, 1, 0, 0.490004,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.214871,-99) , 
1, 326.01, 1, 0, 0.467595,-99)    );
  // itree = 10
  fBoostWeights.push_back(0.138394);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514818,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.307027,-99) , 
1, 129.001, 0, 0, 0.496829,-99) , 
NN(
0, 
0, 
-1, 134.382, 1, -1, 0.346273,-99) , 
1, 234.804, 1, 0, 0.470141,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.237638,-99) , 
1, 326.01, 1, 0, 0.451751,-99)    );
  // itree = 11
  fBoostWeights.push_back(0.163231);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.620849,-99) , 
NN(
0, 
0, 
-1, 75.5026, 0, -1, 0.436932,-99) , 
2, 3.61694, 0, 0, 0.452422,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.263612,-99) , 
1, 326.01, 1, 0, 0.437891,-99)    );
  // itree = 12
  fBoostWeights.push_back(0.139252);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53283,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.374219,-99) , 
2, 1.41672, 0, 0, 0.512326,-99) , 
NN(
0, 
0, 
-1, 57.6084, 0, -1, 0.394887,-99) , 
3, 75.1137, 0, 0, 0.486128,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.296494,-99) , 
1, 326.01, 1, 0, 0.471908,-99)    );
  // itree = 13
  fBoostWeights.push_back(0.11107);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.595051,-99) , 
NN(
0, 
0, 
-1, 326.01, 1, -1, 0.448879,-99) , 
3, 295.557, 0, 0, 0.462808,-99)    );
  // itree = 14
  fBoostWeights.push_back(0.0938528);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520005,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.369104,-99) , 
1, 132.259, 0, 0, 0.507052,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.324348,-99) , 
0, 206.568, 1, 0, 0.496453,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.340654,-99) , 
1, 326.01, 1, 0, 0.485169,-99)    );
  // itree = 15
  fBoostWeights.push_back(0.0871729);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509114,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.339858,-99) , 
0, 67.5253, 0, 0, 0.495518,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.263642,-99) , 
0, 156.582, 1, 0, 0.481927,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504125,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.26857,-99) , 
3, 141.94, 0, 0, 0.38027,-99) , 
0, 178.872, 1, 0, 0.471033,-99)    );
  // itree = 16
  fBoostWeights.push_back(0.106551);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.55922,-99) , 
NN(
0, 
0, 
-1, 162.573, 1, -1, 0.447482,-99) , 
2, 3.61694, 0, 0, 0.456764,-99)    );
  // itree = 17
  fBoostWeights.push_back(0.0835413);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514595,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.416085,-99) , 
0, 84.1889, 0, 0, 0.499649,-99) , 
NN(
0, 
0, 
-1, 2.79183, 0, -1, 0.384027,-99) , 
1, 257.592, 1, 0, 0.487106,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.370519,-99) , 
1, 326.01, 1, 0, 0.478836,-99)    );
  // itree = 18
  fBoostWeights.push_back(0.0853949);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.598075,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501814,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.361924,-99) , 
0, 134.318, 1, 0, 0.473329,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.374812,-99) , 
0, 178.872, 1, 0, 0.463107,-99) , 
3, 369.039, 0, 0, 0.470274,-99)    );
  // itree = 19
  fBoostWeights.push_back(0.143711);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.695285,-99) , 
NN(
0, 
0, 
-1, 1.43734, 0, -1, 0.404106,-99) , 
2, 2.71329, 0, 0, 0.52099,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523228,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.452154,-99) , 
2, 3.5185, 0, 0, 0.458968,-99) , 
NN(
0, 
0, 
-1, 2.91638, 1, -1, 0.379536,-99) , 
3, 54.1182, 0, 0, 0.446808,-99) , 
3, 222.076, 0, 0, 0.460361,-99)    );
  // itree = 20
  fBoostWeights.push_back(0.0478642);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.595493,-99) , 
NN(
0, 
0, 
-1, 326.01, 1, -1, 0.480032,-99) , 
3, 369.039, 0, 0, 0.486063,-99)    );
  // itree = 21
  fBoostWeights.push_back(0.0559531);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.670839,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501626,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.394033,-99) , 
1, 289.388, 1, 0, 0.491047,-99) , 
3, 295.557, 0, 0, 0.503838,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.421191,-99) , 
2, 1.10898, 0, 0, 0.496774,-99)    );
  // itree = 22
  fBoostWeights.push_back(0.0418265);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.581677,-99) , 
NN(
0, 
0, 
-1, 54.1125, 0, -1, 0.482392,-99) , 
3, 369.039, 0, 0, 0.487496,-99)    );
  // itree = 23
  fBoostWeights.push_back(0.0532376);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 285.064, 0, 1, 0.516449,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.418847,-99) , 
2, 1.07107, 0, 0, 0.508057,-99) , 
NN(
0, 
0, 
-1, 54.1099, 0, -1, 0.45712,-99) , 
3, 75.1137, 0, 0, 0.496874,-99)    );
  // itree = 24
  fBoostWeights.push_back(0.0325935);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.568784,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500306,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.415851,-99) , 
1, 132.259, 0, 0, 0.492975,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.398655,-99) , 
1, 326.01, 1, 0, 0.487038,-99) , 
3, 369.039, 0, 0, 0.491183,-99)    );
  // itree = 25
  fBoostWeights.push_back(0.0418112);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.560773,-99) , 
NN(
0, 
0, 
-1, 326.01, 1, -1, 0.481233,-99) , 
3, 369.039, 0, 0, 0.48526,-99)    );
  // itree = 26
  fBoostWeights.push_back(0.0730341);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.664473,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50307,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.447977,-99) , 
2, 3.2075, 1, 0, 0.487541,-99) , 
3, 240.183, 0, 0, 0.504437,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.548343,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474938,-99) , 
2, 1.1724, 1, 0, 0.496609,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.407346,-99) , 
3, 224.938, 1, 0, 0.468011,-99) , 
2, 2.18382, 0, 0, 0.494648,-99)    );
  // itree = 27
  fBoostWeights.push_back(0.10127);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542166,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470715,-99) , 
0, 97.2067, 0, 0, 0.515034,-99) , 
NN(
0, 
0, 
-1, 155.527, 1, -1, 0.423326,-99) , 
0, 134.318, 1, 0, 0.496538,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.539844,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.349563,-99) , 
3, 141.94, 0, 0, 0.442858,-99) , 
0, 178.872, 1, 0, 0.49102,-99)    );
  // itree = 28
  fBoostWeights.push_back(0.0798597);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.568337,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483806,-99) , 
1, 206.347, 0, 0, 0.512608,-99) , 
NN(
0, 
0, 
-1, 154.109, 1, -1, 0.458276,-99) , 
0, 126.897, 1, 0, 0.496767,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514607,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.372925,-99) , 
3, 141.94, 0, 0, 0.442791,-99) , 
0, 178.872, 1, 0, 0.491245,-99)    );
  // itree = 29
  fBoostWeights.push_back(0.102836);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.539009,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.452537,-99) , 
1, 134.233, 0, 0, 0.528135,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.446665,-99) , 
0, 83.7535, 0, 0, 0.516608,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.556855,-99) , 
NN(
0, 
0, 
-1, 175.255, 1, -1, 0.425247,-99) , 
0, 101.03, 1, 0, 0.470507,-99) , 
1, 206.347, 1, 0, 0.500539,-99)    );
  // itree = 30
  fBoostWeights.push_back(0.0453269);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.654979,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495925,-99) , 
3, 295.557, 0, 0, 0.506816,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.428038,-99) , 
2, 1.13114, 0, 0, 0.500615,-99) , 
NN(
0, 
0, 
-1, 141.94, 0, -1, 0.444456,-99) , 
0, 178.872, 1, 0, 0.494923,-99)    );
  // itree = 31
  fBoostWeights.push_back(0.0470388);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 295.557, 0, 1, 0.516605,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.439169,-99) , 
2, 1.13114, 0, 0, 0.510524,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509661,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.402523,-99) , 
3, 141.94, 0, 0, 0.455674,-99) , 
0, 178.872, 1, 0, 0.504973,-99)    );
  // itree = 32
  fBoostWeights.push_back(0.0528192);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515779,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.45913,-99) , 
1, 129.001, 0, 0, 0.511162,-99) , 
NN(
0, 
0, 
-1, 2.90038, 0, -1, 0.445842,-99) , 
1, 234.804, 1, 0, 0.500052,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.440196,-99) , 
1, 326.01, 1, 0, 0.49607,-99)    );
  // itree = 33
  fBoostWeights.push_back(0.0508537);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52893,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486715,-99) , 
1, 206.347, 0, 0, 0.500768,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.427709,-99) , 
0, 149.16, 1, 0, 0.494672,-99) , 
NN(
0, 
0, 
-1, 141.94, 0, -1, 0.452949,-99) , 
0, 178.872, 1, 0, 0.490471,-99)    );
  // itree = 34
  fBoostWeights.push_back(0.0547523);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.568586,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499972,-99) , 
3, 196.393, 0, 0, 0.515308,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.433568,-99) , 
1, 194.941, 1, 0, 0.506686,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523468,-99) , 
NN(
0, 
0, 
-1, 2.5421, 0, -1, 0.451534,-99) , 
0, 101.03, 1, 0, 0.476419,-99) , 
1, 206.347, 1, 0, 0.496201,-99)    );
  // itree = 35
  fBoostWeights.push_back(0.0796398);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.62955,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481054,-99) , 
3, 114.82, 0, 0, 0.566918,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517047,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.437185,-99) , 
1, 189.243, 1, 0, 0.503374,-99) , 
0, 144.508, 0, 0, 0.514915,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.552303,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470952,-99) , 
3, 120.907, 0, 0, 0.502584,-99) , 
NN(
0, 
0, 
-1, 2.43563, 0, -1, 0.42923,-99) , 
3, 180.545, 1, 0, 0.480593,-99) , 
1, 206.347, 1, 0, 0.503034,-99)    );
  // itree = 36
  fBoostWeights.push_back(0.0477005);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538816,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507799,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.447753,-99) , 
0, 69.5142, 0, 0, 0.502443,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545832,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.365915,-99) , 
1, 188.895, 1, 0, 0.447286,-99) , 
0, 162.573, 1, 0, 0.495253,-99) , 
2, 3.61694, 0, 0, 0.498796,-99)    );
  // itree = 37
  fBoostWeights.push_back(0.0577128);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526943,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514957,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46033,-99) , 
3, 148.964, 1, 0, 0.492578,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.43656,-99) , 
2, 3.27506, 1, 0, 0.486868,-99) , 
2, 3.61694, 0, 0, 0.490126,-99)    );
  // itree = 38
  fBoostWeights.push_back(0.0503803);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534472,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51901,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482159,-99) , 
2, 3.14495, 0, 0, 0.49106,-99) , 
NN(
0, 
0, 
-1, 2.91638, 1, -1, 0.441749,-99) , 
3, 57.6171, 0, 0, 0.483536,-99) , 
3, 295.557, 0, 0, 0.488134,-99)    );
  // itree = 39
  fBoostWeights.push_back(0.0772592);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 184.649, 1, 1, 0.596967,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.405447,-99) , 
2, 1.90954, 0, 0, 0.516362,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50863,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.450962,-99) , 
0, 162.573, 1, 0, 0.501179,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518786,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.379591,-99) , 
2, 3.68177, 0, 0, 0.436571,-99) , 
2, 3.27343, 1, 0, 0.488892,-99) , 
3, 222.076, 0, 0, 0.493756,-99)    );
  // itree = 40
  fBoostWeights.push_back(0.077133);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.614629,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502444,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.392273,-99) , 
2, 1.43734, 0, 0, 0.44868,-99) , 
2, 2.71329, 0, 0, 0.513406,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510914,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474766,-99) , 
2, 2.35519, 1, 0, 0.486849,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513148,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.384377,-99) , 
3, 117.093, 0, 0, 0.439704,-99) , 
2, 3.27343, 1, 0, 0.477919,-99) , 
3, 222.076, 0, 0, 0.484174,-99)    );
  // itree = 41
  fBoostWeights.push_back(0.0530525);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.625658,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500024,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454075,-99) , 
2, 3.25866, 1, 0, 0.486668,-99) , 
3, 240.183, 0, 0, 0.498894,-99) , 
NN(
0, 
0, 
-1, 162.662, 1, -1, 0.467941,-99) , 
2, 2.5421, 0, 0, 0.487451,-99)    );
  // itree = 42
  fBoostWeights.push_back(0.0323063);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525754,-99) , 
NN(
0, 
0, 
-1, 326.01, 1, -1, 0.484785,-99) , 
3, 295.557, 0, 0, 0.48841,-99)    );
  // itree = 43
  fBoostWeights.push_back(0.0678591);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.561045,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48668,-99) , 
3, 148.964, 0, 0, 0.515433,-99) , 
NN(
0, 
0, 
-1, 2.5421, 0, -1, 0.470042,-99) , 
1, 209.374, 1, 0, 0.501317,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530312,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477059,-99) , 
2, 2.87614, 1, 0, 0.50386,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.430933,-99) , 
3, 169.015, 1, 0, 0.481509,-99) , 
0, 100.936, 0, 0, 0.495054,-99)    );
  // itree = 44
  fBoostWeights.push_back(0.0449415);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 148.964, 0, 1, 0.519319,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509929,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.450439,-99) , 
2, 2.5421, 0, 0, 0.486974,-99) , 
1, 209.374, 1, 0, 0.50926,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51633,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489951,-99) , 
1, 180.691, 0, 0, 0.503755,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.447646,-99) , 
3, 169.015, 1, 0, 0.486593,-99) , 
0, 100.936, 0, 0, 0.502096,-99)    );
  // itree = 45
  fBoostWeights.push_back(0.0597351);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 3.20428, 0, 1, 0.57424,-99) , 
NN(
0, 
0, 
-1, 57.5338, 0, -1, 0.481082,-99) , 
3, 169.372, 0, 0, 0.505919,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531922,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485919,-99) , 
3, 92.9769, 0, 0, 0.507142,-99) , 
NN(
0, 
0, 
-1, 2.35442, 1, -1, 0.467244,-99) , 
3, 148.964, 1, 0, 0.49022,-99) , 
2, 2.90038, 0, 0, 0.497225,-99)    );
  // itree = 46
  fBoostWeights.push_back(0.0423392);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 217.343, 0, 1, 0.525213,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.434211,-99) , 
3, 57.5455, 0, 0, 0.512913,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.558683,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498351,-99) , 
2, 1.14204, 1, 0, 0.505413,-99) , 
NN(
0, 
0, 
-1, 1.53546, 0, -1, 0.468502,-99) , 
3, 222.426, 1, 0, 0.497212,-99) , 
2, 2.90038, 0, 0, 0.504217,-99)    );
  // itree = 47
  fBoostWeights.push_back(0.0208923);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534579,-99) , 
NN(
NN(
0, 
0, 
-1, 1.10898, 1, 1, 0.505788,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4532,-99) , 
1, 326.01, 1, 0, 0.502787,-99) , 
3, 295.557, 0, 0, 0.505571,-99)    );
  // itree = 48
  fBoostWeights.push_back(0.0290585);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529377,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540255,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514405,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489647,-99) , 
2, 2.33749, 1, 0, 0.495347,-99) , 
2, 1.10898, 1, 0, 0.49816,-99) , 
3, 295.557, 0, 0, 0.500892,-99)    );
  // itree = 49
  fBoostWeights.push_back(0.0449506);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.59659,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.573061,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491662,-99) , 
2, 3.73637, 0, 0, 0.500185,-99) , 
3, 240.183, 0, 0, 0.508411,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527484,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488094,-99) , 
1, 206.347, 0, 0, 0.502564,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.442175,-99) , 
0, 162.662, 1, 0, 0.494297,-99) , 
2, 2.5421, 0, 0, 0.503195,-99)    );
  // itree = 50
  fBoostWeights.push_back(0.0496427);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.585726,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520871,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479036,-99) , 
3, 149.253, 1, 0, 0.509074,-99) , 
3, 240.183, 0, 0, 0.515593,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516228,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476638,-99) , 
3, 222.426, 1, 0, 0.505549,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.453289,-99) , 
0, 162.662, 1, 0, 0.498406,-99) , 
2, 2.5421, 0, 0, 0.509242,-99)    );
  // itree = 51
  fBoostWeights.push_back(0.0316832);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.573632,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.554918,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497698,-99) , 
2, 3.73637, 0, 0, 0.503668,-99) , 
3, 240.183, 0, 0, 0.5096,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535695,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489208,-99) , 
2, 1.97894, 0, 0, 0.501406,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468289,-99) , 
2, 2.30323, 1, 0, 0.495164,-99) , 
2, 2.5421, 0, 0, 0.504265,-99)    );
  // itree = 52
  fBoostWeights.push_back(0.0514285);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 3.19731, 0, 1, 0.530908,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524546,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.436919,-99) , 
2, 3.25866, 1, 0, 0.497918,-99) , 
3, 120.908, 0, 0, 0.514671,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529637,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496693,-99) , 
0, 89.5488, 1, 0, 0.504421,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46985,-99) , 
0, 162.662, 1, 0, 0.499711,-99) , 
2, 2.5421, 0, 0, 0.509143,-99)    );
  // itree = 53
  fBoostWeights.push_back(0.0440226);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.44537, 0, 1, 0.543893,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516657,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477271,-99) , 
1, 212.06, 1, 0, 0.505341,-99) , 
3, 222.076, 0, 0, 0.512084,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528498,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494804,-99) , 
0, 89.801, 0, 0, 0.506638,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464498,-99) , 
3, 169.015, 1, 0, 0.493781,-99) , 
0, 100.936, 0, 0, 0.506296,-99)    );
  // itree = 54
  fBoostWeights.push_back(0.0184731);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526031,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.547518,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502173,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466227,-99) , 
3, 43.6209, 0, 0, 0.498995,-99) , 
2, 1.10898, 1, 0, 0.502047,-99) , 
3, 295.557, 0, 0, 0.504124,-99)    );
  // itree = 55
  fBoostWeights.push_back(0.01687);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521423,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542938,-99) , 
NN(
0, 
0, 
-1, 289.388, 1, -1, 0.495193,-99) , 
2, 1.10898, 1, 0, 0.498194,-99) , 
3, 295.557, 0, 0, 0.500205,-99)    );
  // itree = 56
  fBoostWeights.push_back(0.0468928);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520481,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.551591,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491473,-99) , 
1, 206.347, 0, 0, 0.511959,-99) , 
NN(
0, 
0, 
-1, 154.109, 1, -1, 0.474874,-99) , 
0, 126.897, 1, 0, 0.501302,-99) , 
0, 178.872, 0, 0, 0.503208,-99)    );
  // itree = 57
  fBoostWeights.push_back(0.0367215);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 144.508, 0, 1, 0.517581,-99) , 
NN(
0, 
0, 
-1, 180.545, 1, -1, 0.477525,-99) , 
1, 223.41, 1, 0, 0.508995,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48565,-99) , 
1, 326.01, 1, 0, 0.507481,-99)    );
  // itree = 58
  fBoostWeights.push_back(0.0205136);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517585,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536146,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507007,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491374,-99) , 
3, 113.602, 0, 0, 0.499513,-99) , 
2, 1.10898, 1, 0, 0.501808,-99) , 
3, 295.557, 0, 0, 0.503174,-99)    );
  // itree = 59
  fBoostWeights.push_back(0.0510164);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.544755,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524044,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.442588,-99) , 
2, 2.91638, 1, 0, 0.489033,-99) , 
3, 54.1099, 0, 0, 0.513795,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.621438,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485775,-99) , 
3, 164.707, 0, 0, 0.533484,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50101,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473981,-99) , 
2, 2.70053, 1, 0, 0.489015,-99) , 
2, 3.14495, 0, 0, 0.499007,-99) , 
3, 75.1137, 1, 0, 0.502256,-99)    );
  // itree = 60
  fBoostWeights.push_back(0.0359625);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.558755,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510201,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467392,-99) , 
2, 3.28118, 1, 0, 0.502355,-99) , 
2, 3.73637, 0, 0, 0.508148,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503216,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466446,-99) , 
2, 1.24188, 0, 0, 0.493974,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.447817,-99) , 
0, 162.662, 1, 0, 0.487721,-99) , 
2, 2.5421, 0, 0, 0.50059,-99)    );
  // itree = 61
  fBoostWeights.push_back(0.0334828);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.549871,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534249,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490707,-99) , 
2, 2.71266, 1, 0, 0.496659,-99) , 
2, 3.73637, 0, 0, 0.502117,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502421,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475552,-99) , 
2, 1.83282, 1, 0, 0.489499,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456725,-99) , 
0, 162.662, 1, 0, 0.485065,-99) , 
2, 2.5421, 0, 0, 0.495807,-99)    );
  // itree = 62
  fBoostWeights.push_back(0.0306436);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.54157,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52014,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496102,-99) , 
2, 3.16747, 0, 0, 0.502742,-99) , 
2, 3.73637, 0, 0, 0.50672,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509277,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475598,-99) , 
3, 148.964, 0, 0, 0.490918,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.455596,-99) , 
2, 0.870116, 0, 0, 0.485913,-99) , 
2, 2.5421, 0, 0, 0.49902,-99)    );
  // itree = 63
  fBoostWeights.push_back(0.0365057);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.544808,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513849,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485156,-99) , 
3, 149.253, 1, 0, 0.505748,-99) , 
3, 240.183, 0, 0, 0.509016,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527344,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485644,-99) , 
2, 1.10897, 1, 0, 0.493383,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458455,-99) , 
3, 295.888, 1, 0, 0.487584,-99) , 
2, 2.5421, 0, 0, 0.501086,-99)    );
  // itree = 64
  fBoostWeights.push_back(0.0179864);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.558814,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501731,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472245,-99) , 
1, 289.388, 1, 0, 0.498977,-99) , 
3, 295.557, 0, 0, 0.502838,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476879,-99) , 
2, 1.10898, 0, 0, 0.500643,-99)    );
  // itree = 65
  fBoostWeights.push_back(0.0434503);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.561008,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487227,-99) , 
2, 3.08303, 0, 0, 0.511621,-99) , 
NN(
0, 
0, 
-1, 109.532, 1, -1, 0.487483,-99) , 
3, 120.908, 0, 0, 0.499729,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514491,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462386,-99) , 
3, 152.111, 1, 0, 0.483871,-99) , 
2, 1.46726, 0, 0, 0.497626,-99)    );
  // itree = 66
  fBoostWeights.push_back(0.0289824);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540747,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508848,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.443383,-99) , 
2, 3.45588, 1, 0, 0.504464,-99) , 
2, 3.78759, 0, 0, 0.506952,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502992,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464022,-99) , 
2, 0.921217, 0, 0, 0.485758,-99) , 
2, 1.46726, 0, 0, 0.504142,-99)    );
  // itree = 67
  fBoostWeights.push_back(0.0157502);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.533542,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501603,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.450547,-99) , 
2, 3.45588, 1, 0, 0.498189,-99) , 
2, 3.78759, 0, 0, 0.500611,-99) , 
NN(
0, 
0, 
-1, 225.408, 1, -1, 0.484913,-99) , 
2, 1.46726, 0, 0, 0.49853,-99)    );
  // itree = 68
  fBoostWeights.push_back(0.0480223);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.544631,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499407,-99) , 
3, 120.957, 0, 0, 0.509899,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532711,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47191,-99) , 
3, 348.389, 0, 0, 0.481037,-99) , 
3, 148.964, 1, 0, 0.498177,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.555364,-99) , 
NN(
0, 
0, 
-1, 3.66816, 0, -1, 0.451165,-99) , 
3, 146.513, 0, 0, 0.486336,-99) , 
2, 3.25866, 1, 0, 0.496062,-99)    );
  // itree = 69
  fBoostWeights.push_back(0.0389729);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540443,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522687,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.453467,-99) , 
2, 2.91638, 1, 0, 0.492924,-99) , 
3, 54.1099, 0, 0, 0.514066,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.584263,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486235,-99) , 
3, 164.707, 0, 0, 0.520624,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501452,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486589,-99) , 
3, 145.12, 1, 0, 0.493426,-99) , 
2, 3.14495, 0, 0, 0.499495,-99) , 
3, 75.1137, 1, 0, 0.502702,-99)    );
  // itree = 70
  fBoostWeights.push_back(0.0355416);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 3.1488, 0, 1, 0.515347,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504909,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.452705,-99) , 
2, 2.66614, 1, 0, 0.497496,-99) , 
2, 2.79784, 0, 0, 0.504637,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538403,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513948,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.434585,-99) , 
2, 3.66816, 0, 0, 0.469887,-99) , 
3, 146.513, 0, 0, 0.492988,-99) , 
2, 3.25866, 1, 0, 0.502562,-99)    );
  // itree = 71
  fBoostWeights.push_back(0.0327998);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528799,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484068,-99) , 
3, 47.4967, 0, 0, 0.510301,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519473,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487089,-99) , 
2, 3.10448, 0, 0, 0.493928,-99) , 
3, 75.5026, 1, 0, 0.497353,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481587,-99) , 
2, 3.61694, 1, 0, 0.496084,-99)    );
  // itree = 72
  fBoostWeights.push_back(0.0220294);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 3.14879, 0, 1, 0.504094,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4753,-99) , 
2, 0.955369, 0, 0, 0.501914,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52762,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513263,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.438763,-99) , 
2, 3.66816, 0, 0, 0.471937,-99) , 
3, 146.513, 0, 0, 0.49069,-99) , 
2, 3.25866, 1, 0, 0.499915,-99)    );
  // itree = 73
  fBoostWeights.push_back(0.043113);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519152,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495205,-99) , 
3, 148.964, 0, 0, 0.504991,-99) , 
NN(
0, 
0, 
-1, 3.66814, 1, -1, 0.469571,-99) , 
2, 3.25866, 1, 0, 0.498369,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.555151,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46621,-99) , 
0, 68.2368, 0, 0, 0.514288,-99) , 
NN(
0, 
0, 
-1, 130.821, 1, -1, 0.469964,-99) , 
0, 82.3788, 1, 0, 0.490299,-99) , 
0, 100.936, 0, 0, 0.495814,-99)    );
  // itree = 74
  fBoostWeights.push_back(0.0587463);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522559,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471949,-99) , 
0, 128.364, 1, 0, 0.509824,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454568,-99) , 
0, 170.576, 1, 0, 0.504336,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531453,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464429,-99) , 
1, 209.374, 1, 0, 0.508752,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462562,-99) , 
0, 103.811, 0, 0, 0.493314,-99) , 
3, 148.595, 1, 0, 0.500005,-99)    );
  // itree = 75
  fBoostWeights.push_back(0.0582001);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532033,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470765,-99) , 
1, 299.423, 1, 0, 0.517972,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475521,-99) , 
3, 180.545, 1, 0, 0.505336,-99) , 
NN(
NN(
0, 
0, 
-1, 162.123, 1, 1, 0.562927,-99) , 
NN(
0, 
0, 
-1, 155.057, 0, -1, 0.478451,-99) , 
0, 144.508, 0, 0, 0.493515,-99) , 
1, 206.347, 0, 0, 0.497587,-99)    );
  // itree = 76
  fBoostWeights.push_back(0.0166995);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518082,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540223,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512256,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496385,-99) , 
3, 183.583, 0, 0, 0.499362,-99) , 
2, 1.10898, 1, 0, 0.501935,-99) , 
3, 295.557, 0, 0, 0.503315,-99)    );
  // itree = 77
  fBoostWeights.push_back(0.0313146);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 144.508, 0, 1, 0.516584,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504158,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464657,-99) , 
3, 180.545, 1, 0, 0.495074,-99) , 
1, 191.063, 1, 0, 0.507388,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.54326,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485803,-99) , 
2, 1.46717, 0, 0, 0.514619,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501627,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47533,-99) , 
2, 1.47484, 1, 0, 0.488327,-99) , 
1, 206.347, 0, 0, 0.498378,-99) , 
2, 2.18382, 0, 0, 0.504954,-99)    );
  // itree = 78
  fBoostWeights.push_back(0.0148488);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51408,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534056,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501579,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490953,-99) , 
2, 2.95167, 1, 0, 0.49675,-99) , 
2, 1.10898, 1, 0, 0.499096,-99) , 
3, 295.557, 0, 0, 0.500377,-99)    );
  // itree = 79
  fBoostWeights.push_back(0.0261558);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531415,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525734,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494957,-99) , 
2, 2.71266, 1, 0, 0.499175,-99) , 
2, 3.73637, 0, 0, 0.502492,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529052,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489028,-99) , 
2, 1.97894, 0, 0, 0.499509,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473239,-99) , 
2, 2.30323, 1, 0, 0.494575,-99) , 
2, 2.5421, 0, 0, 0.499556,-99)    );
  // itree = 80
  fBoostWeights.push_back(0.0318672);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536711,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494878,-99) , 
1, 155.387, 0, 0, 0.519802,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509722,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480591,-99) , 
2, 3.34397, 0, 0, 0.490882,-99) , 
1, 193.893, 1, 0, 0.508195,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523139,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498833,-99) , 
2, 1.91236, 0, 0, 0.507119,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503376,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.433541,-99) , 
2, 2.53657, 0, 0, 0.488679,-99) , 
2, 2.35442, 1, 0, 0.499224,-99) , 
2, 2.90038, 0, 0, 0.503206,-99)    );
  // itree = 81
  fBoostWeights.push_back(0.0183317);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518872,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.544782,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503269,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489254,-99) , 
2, 2.64458, 0, 0, 0.498522,-99) , 
2, 1.10898, 1, 0, 0.501438,-99) , 
3, 295.557, 0, 0, 0.502927,-99)    );
  // itree = 82
  fBoostWeights.push_back(0.0278782);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521493,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496915,-99) , 
1, 206.347, 0, 0, 0.504957,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53425,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.446984,-99) , 
1, 188.895, 1, 0, 0.486753,-99) , 
0, 162.573, 1, 0, 0.502641,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482316,-99) , 
2, 3.61694, 1, 0, 0.501004,-99)    );
  // itree = 83
  fBoostWeights.push_back(0.0246);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515599,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498537,-99) , 
0, 109.384, 0, 0, 0.507367,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527307,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.453885,-99) , 
1, 188.895, 1, 0, 0.487354,-99) , 
0, 162.573, 1, 0, 0.504823,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48928,-99) , 
2, 3.61694, 1, 0, 0.503572,-99)    );
  // itree = 84
  fBoostWeights.push_back(0.0338236);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.555178,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491394,-99) , 
3, 151.616, 0, 0, 0.525743,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483539,-99) , 
2, 0.97242, 0, 0, 0.511769,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510086,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464976,-99) , 
1, 241.124, 1, 0, 0.505296,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471186,-99) , 
1, 289.388, 1, 0, 0.502085,-99) , 
2, 1.82554, 1, 0, 0.503958,-99)    );
  // itree = 85
  fBoostWeights.push_back(0.0268279);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.54681,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499849,-99) , 
3, 151.616, 0, 0, 0.52512,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49199,-99) , 
2, 0.97242, 0, 0, 0.514147,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524231,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527476,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490915,-99) , 
3, 240.513, 0, 0, 0.494457,-99) , 
2, 3.73641, 0, 0, 0.496847,-99) , 
2, 1.82554, 1, 0, 0.500192,-99)    );
  // itree = 86
  fBoostWeights.push_back(0.022166);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538443,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523442,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480955,-99) , 
3, 225.408, 1, 0, 0.506551,-99) , 
2, 1.48421, 0, 0, 0.516034,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52188,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497991,-99) , 
3, 180.545, 0, 0, 0.503189,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482927,-99) , 
1, 289.388, 1, 0, 0.501282,-99) , 
2, 1.82554, 1, 0, 0.504134,-99)    );
  // itree = 87
  fBoostWeights.push_back(0.0190516);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.537444,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499205,-99) , 
1, 191.77, 1, 0, 0.521512,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524411,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498722,-99) , 
2, 3.10448, 0, 0, 0.504142,-99) , 
3, 75.5026, 1, 0, 0.507776,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490301,-99) , 
2, 3.61694, 1, 0, 0.506371,-99)    );
  // itree = 88
  fBoostWeights.push_back(0.0344196);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525178,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521213,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482681,-99) , 
2, 3.27343, 1, 0, 0.514014,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50476,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470025,-99) , 
1, 223.388, 1, 0, 0.496896,-99) , 
3, 148.595, 1, 0, 0.507477,-99) , 
1, 326.01, 0, 0, 0.508605,-99)    );
  // itree = 89
  fBoostWeights.push_back(0.0340369);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.546881,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514815,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478792,-99) , 
3, 118.081, 0, 0, 0.503435,-99) , 
3, 61.27, 1, 0, 0.509897,-99) , 
NN(
NN(
0, 
0, 
-1, 162.123, 1, 1, 0.536027,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501386,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459125,-99) , 
1, 143.661, 0, 0, 0.491971,-99) , 
0, 144.508, 0, 0, 0.499775,-99) , 
1, 206.347, 0, 0, 0.503256,-99)    );
  // itree = 90
  fBoostWeights.push_back(0.0317837);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538434,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519379,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4922,-99) , 
2, 2.14494, 1, 0, 0.500303,-99) , 
3, 61.27, 1, 0, 0.505969,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.566751,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495764,-99) , 
1, 162.123, 1, 0, 0.527552,-99) , 
NN(
0, 
0, 
-1, 189.243, 1, -1, 0.487249,-99) , 
0, 144.508, 0, 0, 0.494383,-99) , 
1, 206.347, 0, 0, 0.498368,-99)    );
  // itree = 91
  fBoostWeights.push_back(0.0243094);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 217.343, 0, 1, 0.514436,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474447,-99) , 
3, 57.5455, 0, 0, 0.509009,-99) , 
NN(
NN(
0, 
0, 
-1, 1.14204, 1, 1, 0.505044,-99) , 
NN(
0, 
0, 
-1, 1.80843, 1, -1, 0.476513,-99) , 
3, 222.426, 1, 0, 0.498727,-99) , 
2, 2.90038, 0, 0, 0.503289,-99)    );
  // itree = 92
  fBoostWeights.push_back(0.0310488);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540254,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530052,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487602,-99) , 
3, 170.103, 0, 0, 0.499006,-99) , 
2, 3.78756, 0, 0, 0.504584,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526237,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498991,-99) , 
0, 92.8802, 1, 0, 0.505414,-99) , 
NN(
0, 
0, 
-1, 2.61453, 0, -1, 0.481882,-99) , 
2, 2.35442, 1, 0, 0.49534,-99) , 
2, 2.90038, 0, 0, 0.499441,-99)    );
  // itree = 93
  fBoostWeights.push_back(0.0495984);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522991,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48726,-99) , 
0, 128.364, 1, 0, 0.514006,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.45179,-99) , 
0, 170.576, 1, 0, 0.507929,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.552603,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517351,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473586,-99) , 
2, 2.30803, 1, 0, 0.488001,-99) , 
3, 348.064, 0, 0, 0.496655,-99) , 
3, 148.595, 1, 0, 0.503509,-99)    );
  // itree = 94
  fBoostWeights.push_back(0.0273761);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 217.343, 0, 1, 0.512475,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478346,-99) , 
3, 57.5455, 0, 0, 0.507842,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507771,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477877,-99) , 
0, 92.8802, 0, 0, 0.500663,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468942,-99) , 
3, 295.888, 1, 0, 0.496718,-99) , 
2, 2.90038, 0, 0, 0.501652,-99)    );
  // itree = 95
  fBoostWeights.push_back(0.0280013);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530246,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526003,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48853,-99) , 
3, 170.103, 0, 0, 0.49859,-99) , 
2, 3.78756, 0, 0, 0.502858,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526794,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492941,-99) , 
2, 1.12604, 1, 0, 0.497073,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475765,-99) , 
3, 295.888, 1, 0, 0.494424,-99) , 
2, 2.90038, 0, 0, 0.498165,-99)    );
  // itree = 96
  fBoostWeights.push_back(0.019317);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 3.1695, 0, 1, 0.509244,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515596,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492756,-99) , 
3, 75.5026, 1, 0, 0.498115,-99) , 
2, 2.76333, 0, 0, 0.503509,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485364,-99) , 
2, 3.61694, 1, 0, 0.502053,-99)    );
  // itree = 97
  fBoostWeights.push_back(0.0145159);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515252,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525192,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502997,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490752,-99) , 
3, 141.594, 1, 0, 0.498556,-99) , 
2, 1.10898, 1, 0, 0.500234,-99) , 
3, 295.557, 0, 0, 0.501503,-99)    );
  // itree = 98
  fBoostWeights.push_back(0.0142359);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511626,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521571,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505071,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493999,-99) , 
0, 100.936, 1, 0, 0.497559,-99) , 
2, 1.10898, 1, 0, 0.499072,-99) , 
3, 295.557, 0, 0, 0.500132,-99)    );
  // itree = 99
  fBoostWeights.push_back(0.0180996);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516491,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497101,-99) , 
1, 206.347, 0, 0, 0.503436,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508526,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464961,-99) , 
2, 2.59219, 0, 0, 0.489274,-99) , 
0, 162.573, 1, 0, 0.501642,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490095,-99) , 
2, 3.61694, 1, 0, 0.500716,-99)    );
   return;
};
 
// Clean up
inline void ReadBDT::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDT::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
